// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addGroupAccessLevel = `-- name: AddGroupAccessLevel :exec
INSERT INTO groups_access_levels (group_id, access_level_id) VALUES (?, ?)
ON DUPLICATE KEY UPDATE group_id = group_id
`

type AddGroupAccessLevelParams struct {
	GroupID       int32 `json:"group_id"`
	AccessLevelID int32 `json:"access_level_id"`
}

func (q *Queries) AddGroupAccessLevel(ctx context.Context, arg AddGroupAccessLevelParams) error {
	_, err := q.db.ExecContext(ctx, addGroupAccessLevel, arg.GroupID, arg.AccessLevelID)
	return err
}

const addUserAccessLevel = `-- name: AddUserAccessLevel :exec
INSERT INTO users_access_levels (user_id, access_level_id) VALUES (?, ?)
ON DUPLICATE KEY UPDATE user_id = user_id
`

type AddUserAccessLevelParams struct {
	UserID        int32 `json:"user_id"`
	AccessLevelID int32 `json:"access_level_id"`
}

func (q *Queries) AddUserAccessLevel(ctx context.Context, arg AddUserAccessLevelParams) error {
	_, err := q.db.ExecContext(ctx, addUserAccessLevel, arg.UserID, arg.AccessLevelID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO users_groups (user_id, group_id) VALUES (?, ?)
ON DUPLICATE KEY UPDATE user_id = user_id
`

type AddUserToGroupParams struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const countAccessLevels = `-- name: CountAccessLevels :one
SELECT COUNT(*)
FROM access_level
WHERE (? = '' OR name LIKE ?)
`

type CountAccessLevelsParams struct {
	Column1 interface{} `json:"column_1"`
	Name    string      `json:"name"`
}

func (q *Queries) CountAccessLevels(ctx context.Context, arg CountAccessLevelsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessLevels, arg.Column1, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT COUNT(*)
FROM ` + "`" + `groups` + "`" + `
WHERE deleted_at IS NULL
  AND (? = '' OR name LIKE ?)
`

type CountGroupsParams struct {
	Column1 interface{} `json:"column_1"`
	Name    string      `json:"name"`
}

func (q *Queries) CountGroups(ctx context.Context, arg CountGroupsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups, arg.Column1, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM ` + "`" + `user` + "`" + `
WHERE deleted_at IS NULL
  AND (? = '' OR name LIKE ? OR email LIKE ?)
`

type CountUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Column1, arg.Name, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessLevel = `-- name: CreateAccessLevel :execresult
INSERT INTO access_level (name) VALUES (?)
`

func (q *Queries) CreateAccessLevel(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccessLevel, name)
}

const createAccessLevelModule = `-- name: CreateAccessLevelModule :exec
INSERT INTO access_levels_modules (access_level_id, module_id, permission, data_scope, can_be_assigned)
VALUES (?, ?, ?, ?, ?)
`

type CreateAccessLevelModuleParams struct {
	AccessLevelID int32  `json:"access_level_id"`
	ModuleID      int32  `json:"module_id"`
	Permission    int32  `json:"permission"`
	DataScope     string `json:"data_scope"`
	CanBeAssigned bool   `json:"can_be_assigned"`
}

func (q *Queries) CreateAccessLevelModule(ctx context.Context, arg CreateAccessLevelModuleParams) error {
	_, err := q.db.ExecContext(ctx, createAccessLevelModule,
		arg.AccessLevelID,
		arg.ModuleID,
		arg.Permission,
		arg.DataScope,
		arg.CanBeAssigned,
	)
	return err
}

const createGroup = `-- name: CreateGroup :execresult
INSERT INTO ` + "`" + `groups` + "`" + ` (name, parent_id)
VALUES (?, ?)
`

type CreateGroupParams struct {
	Name     string        `json:"name"`
	ParentID sql.NullInt32 `json:"parent_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGroup, arg.Name, arg.ParentID)
}

const createMenu = `-- name: CreateMenu :execresult
INSERT INTO menu (name, sort_index, paths, module_id, parent_id, required_scope)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMenuParams struct {
	Name          string         `json:"name"`
	SortIndex     int32          `json:"sort_index"`
	Paths         string         `json:"paths"`
	ModuleID      int32          `json:"module_id"`
	ParentID      sql.NullInt32  `json:"parent_id"`
	RequiredScope sql.NullString `json:"required_scope"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMenu,
		arg.Name,
		arg.SortIndex,
		arg.Paths,
		arg.ModuleID,
		arg.ParentID,
		arg.RequiredScope,
	)
}

const createModule = `-- name: CreateModule :execresult
INSERT INTO module (name) VALUES (?)
`

func (q *Queries) CreateModule(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createModule, name)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO ` + "`" + `user` + "`" + ` (name, last_name, email, password, is_active)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Name     string         `json:"name"`
	LastName sql.NullString `json:"last_name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.IsActive,
	)
}

const deleteAccessLevel = `-- name: DeleteAccessLevel :execrows
DELETE FROM access_level WHERE access_level_id = ?
`

func (q *Queries) DeleteAccessLevel(ctx context.Context, accessLevelID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccessLevel, accessLevelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAccessLevelModule = `-- name: DeleteAccessLevelModule :exec
DELETE FROM access_levels_modules
WHERE access_level_id = ? AND module_id = ?
`

type DeleteAccessLevelModuleParams struct {
	AccessLevelID int32 `json:"access_level_id"`
	ModuleID      int32 `json:"module_id"`
}

func (q *Queries) DeleteAccessLevelModule(ctx context.Context, arg DeleteAccessLevelModuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccessLevelModule, arg.AccessLevelID, arg.ModuleID)
	return err
}

const deleteAllModulesFromAccessLevel = `-- name: DeleteAllModulesFromAccessLevel :exec
DELETE FROM access_levels_modules WHERE access_level_id = ?
`

func (q *Queries) DeleteAllModulesFromAccessLevel(ctx context.Context, accessLevelID int32) error {
	_, err := q.db.ExecContext(ctx, deleteAllModulesFromAccessLevel, accessLevelID)
	return err
}

const deleteMenu = `-- name: DeleteMenu :execrows
DELETE FROM menu WHERE menu_id = ?
`

func (q *Queries) DeleteMenu(ctx context.Context, menuID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMenu, menuID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteModule = `-- name: DeleteModule :execrows
DELETE FROM module WHERE module_id = ?
`

func (q *Queries) DeleteModule(ctx context.Context, moduleID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteModule, moduleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccessLevelByID = `-- name: GetAccessLevelByID :one

SELECT access_level_id, name
FROM access_level
WHERE access_level_id = ?
LIMIT 1
`

// ============================================================
// ACCESS LEVEL
// ============================================================
func (q *Queries) GetAccessLevelByID(ctx context.Context, accessLevelID int32) (AccessLevel, error) {
	row := q.db.QueryRowContext(ctx, getAccessLevelByID, accessLevelID)
	var i AccessLevel
	err := row.Scan(&i.AccessLevelID, &i.Name)
	return i, err
}

const getAccessLevelByName = `-- name: GetAccessLevelByName :one
SELECT access_level_id, name
FROM access_level
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetAccessLevelByName(ctx context.Context, name string) (AccessLevel, error) {
	row := q.db.QueryRowContext(ctx, getAccessLevelByName, name)
	var i AccessLevel
	err := row.Scan(&i.AccessLevelID, &i.Name)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one

SELECT group_id, name, parent_id, created_at, updated_at, deleted_at
FROM ` + "`" + `groups` + "`" + `
WHERE group_id = ? AND deleted_at IS NULL
LIMIT 1
`

// ============================================================
// GROUP
// ============================================================
func (q *Queries) GetGroupByID(ctx context.Context, groupID int32) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, groupID)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT group_id, name, parent_id, created_at, updated_at, deleted_at
FROM ` + "`" + `groups` + "`" + `
WHERE name = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMenuByID = `-- name: GetMenuByID :one

SELECT menu_id, name, sort_index, paths, module_id, parent_id, required_scope
FROM menu WHERE menu_id = ? LIMIT 1
`

// ============================================================
// MENU
// ============================================================
func (q *Queries) GetMenuByID(ctx context.Context, menuID int32) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenuByID, menuID)
	var i Menu
	err := row.Scan(
		&i.MenuID,
		&i.Name,
		&i.SortIndex,
		&i.Paths,
		&i.ModuleID,
		&i.ParentID,
		&i.RequiredScope,
	)
	return i, err
}

const getModuleByID = `-- name: GetModuleByID :one

SELECT module_id, name FROM module WHERE module_id = ? LIMIT 1
`

// ============================================================
// MODULE
// ============================================================
func (q *Queries) GetModuleByID(ctx context.Context, moduleID int32) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModuleByID, moduleID)
	var i Module
	err := row.Scan(&i.ModuleID, &i.Name)
	return i, err
}

const getModuleByName = `-- name: GetModuleByName :one
SELECT module_id, name FROM module WHERE name = ? LIMIT 1
`

func (q *Queries) GetModuleByName(ctx context.Context, name string) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModuleByName, name)
	var i Module
	err := row.Scan(&i.ModuleID, &i.Name)
	return i, err
}

const getModulePermForAccessLevel = `-- name: GetModulePermForAccessLevel :one
SELECT access_level_module_id, access_level_id, module_id, data_scope, permission, can_be_assigned
FROM access_levels_modules
WHERE access_level_id = ? AND module_id = ?
LIMIT 1
`

type GetModulePermForAccessLevelParams struct {
	AccessLevelID int32 `json:"access_level_id"`
	ModuleID      int32 `json:"module_id"`
}

type GetModulePermForAccessLevelRow struct {
	AccessLevelModuleID int32  `json:"access_level_module_id"`
	AccessLevelID       int32  `json:"access_level_id"`
	ModuleID            int32  `json:"module_id"`
	DataScope           string `json:"data_scope"`
	Permission          int32  `json:"permission"`
	CanBeAssigned       bool   `json:"can_be_assigned"`
}

func (q *Queries) GetModulePermForAccessLevel(ctx context.Context, arg GetModulePermForAccessLevelParams) (GetModulePermForAccessLevelRow, error) {
	row := q.db.QueryRowContext(ctx, getModulePermForAccessLevel, arg.AccessLevelID, arg.ModuleID)
	var i GetModulePermForAccessLevelRow
	err := row.Scan(
		&i.AccessLevelModuleID,
		&i.AccessLevelID,
		&i.ModuleID,
		&i.DataScope,
		&i.Permission,
		&i.CanBeAssigned,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT user_id, name, last_name, email, password, is_active, created_at, updated_at, deleted_at
FROM ` + "`" + `user` + "`" + `
WHERE email = ? AND deleted_at IS NULL
LIMIT 1
`

// ============================================================
// USER
// ============================================================
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, name, last_name, email, password, is_active, created_at, updated_at, deleted_at
FROM ` + "`" + `user` + "`" + `
WHERE user_id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccessLevelsByGroupID = `-- name: ListAccessLevelsByGroupID :many

SELECT al.access_level_id, al.name
FROM access_level al
INNER JOIN groups_access_levels gal ON gal.access_level_id = al.access_level_id
WHERE gal.group_id = ?
`

// ============================================================
// GROUP-ACCESS LEVEL RELATIONS
// ============================================================
func (q *Queries) ListAccessLevelsByGroupID(ctx context.Context, groupID int32) ([]AccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, listAccessLevelsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(&i.AccessLevelID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessLevelsByUserID = `-- name: ListAccessLevelsByUserID :many

SELECT al.access_level_id, al.name
FROM access_level al
INNER JOIN users_access_levels ual ON ual.access_level_id = al.access_level_id
WHERE ual.user_id = ?
`

// ============================================================
// USER-ACCESS LEVEL RELATIONS
// ============================================================
func (q *Queries) ListAccessLevelsByUserID(ctx context.Context, userID int32) ([]AccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, listAccessLevelsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(&i.AccessLevelID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessLevelsPaginated = `-- name: ListAccessLevelsPaginated :many
SELECT access_level_id, name
FROM access_level
WHERE (? = '' OR name LIKE ?)
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListAccessLevelsPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Name    string      `json:"name"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAccessLevelsPaginated(ctx context.Context, arg ListAccessLevelsPaginatedParams) ([]AccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, listAccessLevelsPaginated,
		arg.Column1,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(&i.AccessLevelID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many

SELECT g.group_id, g.name
FROM ` + "`" + `groups` + "`" + ` g
INNER JOIN users_groups ug ON ug.group_id = g.group_id
WHERE ug.user_id = ? AND g.deleted_at IS NULL
`

type ListGroupsByUserIDRow struct {
	GroupID int32  `json:"group_id"`
	Name    string `json:"name"`
}

// ============================================================
// USER-GROUP RELATIONS
// ============================================================
func (q *Queries) ListGroupsByUserID(ctx context.Context, userID int32) ([]ListGroupsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsByUserIDRow
	for rows.Next() {
		var i ListGroupsByUserIDRow
		if err := rows.Scan(&i.GroupID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsPaginated = `-- name: ListGroupsPaginated :many
SELECT group_id, name, parent_id, created_at, updated_at
FROM ` + "`" + `groups` + "`" + `
WHERE deleted_at IS NULL
  AND (? = '' OR name LIKE ?)
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListGroupsPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Name    string      `json:"name"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListGroupsPaginatedRow struct {
	GroupID   int32         `json:"group_id"`
	Name      string        `json:"name"`
	ParentID  sql.NullInt32 `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

func (q *Queries) ListGroupsPaginated(ctx context.Context, arg ListGroupsPaginatedParams) ([]ListGroupsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsPaginated,
		arg.Column1,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsPaginatedRow
	for rows.Next() {
		var i ListGroupsPaginatedRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenus = `-- name: ListMenus :many
SELECT menu_id, name, sort_index, paths, module_id, parent_id, required_scope
FROM menu ORDER BY sort_index ASC
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.MenuID,
			&i.Name,
			&i.SortIndex,
			&i.Paths,
			&i.ModuleID,
			&i.ParentID,
			&i.RequiredScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulePermsByAccessLevelID = `-- name: ListModulePermsByAccessLevelID :many

SELECT alm.access_level_module_id, alm.access_level_id, alm.module_id,
       alm.data_scope, alm.permission, alm.can_be_assigned, m.name AS module_name
FROM access_levels_modules alm
INNER JOIN module m ON m.module_id = alm.module_id
WHERE alm.access_level_id = ?
`

type ListModulePermsByAccessLevelIDRow struct {
	AccessLevelModuleID int32  `json:"access_level_module_id"`
	AccessLevelID       int32  `json:"access_level_id"`
	ModuleID            int32  `json:"module_id"`
	DataScope           string `json:"data_scope"`
	Permission          int32  `json:"permission"`
	CanBeAssigned       bool   `json:"can_be_assigned"`
	ModuleName          string `json:"module_name"`
}

// ============================================================
// ACCESS LEVEL-MODULE RELATIONS
// ============================================================
func (q *Queries) ListModulePermsByAccessLevelID(ctx context.Context, accessLevelID int32) ([]ListModulePermsByAccessLevelIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listModulePermsByAccessLevelID, accessLevelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModulePermsByAccessLevelIDRow
	for rows.Next() {
		var i ListModulePermsByAccessLevelIDRow
		if err := rows.Scan(
			&i.AccessLevelModuleID,
			&i.AccessLevelID,
			&i.ModuleID,
			&i.DataScope,
			&i.Permission,
			&i.CanBeAssigned,
			&i.ModuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT module_id, name FROM module ORDER BY name ASC
`

func (q *Queries) ListModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(&i.ModuleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, name, last_name, email, is_active, created_at, updated_at
FROM ` + "`" + `user` + "`" + `
WHERE deleted_at IS NULL
ORDER BY name ASC
`

type ListUsersRow struct {
	UserID    int32          `json:"user_id"`
	Name      string         `json:"name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.LastName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByGroupID = `-- name: ListUsersByGroupID :many

SELECT u.user_id, u.name, u.last_name, u.email, u.is_active
FROM ` + "`" + `user` + "`" + ` u
INNER JOIN users_groups ug ON ug.user_id = u.user_id
WHERE ug.group_id = ? AND u.deleted_at IS NULL
ORDER BY u.name ASC
`

type ListUsersByGroupIDRow struct {
	UserID   int32          `json:"user_id"`
	Name     string         `json:"name"`
	LastName sql.NullString `json:"last_name"`
	Email    string         `json:"email"`
	IsActive bool           `json:"is_active"`
}

// ============================================================
// USER-GROUP (by group)
// ============================================================
func (q *Queries) ListUsersByGroupID(ctx context.Context, groupID int32) ([]ListUsersByGroupIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByGroupIDRow
	for rows.Next() {
		var i ListUsersByGroupIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.LastName,
			&i.Email,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT user_id, name, last_name, email, is_active, created_at, updated_at
FROM ` + "`" + `user` + "`" + `
WHERE deleted_at IS NULL
  AND (? = '' OR name LIKE ? OR email LIKE ?)
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListUsersPaginatedParams struct {
	Column1 interface{} `json:"column_1"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListUsersPaginatedRow struct {
	UserID    int32          `json:"user_id"`
	Name      string         `json:"name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaginated,
		arg.Column1,
		arg.Name,
		arg.Email,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPaginatedRow
	for rows.Next() {
		var i ListUsersPaginatedRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.LastName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllAccessLevelsFromGroup = `-- name: RemoveAllAccessLevelsFromGroup :exec
DELETE FROM groups_access_levels WHERE group_id = ?
`

func (q *Queries) RemoveAllAccessLevelsFromGroup(ctx context.Context, groupID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllAccessLevelsFromGroup, groupID)
	return err
}

const removeAllAccessLevelsFromUser = `-- name: RemoveAllAccessLevelsFromUser :exec
DELETE FROM users_access_levels WHERE user_id = ?
`

func (q *Queries) RemoveAllAccessLevelsFromUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllAccessLevelsFromUser, userID)
	return err
}

const removeAllGroupsFromUser = `-- name: RemoveAllGroupsFromUser :exec
DELETE FROM users_groups WHERE user_id = ?
`

func (q *Queries) RemoveAllGroupsFromUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllGroupsFromUser, userID)
	return err
}

const removeAllUsersFromGroup = `-- name: RemoveAllUsersFromGroup :exec
DELETE FROM users_groups WHERE group_id = ?
`

func (q *Queries) RemoveAllUsersFromGroup(ctx context.Context, groupID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllUsersFromGroup, groupID)
	return err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE ` + "`" + `groups` + "`" + `
SET deleted_at = NOW()
WHERE group_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, groupID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteGroup, groupID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE ` + "`" + `user` + "`" + `
SET deleted_at = NOW()
WHERE user_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, userID)
	return err
}

const updateAccessLevelModule = `-- name: UpdateAccessLevelModule :exec
UPDATE access_levels_modules
SET permission = ?, data_scope = ?, can_be_assigned = ?
WHERE access_level_id = ? AND module_id = ?
`

type UpdateAccessLevelModuleParams struct {
	Permission    int32  `json:"permission"`
	DataScope     string `json:"data_scope"`
	CanBeAssigned bool   `json:"can_be_assigned"`
	AccessLevelID int32  `json:"access_level_id"`
	ModuleID      int32  `json:"module_id"`
}

func (q *Queries) UpdateAccessLevelModule(ctx context.Context, arg UpdateAccessLevelModuleParams) error {
	_, err := q.db.ExecContext(ctx, updateAccessLevelModule,
		arg.Permission,
		arg.DataScope,
		arg.CanBeAssigned,
		arg.AccessLevelID,
		arg.ModuleID,
	)
	return err
}

const updateAccessLevelName = `-- name: UpdateAccessLevelName :exec
UPDATE access_level SET name = ? WHERE access_level_id = ?
`

type UpdateAccessLevelNameParams struct {
	Name          string `json:"name"`
	AccessLevelID int32  `json:"access_level_id"`
}

func (q *Queries) UpdateAccessLevelName(ctx context.Context, arg UpdateAccessLevelNameParams) error {
	_, err := q.db.ExecContext(ctx, updateAccessLevelName, arg.Name, arg.AccessLevelID)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE ` + "`" + `groups` + "`" + `
SET name = ?
WHERE group_id = ? AND deleted_at IS NULL
`

type UpdateGroupNameParams struct {
	Name    string `json:"name"`
	GroupID int32  `json:"group_id"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupName, arg.Name, arg.GroupID)
	return err
}

const updateMenu = `-- name: UpdateMenu :exec
UPDATE menu
SET name = ?, sort_index = ?, paths = ?, module_id = ?, parent_id = ?, required_scope = ?
WHERE menu_id = ?
`

type UpdateMenuParams struct {
	Name          string         `json:"name"`
	SortIndex     int32          `json:"sort_index"`
	Paths         string         `json:"paths"`
	ModuleID      int32          `json:"module_id"`
	ParentID      sql.NullInt32  `json:"parent_id"`
	RequiredScope sql.NullString `json:"required_scope"`
	MenuID        int32          `json:"menu_id"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) error {
	_, err := q.db.ExecContext(ctx, updateMenu,
		arg.Name,
		arg.SortIndex,
		arg.Paths,
		arg.ModuleID,
		arg.ParentID,
		arg.RequiredScope,
		arg.MenuID,
	)
	return err
}

const updateModule = `-- name: UpdateModule :exec
UPDATE module SET name = ? WHERE module_id = ?
`

type UpdateModuleParams struct {
	Name     string `json:"name"`
	ModuleID int32  `json:"module_id"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) error {
	_, err := q.db.ExecContext(ctx, updateModule, arg.Name, arg.ModuleID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE ` + "`" + `user` + "`" + `
SET name = ?, last_name = ?, email = ?, is_active = ?
WHERE user_id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Name     string         `json:"name"`
	LastName sql.NullString `json:"last_name"`
	Email    string         `json:"email"`
	IsActive bool           `json:"is_active"`
	UserID   int32          `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.LastName,
		arg.Email,
		arg.IsActive,
		arg.UserID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE ` + "`" + `user` + "`" + `
SET password = ?
WHERE user_id = ? AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.UserID)
	return err
}
