// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: commercial.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignCommercialOrder = `-- name: AssignCommercialOrder :exec
UPDATE commercial_order SET assigned_to_id=?, assigned_to_name=?
WHERE commercial_order_id=? AND deleted_at IS NULL
`

type AssignCommercialOrderParams struct {
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	CommercialOrderID int32          `json:"commercial_order_id"`
}

func (q *Queries) AssignCommercialOrder(ctx context.Context, arg AssignCommercialOrderParams) error {
	_, err := q.db.ExecContext(ctx, assignCommercialOrder, arg.AssignedToID, arg.AssignedToName, arg.CommercialOrderID)
	return err
}

const createCommercialOrder = `-- name: CreateCommercialOrder :execresult

INSERT INTO commercial_order (requester_id, requester_name, assigned_to_id, assigned_to_name,
    salesperson_name, client_code, client_name, client_alias_name,
    status_id, priority_id, reason_id, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCommercialOrderParams struct {
	RequesterID     int32          `json:"requester_id"`
	RequesterName   string         `json:"requester_name"`
	AssignedToID    sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName  sql.NullString `json:"assigned_to_name"`
	SalespersonName sql.NullString `json:"salesperson_name"`
	ClientCode      string         `json:"client_code"`
	ClientName      string         `json:"client_name"`
	ClientAliasName string         `json:"client_alias_name"`
	StatusID        int32          `json:"status_id"`
	PriorityID      int32          `json:"priority_id"`
	ReasonID        int32          `json:"reason_id"`
	Description     string         `json:"description"`
}

// ── Commercial Orders ─────────────────────────────────────────────────────────
func (q *Queries) CreateCommercialOrder(ctx context.Context, arg CreateCommercialOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialOrder,
		arg.RequesterID,
		arg.RequesterName,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
	)
}

const createCommercialOrderAttachment = `-- name: CreateCommercialOrderAttachment :execresult

INSERT INTO commercial_order_attachment (commercial_order_id, file_name, file_path, file_size)
VALUES (?, ?, ?, ?)
`

type CreateCommercialOrderAttachmentParams struct {
	CommercialOrderID int32  `json:"commercial_order_id"`
	FileName          string `json:"file_name"`
	FilePath          string `json:"file_path"`
	FileSize          int32  `json:"file_size"`
}

// ── Commercial Attachments ────────────────────────────────────────────────────
func (q *Queries) CreateCommercialOrderAttachment(ctx context.Context, arg CreateCommercialOrderAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialOrderAttachment,
		arg.CommercialOrderID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
	)
}

const createCommercialOrderItem = `-- name: CreateCommercialOrderItem :execresult

INSERT INTO commercial_order_items (commercial_order_id, name, item_code, quantity)
VALUES (?, ?, ?, ?)
`

type CreateCommercialOrderItemParams struct {
	CommercialOrderID int32  `json:"commercial_order_id"`
	Name              string `json:"name"`
	ItemCode          string `json:"item_code"`
	Quantity          int32  `json:"quantity"`
}

// ── Commercial Items ──────────────────────────────────────────────────────────
func (q *Queries) CreateCommercialOrderItem(ctx context.Context, arg CreateCommercialOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialOrderItem,
		arg.CommercialOrderID,
		arg.Name,
		arg.ItemCode,
		arg.Quantity,
	)
}

const createCommercialOrderPriority = `-- name: CreateCommercialOrderPriority :execresult
INSERT INTO commercial_order_priorities (name, background_color, border_color, text_color, sort_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateCommercialOrderPriorityParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
}

func (q *Queries) CreateCommercialOrderPriority(ctx context.Context, arg CreateCommercialOrderPriorityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
	)
}

const createCommercialOrderReason = `-- name: CreateCommercialOrderReason :execresult
INSERT INTO commercial_order_reason (name, initial_status_id) VALUES (?, ?)
`

type CreateCommercialOrderReasonParams struct {
	Name            string `json:"name"`
	InitialStatusID int32  `json:"initial_status_id"`
}

func (q *Queries) CreateCommercialOrderReason(ctx context.Context, arg CreateCommercialOrderReasonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialOrderReason, arg.Name, arg.InitialStatusID)
}

const createCommercialOrderStatus = `-- name: CreateCommercialOrderStatus :execresult
INSERT INTO commercial_order_status (name, background_color, border_color, text_color,
    sort_index, is_closed, is_pending_approval)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCommercialOrderStatusParams struct {
	Name              string `json:"name"`
	BackgroundColor   string `json:"background_color"`
	BorderColor       string `json:"border_color"`
	TextColor         string `json:"text_color"`
	SortIndex         int32  `json:"sort_index"`
	IsClosed          bool   `json:"is_closed"`
	IsPendingApproval bool   `json:"is_pending_approval"`
}

func (q *Queries) CreateCommercialOrderStatus(ctx context.Context, arg CreateCommercialOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsPendingApproval,
	)
}

const createCommercialStatusTransition = `-- name: CreateCommercialStatusTransition :execresult
INSERT INTO commercial_order_status_transition (from_status_id, to_status_id, access_level_id)
VALUES (?, ?, ?)
`

type CreateCommercialStatusTransitionParams struct {
	FromStatusID  sql.NullInt32 `json:"from_status_id"`
	ToStatusID    int32         `json:"to_status_id"`
	AccessLevelID int32         `json:"access_level_id"`
}

func (q *Queries) CreateCommercialStatusTransition(ctx context.Context, arg CreateCommercialStatusTransitionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommercialStatusTransition, arg.FromStatusID, arg.ToStatusID, arg.AccessLevelID)
}

const deleteCommercialConfigAssignableAccessLevels = `-- name: DeleteCommercialConfigAssignableAccessLevels :exec
DELETE FROM commercial_config_assignable_access_level WHERE commercial_config_id=?
`

func (q *Queries) DeleteCommercialConfigAssignableAccessLevels(ctx context.Context, commercialConfigID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialConfigAssignableAccessLevels, commercialConfigID)
	return err
}

const deleteCommercialOrder = `-- name: DeleteCommercialOrder :exec
UPDATE commercial_order SET deleted_at=NOW()
WHERE commercial_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteCommercialOrder(ctx context.Context, commercialOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialOrder, commercialOrderID)
	return err
}

const deleteCommercialOrderAttachment = `-- name: DeleteCommercialOrderAttachment :exec
UPDATE commercial_order_attachment SET deleted_at=NOW()
WHERE commercial_order_attachment_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteCommercialOrderAttachment(ctx context.Context, commercialOrderAttachmentID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialOrderAttachment, commercialOrderAttachmentID)
	return err
}

const deleteCommercialOrderItems = `-- name: DeleteCommercialOrderItems :exec
UPDATE commercial_order_items SET deleted_at=NOW()
WHERE commercial_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteCommercialOrderItems(ctx context.Context, commercialOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialOrderItems, commercialOrderID)
	return err
}

const deleteCommercialOrderPriority = `-- name: DeleteCommercialOrderPriority :exec
DELETE FROM commercial_order_priorities WHERE commercial_order_priority_id=?
`

func (q *Queries) DeleteCommercialOrderPriority(ctx context.Context, commercialOrderPriorityID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialOrderPriority, commercialOrderPriorityID)
	return err
}

const deleteCommercialOrderReason = `-- name: DeleteCommercialOrderReason :exec
UPDATE commercial_order_reason SET deleted_at=NOW()
WHERE commercial_order_reason_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteCommercialOrderReason(ctx context.Context, commercialOrderReasonID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialOrderReason, commercialOrderReasonID)
	return err
}

const deleteCommercialOrderStatus = `-- name: DeleteCommercialOrderStatus :exec
DELETE FROM commercial_order_status WHERE commercial_order_status_id=?
`

func (q *Queries) DeleteCommercialOrderStatus(ctx context.Context, commercialOrderStatusID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialOrderStatus, commercialOrderStatusID)
	return err
}

const deleteCommercialStatusTransition = `-- name: DeleteCommercialStatusTransition :exec
DELETE FROM commercial_order_status_transition WHERE id=?
`

func (q *Queries) DeleteCommercialStatusTransition(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommercialStatusTransition, id)
	return err
}

const getCommercialConfigAssignableAccessLevels = `-- name: GetCommercialConfigAssignableAccessLevels :many
SELECT a.access_level_id, a.name
FROM commercial_config_assignable_access_level ca
JOIN access_level a ON a.access_level_id = ca.access_level_id
WHERE ca.commercial_config_id = ?
`

func (q *Queries) GetCommercialConfigAssignableAccessLevels(ctx context.Context, commercialConfigID int32) ([]AccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, getCommercialConfigAssignableAccessLevels, commercialConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(&i.AccessLevelID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommercialOrderAttachmentByID = `-- name: GetCommercialOrderAttachmentByID :one
SELECT commercial_order_attachment_id, commercial_order_id, file_name, file_path, file_size, created_at
FROM commercial_order_attachment
WHERE commercial_order_attachment_id=? AND deleted_at IS NULL
`

type GetCommercialOrderAttachmentByIDRow struct {
	CommercialOrderAttachmentID int32     `json:"commercial_order_attachment_id"`
	CommercialOrderID           int32     `json:"commercial_order_id"`
	FileName                    string    `json:"file_name"`
	FilePath                    string    `json:"file_path"`
	FileSize                    int32     `json:"file_size"`
	CreatedAt                   time.Time `json:"created_at"`
}

func (q *Queries) GetCommercialOrderAttachmentByID(ctx context.Context, commercialOrderAttachmentID int32) (GetCommercialOrderAttachmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommercialOrderAttachmentByID, commercialOrderAttachmentID)
	var i GetCommercialOrderAttachmentByIDRow
	err := row.Scan(
		&i.CommercialOrderAttachmentID,
		&i.CommercialOrderID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getCommercialOrderByID = `-- name: GetCommercialOrderByID :one
SELECT o.commercial_order_id, o.requester_id, o.requester_name, o.assigned_to_id, o.assigned_to_name,
       o.salesperson_name, o.client_code, o.client_name, o.client_alias_name,
       o.status_id, o.priority_id, o.reason_id, o.description,
       o.captured_at, o.resolution, o.closed_at, o.created_at, o.updated_at,
       s.name AS status_name, s.background_color AS status_bg, s.border_color AS status_border,
       s.text_color AS status_text, s.is_closed AS status_is_closed,
       p.name AS priority_name, p.background_color AS priority_bg,
       r.name AS reason_name
FROM commercial_order o
JOIN commercial_order_status s     ON s.commercial_order_status_id   = o.status_id
JOIN commercial_order_priorities p ON p.commercial_order_priority_id = o.priority_id
JOIN commercial_order_reason r     ON r.commercial_order_reason_id   = o.reason_id
WHERE o.commercial_order_id=? AND o.deleted_at IS NULL
`

type GetCommercialOrderByIDRow struct {
	CommercialOrderID int32          `json:"commercial_order_id"`
	RequesterID       int32          `json:"requester_id"`
	RequesterName     string         `json:"requester_name"`
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	SalespersonName   sql.NullString `json:"salesperson_name"`
	ClientCode        string         `json:"client_code"`
	ClientName        string         `json:"client_name"`
	ClientAliasName   string         `json:"client_alias_name"`
	StatusID          int32          `json:"status_id"`
	PriorityID        int32          `json:"priority_id"`
	ReasonID          int32          `json:"reason_id"`
	Description       string         `json:"description"`
	CapturedAt        sql.NullTime   `json:"captured_at"`
	Resolution        sql.NullString `json:"resolution"`
	ClosedAt          sql.NullTime   `json:"closed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	StatusName        string         `json:"status_name"`
	StatusBg          string         `json:"status_bg"`
	StatusBorder      string         `json:"status_border"`
	StatusText        string         `json:"status_text"`
	StatusIsClosed    bool           `json:"status_is_closed"`
	PriorityName      string         `json:"priority_name"`
	PriorityBg        string         `json:"priority_bg"`
	ReasonName        string         `json:"reason_name"`
}

func (q *Queries) GetCommercialOrderByID(ctx context.Context, commercialOrderID int32) (GetCommercialOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommercialOrderByID, commercialOrderID)
	var i GetCommercialOrderByIDRow
	err := row.Scan(
		&i.CommercialOrderID,
		&i.RequesterID,
		&i.RequesterName,
		&i.AssignedToID,
		&i.AssignedToName,
		&i.SalespersonName,
		&i.ClientCode,
		&i.ClientName,
		&i.ClientAliasName,
		&i.StatusID,
		&i.PriorityID,
		&i.ReasonID,
		&i.Description,
		&i.CapturedAt,
		&i.Resolution,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusName,
		&i.StatusBg,
		&i.StatusBorder,
		&i.StatusText,
		&i.StatusIsClosed,
		&i.PriorityName,
		&i.PriorityBg,
		&i.ReasonName,
	)
	return i, err
}

const getCommercialOrderPriorityByID = `-- name: GetCommercialOrderPriorityByID :one
SELECT commercial_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM commercial_order_priorities
WHERE commercial_order_priority_id=?
`

func (q *Queries) GetCommercialOrderPriorityByID(ctx context.Context, commercialOrderPriorityID int32) (CommercialOrderPriority, error) {
	row := q.db.QueryRowContext(ctx, getCommercialOrderPriorityByID, commercialOrderPriorityID)
	var i CommercialOrderPriority
	err := row.Scan(
		&i.CommercialOrderPriorityID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
	)
	return i, err
}

const getCommercialOrderReasonByID = `-- name: GetCommercialOrderReasonByID :one
SELECT r.commercial_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM commercial_order_reason r
JOIN commercial_order_status s ON s.commercial_order_status_id = r.initial_status_id
WHERE r.commercial_order_reason_id=? AND r.deleted_at IS NULL
`

type GetCommercialOrderReasonByIDRow struct {
	CommercialOrderReasonID int32  `json:"commercial_order_reason_id"`
	Name                    string `json:"name"`
	InitialStatusID         int32  `json:"initial_status_id"`
	InitialStatusName       string `json:"initial_status_name"`
}

func (q *Queries) GetCommercialOrderReasonByID(ctx context.Context, commercialOrderReasonID int32) (GetCommercialOrderReasonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommercialOrderReasonByID, commercialOrderReasonID)
	var i GetCommercialOrderReasonByIDRow
	err := row.Scan(
		&i.CommercialOrderReasonID,
		&i.Name,
		&i.InitialStatusID,
		&i.InitialStatusName,
	)
	return i, err
}

const getCommercialOrderStatusByID = `-- name: GetCommercialOrderStatusByID :one
SELECT commercial_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_pending_approval
FROM commercial_order_status
WHERE commercial_order_status_id=?
`

func (q *Queries) GetCommercialOrderStatusByID(ctx context.Context, commercialOrderStatusID int32) (CommercialOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getCommercialOrderStatusByID, commercialOrderStatusID)
	var i CommercialOrderStatus
	err := row.Scan(
		&i.CommercialOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsPendingApproval,
	)
	return i, err
}

const getOrCreateCommercialConfig = `-- name: GetOrCreateCommercialConfig :one

SELECT commercial_config_id FROM commercial_config LIMIT 1
`

// ── Commercial Config ─────────────────────────────────────────────────────────
func (q *Queries) GetOrCreateCommercialConfig(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateCommercialConfig)
	var commercial_config_id int32
	err := row.Scan(&commercial_config_id)
	return commercial_config_id, err
}

const insertCommercialConfig = `-- name: InsertCommercialConfig :execresult
INSERT INTO commercial_config () VALUES ()
`

func (q *Queries) InsertCommercialConfig(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCommercialConfig)
}

const insertCommercialConfigAssignableAccessLevel = `-- name: InsertCommercialConfigAssignableAccessLevel :exec
INSERT INTO commercial_config_assignable_access_level (commercial_config_id, access_level_id)
VALUES (?, ?)
`

type InsertCommercialConfigAssignableAccessLevelParams struct {
	CommercialConfigID int32 `json:"commercial_config_id"`
	AccessLevelID      int32 `json:"access_level_id"`
}

func (q *Queries) InsertCommercialConfigAssignableAccessLevel(ctx context.Context, arg InsertCommercialConfigAssignableAccessLevelParams) error {
	_, err := q.db.ExecContext(ctx, insertCommercialConfigAssignableAccessLevel, arg.CommercialConfigID, arg.AccessLevelID)
	return err
}

const listCommercialOrderAttachments = `-- name: ListCommercialOrderAttachments :many
SELECT commercial_order_attachment_id, commercial_order_id, file_name, file_path, file_size, created_at
FROM commercial_order_attachment
WHERE commercial_order_id=? AND deleted_at IS NULL
ORDER BY created_at
`

type ListCommercialOrderAttachmentsRow struct {
	CommercialOrderAttachmentID int32     `json:"commercial_order_attachment_id"`
	CommercialOrderID           int32     `json:"commercial_order_id"`
	FileName                    string    `json:"file_name"`
	FilePath                    string    `json:"file_path"`
	FileSize                    int32     `json:"file_size"`
	CreatedAt                   time.Time `json:"created_at"`
}

func (q *Queries) ListCommercialOrderAttachments(ctx context.Context, commercialOrderID int32) ([]ListCommercialOrderAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommercialOrderAttachments, commercialOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommercialOrderAttachmentsRow
	for rows.Next() {
		var i ListCommercialOrderAttachmentsRow
		if err := rows.Scan(
			&i.CommercialOrderAttachmentID,
			&i.CommercialOrderID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommercialOrderItems = `-- name: ListCommercialOrderItems :many
SELECT commercial_order_item_id, commercial_order_id, name, item_code, quantity
FROM commercial_order_items
WHERE commercial_order_id=? AND deleted_at IS NULL
`

type ListCommercialOrderItemsRow struct {
	CommercialOrderItemID int32  `json:"commercial_order_item_id"`
	CommercialOrderID     int32  `json:"commercial_order_id"`
	Name                  string `json:"name"`
	ItemCode              string `json:"item_code"`
	Quantity              int32  `json:"quantity"`
}

func (q *Queries) ListCommercialOrderItems(ctx context.Context, commercialOrderID int32) ([]ListCommercialOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommercialOrderItems, commercialOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommercialOrderItemsRow
	for rows.Next() {
		var i ListCommercialOrderItemsRow
		if err := rows.Scan(
			&i.CommercialOrderItemID,
			&i.CommercialOrderID,
			&i.Name,
			&i.ItemCode,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommercialOrderPriorities = `-- name: ListCommercialOrderPriorities :many

SELECT commercial_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM commercial_order_priorities
ORDER BY sort_index
`

// ── Commercial Priority ───────────────────────────────────────────────────────
func (q *Queries) ListCommercialOrderPriorities(ctx context.Context) ([]CommercialOrderPriority, error) {
	rows, err := q.db.QueryContext(ctx, listCommercialOrderPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommercialOrderPriority
	for rows.Next() {
		var i CommercialOrderPriority
		if err := rows.Scan(
			&i.CommercialOrderPriorityID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommercialOrderReasons = `-- name: ListCommercialOrderReasons :many

SELECT r.commercial_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM commercial_order_reason r
JOIN commercial_order_status s ON s.commercial_order_status_id = r.initial_status_id
WHERE r.deleted_at IS NULL
ORDER BY r.name
`

type ListCommercialOrderReasonsRow struct {
	CommercialOrderReasonID int32  `json:"commercial_order_reason_id"`
	Name                    string `json:"name"`
	InitialStatusID         int32  `json:"initial_status_id"`
	InitialStatusName       string `json:"initial_status_name"`
}

// ── Commercial Reason ─────────────────────────────────────────────────────────
func (q *Queries) ListCommercialOrderReasons(ctx context.Context) ([]ListCommercialOrderReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommercialOrderReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommercialOrderReasonsRow
	for rows.Next() {
		var i ListCommercialOrderReasonsRow
		if err := rows.Scan(
			&i.CommercialOrderReasonID,
			&i.Name,
			&i.InitialStatusID,
			&i.InitialStatusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommercialOrderStatuses = `-- name: ListCommercialOrderStatuses :many

SELECT commercial_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_pending_approval
FROM commercial_order_status
ORDER BY sort_index
`

// ── Commercial Status ─────────────────────────────────────────────────────────
func (q *Queries) ListCommercialOrderStatuses(ctx context.Context) ([]CommercialOrderStatus, error) {
	rows, err := q.db.QueryContext(ctx, listCommercialOrderStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommercialOrderStatus
	for rows.Next() {
		var i CommercialOrderStatus
		if err := rows.Scan(
			&i.CommercialOrderStatusID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
			&i.IsClosed,
			&i.IsPendingApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommercialStatusTransitions = `-- name: ListCommercialStatusTransitions :many

SELECT id, from_status_id, to_status_id, access_level_id
FROM commercial_order_status_transition
`

// ── Commercial Status Transitions ─────────────────────────────────────────────
func (q *Queries) ListCommercialStatusTransitions(ctx context.Context) ([]CommercialOrderStatusTransition, error) {
	rows, err := q.db.QueryContext(ctx, listCommercialStatusTransitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommercialOrderStatusTransition
	for rows.Next() {
		var i CommercialOrderStatusTransition
		if err := rows.Scan(
			&i.ID,
			&i.FromStatusID,
			&i.ToStatusID,
			&i.AccessLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommercialOrder = `-- name: UpdateCommercialOrder :exec
UPDATE commercial_order
SET assigned_to_id=?, assigned_to_name=?, salesperson_name=?,
    client_code=?, client_name=?, client_alias_name=?,
    status_id=?, priority_id=?, reason_id=?, description=?,
    captured_at=?, resolution=?, closed_at=?
WHERE commercial_order_id=? AND deleted_at IS NULL
`

type UpdateCommercialOrderParams struct {
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	SalespersonName   sql.NullString `json:"salesperson_name"`
	ClientCode        string         `json:"client_code"`
	ClientName        string         `json:"client_name"`
	ClientAliasName   string         `json:"client_alias_name"`
	StatusID          int32          `json:"status_id"`
	PriorityID        int32          `json:"priority_id"`
	ReasonID          int32          `json:"reason_id"`
	Description       string         `json:"description"`
	CapturedAt        sql.NullTime   `json:"captured_at"`
	Resolution        sql.NullString `json:"resolution"`
	ClosedAt          sql.NullTime   `json:"closed_at"`
	CommercialOrderID int32          `json:"commercial_order_id"`
}

func (q *Queries) UpdateCommercialOrder(ctx context.Context, arg UpdateCommercialOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCommercialOrder,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
		arg.CapturedAt,
		arg.Resolution,
		arg.ClosedAt,
		arg.CommercialOrderID,
	)
	return err
}

const updateCommercialOrderPriority = `-- name: UpdateCommercialOrderPriority :exec
UPDATE commercial_order_priorities
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?
WHERE commercial_order_priority_id=?
`

type UpdateCommercialOrderPriorityParams struct {
	Name                      string `json:"name"`
	BackgroundColor           string `json:"background_color"`
	BorderColor               string `json:"border_color"`
	TextColor                 string `json:"text_color"`
	SortIndex                 int32  `json:"sort_index"`
	CommercialOrderPriorityID int32  `json:"commercial_order_priority_id"`
}

func (q *Queries) UpdateCommercialOrderPriority(ctx context.Context, arg UpdateCommercialOrderPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateCommercialOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.CommercialOrderPriorityID,
	)
	return err
}

const updateCommercialOrderReason = `-- name: UpdateCommercialOrderReason :exec
UPDATE commercial_order_reason SET name=?, initial_status_id=?
WHERE commercial_order_reason_id=? AND deleted_at IS NULL
`

type UpdateCommercialOrderReasonParams struct {
	Name                    string `json:"name"`
	InitialStatusID         int32  `json:"initial_status_id"`
	CommercialOrderReasonID int32  `json:"commercial_order_reason_id"`
}

func (q *Queries) UpdateCommercialOrderReason(ctx context.Context, arg UpdateCommercialOrderReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateCommercialOrderReason, arg.Name, arg.InitialStatusID, arg.CommercialOrderReasonID)
	return err
}

const updateCommercialOrderStatus = `-- name: UpdateCommercialOrderStatus :exec
UPDATE commercial_order SET status_id=?, captured_at=?, closed_at=?
WHERE commercial_order_id=? AND deleted_at IS NULL
`

type UpdateCommercialOrderStatusParams struct {
	StatusID          int32        `json:"status_id"`
	CapturedAt        sql.NullTime `json:"captured_at"`
	ClosedAt          sql.NullTime `json:"closed_at"`
	CommercialOrderID int32        `json:"commercial_order_id"`
}

func (q *Queries) UpdateCommercialOrderStatus(ctx context.Context, arg UpdateCommercialOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCommercialOrderStatus,
		arg.StatusID,
		arg.CapturedAt,
		arg.ClosedAt,
		arg.CommercialOrderID,
	)
	return err
}

const updateCommercialStatusRecord = `-- name: UpdateCommercialStatusRecord :exec
UPDATE commercial_order_status
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?,
    is_closed=?, is_pending_approval=?
WHERE commercial_order_status_id=?
`

type UpdateCommercialStatusRecordParams struct {
	Name                    string `json:"name"`
	BackgroundColor         string `json:"background_color"`
	BorderColor             string `json:"border_color"`
	TextColor               string `json:"text_color"`
	SortIndex               int32  `json:"sort_index"`
	IsClosed                bool   `json:"is_closed"`
	IsPendingApproval       bool   `json:"is_pending_approval"`
	CommercialOrderStatusID int32  `json:"commercial_order_status_id"`
}

func (q *Queries) UpdateCommercialStatusRecord(ctx context.Context, arg UpdateCommercialStatusRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateCommercialStatusRecord,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsPendingApproval,
		arg.CommercialOrderStatusID,
	)
	return err
}
