// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fiscal.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignFiscalOrder = `-- name: AssignFiscalOrder :exec
UPDATE fiscal_order SET assigned_to_id=?, assigned_to_name=?
WHERE fiscal_order_id=? AND deleted_at IS NULL
`

type AssignFiscalOrderParams struct {
	AssignedToID   sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName sql.NullString `json:"assigned_to_name"`
	FiscalOrderID  int32          `json:"fiscal_order_id"`
}

func (q *Queries) AssignFiscalOrder(ctx context.Context, arg AssignFiscalOrderParams) error {
	_, err := q.db.ExecContext(ctx, assignFiscalOrder, arg.AssignedToID, arg.AssignedToName, arg.FiscalOrderID)
	return err
}

const createFiscalOrder = `-- name: CreateFiscalOrder :execresult

INSERT INTO fiscal_order (requester_id, requester_name, assigned_to_id, assigned_to_name,
    salesperson_name, client_code, client_name, client_alias_name,
    status_id, priority_id, reason_id, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFiscalOrderParams struct {
	RequesterID     int32          `json:"requester_id"`
	RequesterName   string         `json:"requester_name"`
	AssignedToID    sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName  sql.NullString `json:"assigned_to_name"`
	SalespersonName sql.NullString `json:"salesperson_name"`
	ClientCode      string         `json:"client_code"`
	ClientName      string         `json:"client_name"`
	ClientAliasName string         `json:"client_alias_name"`
	StatusID        int32          `json:"status_id"`
	PriorityID      int32          `json:"priority_id"`
	ReasonID        int32          `json:"reason_id"`
	Description     string         `json:"description"`
}

// ── Fiscal Orders ─────────────────────────────────────────────────────────────
func (q *Queries) CreateFiscalOrder(ctx context.Context, arg CreateFiscalOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFiscalOrder,
		arg.RequesterID,
		arg.RequesterName,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
	)
}

const createFiscalOrderAttachment = `-- name: CreateFiscalOrderAttachment :execresult

INSERT INTO fiscal_order_attachment (fiscal_order_id, file_name, file_path, file_size)
VALUES (?, ?, ?, ?)
`

type CreateFiscalOrderAttachmentParams struct {
	FiscalOrderID int32  `json:"fiscal_order_id"`
	FileName      string `json:"file_name"`
	FilePath      string `json:"file_path"`
	FileSize      int32  `json:"file_size"`
}

// ── Fiscal Attachments ────────────────────────────────────────────────────────
func (q *Queries) CreateFiscalOrderAttachment(ctx context.Context, arg CreateFiscalOrderAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFiscalOrderAttachment,
		arg.FiscalOrderID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
	)
}

const createFiscalOrderPriority = `-- name: CreateFiscalOrderPriority :execresult
INSERT INTO fiscal_order_priorities (name, background_color, border_color, text_color, sort_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateFiscalOrderPriorityParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
}

func (q *Queries) CreateFiscalOrderPriority(ctx context.Context, arg CreateFiscalOrderPriorityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFiscalOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
	)
}

const createFiscalOrderReason = `-- name: CreateFiscalOrderReason :execresult
INSERT INTO fiscal_order_reason (name, initial_status_id) VALUES (?, ?)
`

type CreateFiscalOrderReasonParams struct {
	Name            string `json:"name"`
	InitialStatusID int32  `json:"initial_status_id"`
}

func (q *Queries) CreateFiscalOrderReason(ctx context.Context, arg CreateFiscalOrderReasonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFiscalOrderReason, arg.Name, arg.InitialStatusID)
}

const createFiscalOrderStatus = `-- name: CreateFiscalOrderStatus :execresult
INSERT INTO fiscal_order_status (name, background_color, border_color, text_color, sort_index,
    is_closed, is_default, is_pending_approval)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFiscalOrderStatusParams struct {
	Name              string `json:"name"`
	BackgroundColor   string `json:"background_color"`
	BorderColor       string `json:"border_color"`
	TextColor         string `json:"text_color"`
	SortIndex         int32  `json:"sort_index"`
	IsClosed          bool   `json:"is_closed"`
	IsDefault         bool   `json:"is_default"`
	IsPendingApproval bool   `json:"is_pending_approval"`
}

func (q *Queries) CreateFiscalOrderStatus(ctx context.Context, arg CreateFiscalOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFiscalOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.IsPendingApproval,
	)
}

const createFiscalStatusTransition = `-- name: CreateFiscalStatusTransition :execresult
INSERT INTO fiscal_order_status_transition (from_status_id, to_status_id, access_level_id)
VALUES (?, ?, ?)
`

type CreateFiscalStatusTransitionParams struct {
	FromStatusID  sql.NullInt32 `json:"from_status_id"`
	ToStatusID    int32         `json:"to_status_id"`
	AccessLevelID int32         `json:"access_level_id"`
}

func (q *Queries) CreateFiscalStatusTransition(ctx context.Context, arg CreateFiscalStatusTransitionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFiscalStatusTransition, arg.FromStatusID, arg.ToStatusID, arg.AccessLevelID)
}

const deleteFiscalOrder = `-- name: DeleteFiscalOrder :exec
UPDATE fiscal_order SET deleted_at=NOW()
WHERE fiscal_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteFiscalOrder(ctx context.Context, fiscalOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteFiscalOrder, fiscalOrderID)
	return err
}

const deleteFiscalOrderAttachment = `-- name: DeleteFiscalOrderAttachment :exec
UPDATE fiscal_order_attachment SET deleted_at=NOW()
WHERE fiscal_order_attachment_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteFiscalOrderAttachment(ctx context.Context, fiscalOrderAttachmentID int32) error {
	_, err := q.db.ExecContext(ctx, deleteFiscalOrderAttachment, fiscalOrderAttachmentID)
	return err
}

const deleteFiscalOrderPriority = `-- name: DeleteFiscalOrderPriority :exec
DELETE FROM fiscal_order_priorities WHERE fiscal_order_priority_id=?
`

func (q *Queries) DeleteFiscalOrderPriority(ctx context.Context, fiscalOrderPriorityID int32) error {
	_, err := q.db.ExecContext(ctx, deleteFiscalOrderPriority, fiscalOrderPriorityID)
	return err
}

const deleteFiscalOrderReason = `-- name: DeleteFiscalOrderReason :exec
UPDATE fiscal_order_reason SET deleted_at=NOW()
WHERE fiscal_order_reason_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteFiscalOrderReason(ctx context.Context, fiscalOrderReasonID int32) error {
	_, err := q.db.ExecContext(ctx, deleteFiscalOrderReason, fiscalOrderReasonID)
	return err
}

const deleteFiscalOrderStatus = `-- name: DeleteFiscalOrderStatus :exec
DELETE FROM fiscal_order_status WHERE fiscal_order_status_id=?
`

func (q *Queries) DeleteFiscalOrderStatus(ctx context.Context, fiscalOrderStatusID int32) error {
	_, err := q.db.ExecContext(ctx, deleteFiscalOrderStatus, fiscalOrderStatusID)
	return err
}

const deleteFiscalStatusTransition = `-- name: DeleteFiscalStatusTransition :exec
DELETE FROM fiscal_order_status_transition WHERE id=?
`

func (q *Queries) DeleteFiscalStatusTransition(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFiscalStatusTransition, id)
	return err
}

const getFiscalOrderAttachmentByID = `-- name: GetFiscalOrderAttachmentByID :one
SELECT fiscal_order_attachment_id, fiscal_order_id, file_name, file_path, file_size, created_at
FROM fiscal_order_attachment
WHERE fiscal_order_attachment_id=? AND deleted_at IS NULL
`

type GetFiscalOrderAttachmentByIDRow struct {
	FiscalOrderAttachmentID int32     `json:"fiscal_order_attachment_id"`
	FiscalOrderID           int32     `json:"fiscal_order_id"`
	FileName                string    `json:"file_name"`
	FilePath                string    `json:"file_path"`
	FileSize                int32     `json:"file_size"`
	CreatedAt               time.Time `json:"created_at"`
}

func (q *Queries) GetFiscalOrderAttachmentByID(ctx context.Context, fiscalOrderAttachmentID int32) (GetFiscalOrderAttachmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFiscalOrderAttachmentByID, fiscalOrderAttachmentID)
	var i GetFiscalOrderAttachmentByIDRow
	err := row.Scan(
		&i.FiscalOrderAttachmentID,
		&i.FiscalOrderID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getFiscalOrderByID = `-- name: GetFiscalOrderByID :one
SELECT o.fiscal_order_id, o.requester_id, o.requester_name, o.assigned_to_id, o.assigned_to_name,
       o.salesperson_name, o.client_code, o.client_name, o.client_alias_name,
       o.status_id, o.priority_id, o.reason_id, o.description,
       o.captured_at, o.resolution, o.closed_at, o.created_at, o.updated_at,
       s.name AS status_name, s.background_color AS status_bg, s.border_color AS status_border,
       s.text_color AS status_text, s.is_closed AS status_is_closed,
       p.name AS priority_name, p.background_color AS priority_bg,
       r.name AS reason_name
FROM fiscal_order o
JOIN fiscal_order_status s     ON s.fiscal_order_status_id   = o.status_id
JOIN fiscal_order_priorities p ON p.fiscal_order_priority_id = o.priority_id
JOIN fiscal_order_reason r     ON r.fiscal_order_reason_id   = o.reason_id
WHERE o.fiscal_order_id=? AND o.deleted_at IS NULL
`

type GetFiscalOrderByIDRow struct {
	FiscalOrderID   int32          `json:"fiscal_order_id"`
	RequesterID     int32          `json:"requester_id"`
	RequesterName   string         `json:"requester_name"`
	AssignedToID    sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName  sql.NullString `json:"assigned_to_name"`
	SalespersonName sql.NullString `json:"salesperson_name"`
	ClientCode      string         `json:"client_code"`
	ClientName      string         `json:"client_name"`
	ClientAliasName string         `json:"client_alias_name"`
	StatusID        int32          `json:"status_id"`
	PriorityID      int32          `json:"priority_id"`
	ReasonID        int32          `json:"reason_id"`
	Description     string         `json:"description"`
	CapturedAt      sql.NullTime   `json:"captured_at"`
	Resolution      sql.NullString `json:"resolution"`
	ClosedAt        sql.NullTime   `json:"closed_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	StatusName      string         `json:"status_name"`
	StatusBg        string         `json:"status_bg"`
	StatusBorder    string         `json:"status_border"`
	StatusText      string         `json:"status_text"`
	StatusIsClosed  bool           `json:"status_is_closed"`
	PriorityName    string         `json:"priority_name"`
	PriorityBg      string         `json:"priority_bg"`
	ReasonName      string         `json:"reason_name"`
}

func (q *Queries) GetFiscalOrderByID(ctx context.Context, fiscalOrderID int32) (GetFiscalOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFiscalOrderByID, fiscalOrderID)
	var i GetFiscalOrderByIDRow
	err := row.Scan(
		&i.FiscalOrderID,
		&i.RequesterID,
		&i.RequesterName,
		&i.AssignedToID,
		&i.AssignedToName,
		&i.SalespersonName,
		&i.ClientCode,
		&i.ClientName,
		&i.ClientAliasName,
		&i.StatusID,
		&i.PriorityID,
		&i.ReasonID,
		&i.Description,
		&i.CapturedAt,
		&i.Resolution,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusName,
		&i.StatusBg,
		&i.StatusBorder,
		&i.StatusText,
		&i.StatusIsClosed,
		&i.PriorityName,
		&i.PriorityBg,
		&i.ReasonName,
	)
	return i, err
}

const getFiscalOrderPriorityByID = `-- name: GetFiscalOrderPriorityByID :one
SELECT fiscal_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM fiscal_order_priorities
WHERE fiscal_order_priority_id=?
`

func (q *Queries) GetFiscalOrderPriorityByID(ctx context.Context, fiscalOrderPriorityID int32) (FiscalOrderPriority, error) {
	row := q.db.QueryRowContext(ctx, getFiscalOrderPriorityByID, fiscalOrderPriorityID)
	var i FiscalOrderPriority
	err := row.Scan(
		&i.FiscalOrderPriorityID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
	)
	return i, err
}

const getFiscalOrderReasonByID = `-- name: GetFiscalOrderReasonByID :one
SELECT r.fiscal_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM fiscal_order_reason r
JOIN fiscal_order_status s ON s.fiscal_order_status_id = r.initial_status_id
WHERE r.fiscal_order_reason_id=? AND r.deleted_at IS NULL
`

type GetFiscalOrderReasonByIDRow struct {
	FiscalOrderReasonID int32  `json:"fiscal_order_reason_id"`
	Name                string `json:"name"`
	InitialStatusID     int32  `json:"initial_status_id"`
	InitialStatusName   string `json:"initial_status_name"`
}

func (q *Queries) GetFiscalOrderReasonByID(ctx context.Context, fiscalOrderReasonID int32) (GetFiscalOrderReasonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFiscalOrderReasonByID, fiscalOrderReasonID)
	var i GetFiscalOrderReasonByIDRow
	err := row.Scan(
		&i.FiscalOrderReasonID,
		&i.Name,
		&i.InitialStatusID,
		&i.InitialStatusName,
	)
	return i, err
}

const getFiscalOrderStatusByID = `-- name: GetFiscalOrderStatusByID :one
SELECT fiscal_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_default, is_pending_approval
FROM fiscal_order_status
WHERE fiscal_order_status_id = ?
`

func (q *Queries) GetFiscalOrderStatusByID(ctx context.Context, fiscalOrderStatusID int32) (FiscalOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getFiscalOrderStatusByID, fiscalOrderStatusID)
	var i FiscalOrderStatus
	err := row.Scan(
		&i.FiscalOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsDefault,
		&i.IsPendingApproval,
	)
	return i, err
}

const listFiscalOrderAttachments = `-- name: ListFiscalOrderAttachments :many
SELECT fiscal_order_attachment_id, fiscal_order_id, file_name, file_path, file_size, created_at
FROM fiscal_order_attachment
WHERE fiscal_order_id=? AND deleted_at IS NULL
ORDER BY created_at
`

type ListFiscalOrderAttachmentsRow struct {
	FiscalOrderAttachmentID int32     `json:"fiscal_order_attachment_id"`
	FiscalOrderID           int32     `json:"fiscal_order_id"`
	FileName                string    `json:"file_name"`
	FilePath                string    `json:"file_path"`
	FileSize                int32     `json:"file_size"`
	CreatedAt               time.Time `json:"created_at"`
}

func (q *Queries) ListFiscalOrderAttachments(ctx context.Context, fiscalOrderID int32) ([]ListFiscalOrderAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFiscalOrderAttachments, fiscalOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFiscalOrderAttachmentsRow
	for rows.Next() {
		var i ListFiscalOrderAttachmentsRow
		if err := rows.Scan(
			&i.FiscalOrderAttachmentID,
			&i.FiscalOrderID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalOrderPriorities = `-- name: ListFiscalOrderPriorities :many

SELECT fiscal_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM fiscal_order_priorities
ORDER BY sort_index
`

// ── Fiscal Priority ───────────────────────────────────────────────────────────
func (q *Queries) ListFiscalOrderPriorities(ctx context.Context) ([]FiscalOrderPriority, error) {
	rows, err := q.db.QueryContext(ctx, listFiscalOrderPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalOrderPriority
	for rows.Next() {
		var i FiscalOrderPriority
		if err := rows.Scan(
			&i.FiscalOrderPriorityID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalOrderReasons = `-- name: ListFiscalOrderReasons :many

SELECT r.fiscal_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM fiscal_order_reason r
JOIN fiscal_order_status s ON s.fiscal_order_status_id = r.initial_status_id
WHERE r.deleted_at IS NULL
ORDER BY r.name
`

type ListFiscalOrderReasonsRow struct {
	FiscalOrderReasonID int32  `json:"fiscal_order_reason_id"`
	Name                string `json:"name"`
	InitialStatusID     int32  `json:"initial_status_id"`
	InitialStatusName   string `json:"initial_status_name"`
}

// ── Fiscal Reason ─────────────────────────────────────────────────────────────
func (q *Queries) ListFiscalOrderReasons(ctx context.Context) ([]ListFiscalOrderReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFiscalOrderReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFiscalOrderReasonsRow
	for rows.Next() {
		var i ListFiscalOrderReasonsRow
		if err := rows.Scan(
			&i.FiscalOrderReasonID,
			&i.Name,
			&i.InitialStatusID,
			&i.InitialStatusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalOrderStatuses = `-- name: ListFiscalOrderStatuses :many

SELECT fiscal_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_default, is_pending_approval
FROM fiscal_order_status
ORDER BY sort_index
`

// ── Fiscal Status ─────────────────────────────────────────────────────────────
func (q *Queries) ListFiscalOrderStatuses(ctx context.Context) ([]FiscalOrderStatus, error) {
	rows, err := q.db.QueryContext(ctx, listFiscalOrderStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalOrderStatus
	for rows.Next() {
		var i FiscalOrderStatus
		if err := rows.Scan(
			&i.FiscalOrderStatusID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
			&i.IsClosed,
			&i.IsDefault,
			&i.IsPendingApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalStatusTransitions = `-- name: ListFiscalStatusTransitions :many

SELECT id, from_status_id, to_status_id, access_level_id
FROM fiscal_order_status_transition
`

// ── Fiscal Status Transitions ─────────────────────────────────────────────────
func (q *Queries) ListFiscalStatusTransitions(ctx context.Context) ([]FiscalOrderStatusTransition, error) {
	rows, err := q.db.QueryContext(ctx, listFiscalStatusTransitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalOrderStatusTransition
	for rows.Next() {
		var i FiscalOrderStatusTransition
		if err := rows.Scan(
			&i.ID,
			&i.FromStatusID,
			&i.ToStatusID,
			&i.AccessLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFiscalOrder = `-- name: UpdateFiscalOrder :exec
UPDATE fiscal_order
SET assigned_to_id=?, assigned_to_name=?, salesperson_name=?,
    client_code=?, client_name=?, client_alias_name=?,
    status_id=?, priority_id=?, reason_id=?, description=?,
    captured_at=?, resolution=?, closed_at=?
WHERE fiscal_order_id=? AND deleted_at IS NULL
`

type UpdateFiscalOrderParams struct {
	AssignedToID    sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName  sql.NullString `json:"assigned_to_name"`
	SalespersonName sql.NullString `json:"salesperson_name"`
	ClientCode      string         `json:"client_code"`
	ClientName      string         `json:"client_name"`
	ClientAliasName string         `json:"client_alias_name"`
	StatusID        int32          `json:"status_id"`
	PriorityID      int32          `json:"priority_id"`
	ReasonID        int32          `json:"reason_id"`
	Description     string         `json:"description"`
	CapturedAt      sql.NullTime   `json:"captured_at"`
	Resolution      sql.NullString `json:"resolution"`
	ClosedAt        sql.NullTime   `json:"closed_at"`
	FiscalOrderID   int32          `json:"fiscal_order_id"`
}

func (q *Queries) UpdateFiscalOrder(ctx context.Context, arg UpdateFiscalOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateFiscalOrder,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
		arg.CapturedAt,
		arg.Resolution,
		arg.ClosedAt,
		arg.FiscalOrderID,
	)
	return err
}

const updateFiscalOrderPriority = `-- name: UpdateFiscalOrderPriority :exec
UPDATE fiscal_order_priorities
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?
WHERE fiscal_order_priority_id=?
`

type UpdateFiscalOrderPriorityParams struct {
	Name                  string `json:"name"`
	BackgroundColor       string `json:"background_color"`
	BorderColor           string `json:"border_color"`
	TextColor             string `json:"text_color"`
	SortIndex             int32  `json:"sort_index"`
	FiscalOrderPriorityID int32  `json:"fiscal_order_priority_id"`
}

func (q *Queries) UpdateFiscalOrderPriority(ctx context.Context, arg UpdateFiscalOrderPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateFiscalOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.FiscalOrderPriorityID,
	)
	return err
}

const updateFiscalOrderReason = `-- name: UpdateFiscalOrderReason :exec
UPDATE fiscal_order_reason SET name=?, initial_status_id=?
WHERE fiscal_order_reason_id=? AND deleted_at IS NULL
`

type UpdateFiscalOrderReasonParams struct {
	Name                string `json:"name"`
	InitialStatusID     int32  `json:"initial_status_id"`
	FiscalOrderReasonID int32  `json:"fiscal_order_reason_id"`
}

func (q *Queries) UpdateFiscalOrderReason(ctx context.Context, arg UpdateFiscalOrderReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateFiscalOrderReason, arg.Name, arg.InitialStatusID, arg.FiscalOrderReasonID)
	return err
}

const updateFiscalOrderStatus = `-- name: UpdateFiscalOrderStatus :exec
UPDATE fiscal_order SET status_id=?, captured_at=?, closed_at=?
WHERE fiscal_order_id=? AND deleted_at IS NULL
`

type UpdateFiscalOrderStatusParams struct {
	StatusID      int32        `json:"status_id"`
	CapturedAt    sql.NullTime `json:"captured_at"`
	ClosedAt      sql.NullTime `json:"closed_at"`
	FiscalOrderID int32        `json:"fiscal_order_id"`
}

func (q *Queries) UpdateFiscalOrderStatus(ctx context.Context, arg UpdateFiscalOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFiscalOrderStatus,
		arg.StatusID,
		arg.CapturedAt,
		arg.ClosedAt,
		arg.FiscalOrderID,
	)
	return err
}

const updateFiscalStatusRecord = `-- name: UpdateFiscalStatusRecord :exec
UPDATE fiscal_order_status
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?,
    is_closed=?, is_default=?, is_pending_approval=?
WHERE fiscal_order_status_id=?
`

type UpdateFiscalStatusRecordParams struct {
	Name                string `json:"name"`
	BackgroundColor     string `json:"background_color"`
	BorderColor         string `json:"border_color"`
	TextColor           string `json:"text_color"`
	SortIndex           int32  `json:"sort_index"`
	IsClosed            bool   `json:"is_closed"`
	IsDefault           bool   `json:"is_default"`
	IsPendingApproval   bool   `json:"is_pending_approval"`
	FiscalOrderStatusID int32  `json:"fiscal_order_status_id"`
}

func (q *Queries) UpdateFiscalStatusRecord(ctx context.Context, arg UpdateFiscalStatusRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateFiscalStatusRecord,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.IsPendingApproval,
		arg.FiscalOrderStatusID,
	)
	return err
}
