// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logistic.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignLogisticOrder = `-- name: AssignLogisticOrder :exec
UPDATE logistic_order SET assigned_to_id=?, assigned_to_name=?
WHERE logistic_order_id=? AND deleted_at IS NULL
`

type AssignLogisticOrderParams struct {
	AssignedToID    sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName  sql.NullString `json:"assigned_to_name"`
	LogisticOrderID int32          `json:"logistic_order_id"`
}

func (q *Queries) AssignLogisticOrder(ctx context.Context, arg AssignLogisticOrderParams) error {
	_, err := q.db.ExecContext(ctx, assignLogisticOrder, arg.AssignedToID, arg.AssignedToName, arg.LogisticOrderID)
	return err
}

const createLogisticOperator = `-- name: CreateLogisticOperator :execresult
INSERT INTO logistic_operator (name, type) VALUES (?, ?)
`

type CreateLogisticOperatorParams struct {
	Name string               `json:"name"`
	Type LogisticOperatorType `json:"type"`
}

func (q *Queries) CreateLogisticOperator(ctx context.Context, arg CreateLogisticOperatorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOperator, arg.Name, arg.Type)
}

const createLogisticOrder = `-- name: CreateLogisticOrder :execresult

INSERT INTO logistic_order (requester_id, requester_name, assigned_to_id, assigned_to_name,
    salesperson_name, client_code, client_name, client_alias_name,
    contact_type, contact_name, contact_phone, contact_mobile, contact_email,
    address_name, address_type, type_of_address, street, street_no, block,
    city, county, state, country, zip_code, building_floor_room,
    status_id, priority_id, reason_id, schedule_date, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLogisticOrderParams struct {
	RequesterID       int32          `json:"requester_id"`
	RequesterName     string         `json:"requester_name"`
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	SalespersonName   sql.NullString `json:"salesperson_name"`
	ClientCode        string         `json:"client_code"`
	ClientName        string         `json:"client_name"`
	ClientAliasName   string         `json:"client_alias_name"`
	ContactType       sql.NullString `json:"contact_type"`
	ContactName       sql.NullString `json:"contact_name"`
	ContactPhone      sql.NullString `json:"contact_phone"`
	ContactMobile     sql.NullString `json:"contact_mobile"`
	ContactEmail      sql.NullString `json:"contact_email"`
	AddressName       sql.NullString `json:"address_name"`
	AddressType       sql.NullString `json:"address_type"`
	TypeOfAddress     sql.NullString `json:"type_of_address"`
	Street            sql.NullString `json:"street"`
	StreetNo          sql.NullString `json:"street_no"`
	Block             sql.NullString `json:"block"`
	City              sql.NullString `json:"city"`
	County            sql.NullString `json:"county"`
	State             sql.NullString `json:"state"`
	Country           sql.NullString `json:"country"`
	ZipCode           sql.NullString `json:"zip_code"`
	BuildingFloorRoom sql.NullString `json:"building_floor_room"`
	StatusID          int32          `json:"status_id"`
	PriorityID        int32          `json:"priority_id"`
	ReasonID          int32          `json:"reason_id"`
	ScheduleDate      sql.NullTime   `json:"schedule_date"`
	Description       string         `json:"description"`
}

// ── Logistic Orders ───────────────────────────────────────────────────────────
func (q *Queries) CreateLogisticOrder(ctx context.Context, arg CreateLogisticOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOrder,
		arg.RequesterID,
		arg.RequesterName,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.ContactType,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactMobile,
		arg.ContactEmail,
		arg.AddressName,
		arg.AddressType,
		arg.TypeOfAddress,
		arg.Street,
		arg.StreetNo,
		arg.Block,
		arg.City,
		arg.County,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.BuildingFloorRoom,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.ScheduleDate,
		arg.Description,
	)
}

const createLogisticOrderAttachment = `-- name: CreateLogisticOrderAttachment :execresult

INSERT INTO logistic_order_attachment (logistic_order_id, file_name, file_path, file_size)
VALUES (?, ?, ?, ?)
`

type CreateLogisticOrderAttachmentParams struct {
	LogisticOrderID int32  `json:"logistic_order_id"`
	FileName        string `json:"file_name"`
	FilePath        string `json:"file_path"`
	FileSize        int32  `json:"file_size"`
}

// ── Logistic Attachments ──────────────────────────────────────────────────────
func (q *Queries) CreateLogisticOrderAttachment(ctx context.Context, arg CreateLogisticOrderAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOrderAttachment,
		arg.LogisticOrderID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
	)
}

const createLogisticOrderItem = `-- name: CreateLogisticOrderItem :execresult

INSERT INTO logistic_order_items (logistic_order_id, name, item_code, quantity)
VALUES (?, ?, ?, ?)
`

type CreateLogisticOrderItemParams struct {
	LogisticOrderID int32  `json:"logistic_order_id"`
	Name            string `json:"name"`
	ItemCode        string `json:"item_code"`
	Quantity        int32  `json:"quantity"`
}

// ── Logistic Items ────────────────────────────────────────────────────────────
func (q *Queries) CreateLogisticOrderItem(ctx context.Context, arg CreateLogisticOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOrderItem,
		arg.LogisticOrderID,
		arg.Name,
		arg.ItemCode,
		arg.Quantity,
	)
}

const createLogisticOrderPriority = `-- name: CreateLogisticOrderPriority :execresult
INSERT INTO logistic_order_priorities (name, background_color, border_color, text_color, sort_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateLogisticOrderPriorityParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
}

func (q *Queries) CreateLogisticOrderPriority(ctx context.Context, arg CreateLogisticOrderPriorityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
	)
}

const createLogisticOrderReason = `-- name: CreateLogisticOrderReason :execresult
INSERT INTO logistic_order_reason (name, initial_status_id) VALUES (?, ?)
`

type CreateLogisticOrderReasonParams struct {
	Name            string `json:"name"`
	InitialStatusID int32  `json:"initial_status_id"`
}

func (q *Queries) CreateLogisticOrderReason(ctx context.Context, arg CreateLogisticOrderReasonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOrderReason, arg.Name, arg.InitialStatusID)
}

const createLogisticOrderStatus = `-- name: CreateLogisticOrderStatus :execresult
INSERT INTO logistic_order_status (name, background_color, border_color, text_color,
    sort_index, is_closed, is_pending_approval, is_rh_step)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLogisticOrderStatusParams struct {
	Name              string `json:"name"`
	BackgroundColor   string `json:"background_color"`
	BorderColor       string `json:"border_color"`
	TextColor         string `json:"text_color"`
	SortIndex         int32  `json:"sort_index"`
	IsClosed          bool   `json:"is_closed"`
	IsPendingApproval bool   `json:"is_pending_approval"`
	IsRhStep          bool   `json:"is_rh_step"`
}

func (q *Queries) CreateLogisticOrderStatus(ctx context.Context, arg CreateLogisticOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsPendingApproval,
		arg.IsRhStep,
	)
}

const createLogisticStatusTransition = `-- name: CreateLogisticStatusTransition :execresult
INSERT INTO logistic_order_status_transition (from_status_id, to_status_id, access_level_id)
VALUES (?, ?, ?)
`

type CreateLogisticStatusTransitionParams struct {
	FromStatusID  sql.NullInt32 `json:"from_status_id"`
	ToStatusID    int32         `json:"to_status_id"`
	AccessLevelID int32         `json:"access_level_id"`
}

func (q *Queries) CreateLogisticStatusTransition(ctx context.Context, arg CreateLogisticStatusTransitionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLogisticStatusTransition, arg.FromStatusID, arg.ToStatusID, arg.AccessLevelID)
}

const deleteLogisticConfigAssignableAccessLevels = `-- name: DeleteLogisticConfigAssignableAccessLevels :exec
DELETE FROM logistic_config_assignable_access_level WHERE logistic_config_id=?
`

func (q *Queries) DeleteLogisticConfigAssignableAccessLevels(ctx context.Context, logisticConfigID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticConfigAssignableAccessLevels, logisticConfigID)
	return err
}

const deleteLogisticOperator = `-- name: DeleteLogisticOperator :exec
DELETE FROM logistic_operator WHERE logistic_operator_id=?
`

func (q *Queries) DeleteLogisticOperator(ctx context.Context, logisticOperatorID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOperator, logisticOperatorID)
	return err
}

const deleteLogisticOrder = `-- name: DeleteLogisticOrder :exec
UPDATE logistic_order SET deleted_at=NOW()
WHERE logistic_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteLogisticOrder(ctx context.Context, logisticOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOrder, logisticOrderID)
	return err
}

const deleteLogisticOrderAttachment = `-- name: DeleteLogisticOrderAttachment :exec
UPDATE logistic_order_attachment SET deleted_at=NOW()
WHERE logistic_order_attachment_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteLogisticOrderAttachment(ctx context.Context, logisticOrderAttachmentID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOrderAttachment, logisticOrderAttachmentID)
	return err
}

const deleteLogisticOrderItems = `-- name: DeleteLogisticOrderItems :exec
UPDATE logistic_order_items SET deleted_at=NOW()
WHERE logistic_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteLogisticOrderItems(ctx context.Context, logisticOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOrderItems, logisticOrderID)
	return err
}

const deleteLogisticOrderPriority = `-- name: DeleteLogisticOrderPriority :exec
DELETE FROM logistic_order_priorities WHERE logistic_order_priority_id=?
`

func (q *Queries) DeleteLogisticOrderPriority(ctx context.Context, logisticOrderPriorityID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOrderPriority, logisticOrderPriorityID)
	return err
}

const deleteLogisticOrderReason = `-- name: DeleteLogisticOrderReason :exec
UPDATE logistic_order_reason SET deleted_at=NOW()
WHERE logistic_order_reason_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteLogisticOrderReason(ctx context.Context, logisticOrderReasonID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOrderReason, logisticOrderReasonID)
	return err
}

const deleteLogisticOrderStatus = `-- name: DeleteLogisticOrderStatus :exec
DELETE FROM logistic_order_status WHERE logistic_order_status_id=?
`

func (q *Queries) DeleteLogisticOrderStatus(ctx context.Context, logisticOrderStatusID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticOrderStatus, logisticOrderStatusID)
	return err
}

const deleteLogisticStatusTransition = `-- name: DeleteLogisticStatusTransition :exec
DELETE FROM logistic_order_status_transition WHERE id=?
`

func (q *Queries) DeleteLogisticStatusTransition(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLogisticStatusTransition, id)
	return err
}

const getLogisticConfigAssignableAccessLevels = `-- name: GetLogisticConfigAssignableAccessLevels :many
SELECT a.access_level_id, a.name
FROM logistic_config_assignable_access_level ca
JOIN access_level a ON a.access_level_id = ca.access_level_id
WHERE ca.logistic_config_id=?
`

func (q *Queries) GetLogisticConfigAssignableAccessLevels(ctx context.Context, logisticConfigID int32) ([]AccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, getLogisticConfigAssignableAccessLevels, logisticConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(&i.AccessLevelID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogisticOperatorByID = `-- name: GetLogisticOperatorByID :one
SELECT logistic_operator_id, name, type FROM logistic_operator WHERE logistic_operator_id=?
`

func (q *Queries) GetLogisticOperatorByID(ctx context.Context, logisticOperatorID int32) (LogisticOperator, error) {
	row := q.db.QueryRowContext(ctx, getLogisticOperatorByID, logisticOperatorID)
	var i LogisticOperator
	err := row.Scan(&i.LogisticOperatorID, &i.Name, &i.Type)
	return i, err
}

const getLogisticOrderAttachmentByID = `-- name: GetLogisticOrderAttachmentByID :one
SELECT logistic_order_attachment_id, logistic_order_id, file_name, file_path, file_size, created_at
FROM logistic_order_attachment
WHERE logistic_order_attachment_id=? AND deleted_at IS NULL
`

type GetLogisticOrderAttachmentByIDRow struct {
	LogisticOrderAttachmentID int32     `json:"logistic_order_attachment_id"`
	LogisticOrderID           int32     `json:"logistic_order_id"`
	FileName                  string    `json:"file_name"`
	FilePath                  string    `json:"file_path"`
	FileSize                  int32     `json:"file_size"`
	CreatedAt                 time.Time `json:"created_at"`
}

func (q *Queries) GetLogisticOrderAttachmentByID(ctx context.Context, logisticOrderAttachmentID int32) (GetLogisticOrderAttachmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLogisticOrderAttachmentByID, logisticOrderAttachmentID)
	var i GetLogisticOrderAttachmentByIDRow
	err := row.Scan(
		&i.LogisticOrderAttachmentID,
		&i.LogisticOrderID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getLogisticOrderByID = `-- name: GetLogisticOrderByID :one
SELECT o.logistic_order_id, o.requester_id, o.requester_name, o.assigned_to_id, o.assigned_to_name,
       o.driver_name, o.checker_name, o.checker_signature, o.salesperson_name,
       o.client_code, o.client_name, o.client_alias_name,
       o.contact_type, o.contact_name, o.contact_phone, o.contact_mobile, o.contact_email,
       o.address_name, o.address_type, o.type_of_address, o.street, o.street_no, o.block,
       o.city, o.county, o.state, o.country, o.zip_code, o.building_floor_room,
       o.status_id, o.priority_id, o.reason_id, o.schedule_date, o.description,
       o.has_salary_discount, o.salary_discount_reason,
       o.captured_at, o.resolution, o.closed_at, o.created_at, o.updated_at,
       s.name AS status_name, s.background_color AS status_bg, s.border_color AS status_border,
       s.text_color AS status_text, s.is_closed AS status_is_closed, s.is_rh_step AS status_is_rh_step,
       p.name AS priority_name, p.background_color AS priority_bg,
       r.name AS reason_name
FROM logistic_order o
JOIN logistic_order_status s     ON s.logistic_order_status_id   = o.status_id
JOIN logistic_order_priorities p ON p.logistic_order_priority_id = o.priority_id
JOIN logistic_order_reason r     ON r.logistic_order_reason_id   = o.reason_id
WHERE o.logistic_order_id=? AND o.deleted_at IS NULL
`

type GetLogisticOrderByIDRow struct {
	LogisticOrderID      int32          `json:"logistic_order_id"`
	RequesterID          int32          `json:"requester_id"`
	RequesterName        string         `json:"requester_name"`
	AssignedToID         sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName       sql.NullString `json:"assigned_to_name"`
	DriverName           sql.NullString `json:"driver_name"`
	CheckerName          sql.NullString `json:"checker_name"`
	CheckerSignature     sql.NullString `json:"checker_signature"`
	SalespersonName      sql.NullString `json:"salesperson_name"`
	ClientCode           string         `json:"client_code"`
	ClientName           string         `json:"client_name"`
	ClientAliasName      string         `json:"client_alias_name"`
	ContactType          sql.NullString `json:"contact_type"`
	ContactName          sql.NullString `json:"contact_name"`
	ContactPhone         sql.NullString `json:"contact_phone"`
	ContactMobile        sql.NullString `json:"contact_mobile"`
	ContactEmail         sql.NullString `json:"contact_email"`
	AddressName          sql.NullString `json:"address_name"`
	AddressType          sql.NullString `json:"address_type"`
	TypeOfAddress        sql.NullString `json:"type_of_address"`
	Street               sql.NullString `json:"street"`
	StreetNo             sql.NullString `json:"street_no"`
	Block                sql.NullString `json:"block"`
	City                 sql.NullString `json:"city"`
	County               sql.NullString `json:"county"`
	State                sql.NullString `json:"state"`
	Country              sql.NullString `json:"country"`
	ZipCode              sql.NullString `json:"zip_code"`
	BuildingFloorRoom    sql.NullString `json:"building_floor_room"`
	StatusID             int32          `json:"status_id"`
	PriorityID           int32          `json:"priority_id"`
	ReasonID             int32          `json:"reason_id"`
	ScheduleDate         sql.NullTime   `json:"schedule_date"`
	Description          string         `json:"description"`
	HasSalaryDiscount    sql.NullBool   `json:"has_salary_discount"`
	SalaryDiscountReason sql.NullString `json:"salary_discount_reason"`
	CapturedAt           sql.NullTime   `json:"captured_at"`
	Resolution           sql.NullString `json:"resolution"`
	ClosedAt             sql.NullTime   `json:"closed_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	StatusName           string         `json:"status_name"`
	StatusBg             string         `json:"status_bg"`
	StatusBorder         string         `json:"status_border"`
	StatusText           string         `json:"status_text"`
	StatusIsClosed       bool           `json:"status_is_closed"`
	StatusIsRhStep       bool           `json:"status_is_rh_step"`
	PriorityName         string         `json:"priority_name"`
	PriorityBg           string         `json:"priority_bg"`
	ReasonName           string         `json:"reason_name"`
}

func (q *Queries) GetLogisticOrderByID(ctx context.Context, logisticOrderID int32) (GetLogisticOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLogisticOrderByID, logisticOrderID)
	var i GetLogisticOrderByIDRow
	err := row.Scan(
		&i.LogisticOrderID,
		&i.RequesterID,
		&i.RequesterName,
		&i.AssignedToID,
		&i.AssignedToName,
		&i.DriverName,
		&i.CheckerName,
		&i.CheckerSignature,
		&i.SalespersonName,
		&i.ClientCode,
		&i.ClientName,
		&i.ClientAliasName,
		&i.ContactType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactMobile,
		&i.ContactEmail,
		&i.AddressName,
		&i.AddressType,
		&i.TypeOfAddress,
		&i.Street,
		&i.StreetNo,
		&i.Block,
		&i.City,
		&i.County,
		&i.State,
		&i.Country,
		&i.ZipCode,
		&i.BuildingFloorRoom,
		&i.StatusID,
		&i.PriorityID,
		&i.ReasonID,
		&i.ScheduleDate,
		&i.Description,
		&i.HasSalaryDiscount,
		&i.SalaryDiscountReason,
		&i.CapturedAt,
		&i.Resolution,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusName,
		&i.StatusBg,
		&i.StatusBorder,
		&i.StatusText,
		&i.StatusIsClosed,
		&i.StatusIsRhStep,
		&i.PriorityName,
		&i.PriorityBg,
		&i.ReasonName,
	)
	return i, err
}

const getLogisticOrderPriorityByID = `-- name: GetLogisticOrderPriorityByID :one
SELECT logistic_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM logistic_order_priorities
WHERE logistic_order_priority_id=?
`

func (q *Queries) GetLogisticOrderPriorityByID(ctx context.Context, logisticOrderPriorityID int32) (LogisticOrderPriority, error) {
	row := q.db.QueryRowContext(ctx, getLogisticOrderPriorityByID, logisticOrderPriorityID)
	var i LogisticOrderPriority
	err := row.Scan(
		&i.LogisticOrderPriorityID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
	)
	return i, err
}

const getLogisticOrderReasonByID = `-- name: GetLogisticOrderReasonByID :one
SELECT r.logistic_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM logistic_order_reason r
JOIN logistic_order_status s ON s.logistic_order_status_id = r.initial_status_id
WHERE r.logistic_order_reason_id=? AND r.deleted_at IS NULL
`

type GetLogisticOrderReasonByIDRow struct {
	LogisticOrderReasonID int32  `json:"logistic_order_reason_id"`
	Name                  string `json:"name"`
	InitialStatusID       int32  `json:"initial_status_id"`
	InitialStatusName     string `json:"initial_status_name"`
}

func (q *Queries) GetLogisticOrderReasonByID(ctx context.Context, logisticOrderReasonID int32) (GetLogisticOrderReasonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLogisticOrderReasonByID, logisticOrderReasonID)
	var i GetLogisticOrderReasonByIDRow
	err := row.Scan(
		&i.LogisticOrderReasonID,
		&i.Name,
		&i.InitialStatusID,
		&i.InitialStatusName,
	)
	return i, err
}

const getLogisticOrderStatusByID = `-- name: GetLogisticOrderStatusByID :one
SELECT logistic_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_pending_approval, is_rh_step
FROM logistic_order_status
WHERE logistic_order_status_id=?
`

func (q *Queries) GetLogisticOrderStatusByID(ctx context.Context, logisticOrderStatusID int32) (LogisticOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getLogisticOrderStatusByID, logisticOrderStatusID)
	var i LogisticOrderStatus
	err := row.Scan(
		&i.LogisticOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsPendingApproval,
		&i.IsRhStep,
	)
	return i, err
}

const getOrCreateLogisticConfig = `-- name: GetOrCreateLogisticConfig :one

SELECT logistic_config_id, salary_discount_access_level_id FROM logistic_config LIMIT 1
`

// ── Logistic Config ───────────────────────────────────────────────────────────
func (q *Queries) GetOrCreateLogisticConfig(ctx context.Context) (LogisticConfig, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateLogisticConfig)
	var i LogisticConfig
	err := row.Scan(&i.LogisticConfigID, &i.SalaryDiscountAccessLevelID)
	return i, err
}

const insertLogisticConfig = `-- name: InsertLogisticConfig :execresult
INSERT INTO logistic_config (salary_discount_access_level_id) VALUES (NULL)
`

func (q *Queries) InsertLogisticConfig(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertLogisticConfig)
}

const insertLogisticConfigAssignableAccessLevel = `-- name: InsertLogisticConfigAssignableAccessLevel :exec
INSERT INTO logistic_config_assignable_access_level (logistic_config_id, access_level_id)
VALUES (?, ?)
`

type InsertLogisticConfigAssignableAccessLevelParams struct {
	LogisticConfigID int32 `json:"logistic_config_id"`
	AccessLevelID    int32 `json:"access_level_id"`
}

func (q *Queries) InsertLogisticConfigAssignableAccessLevel(ctx context.Context, arg InsertLogisticConfigAssignableAccessLevelParams) error {
	_, err := q.db.ExecContext(ctx, insertLogisticConfigAssignableAccessLevel, arg.LogisticConfigID, arg.AccessLevelID)
	return err
}

const listLogisticOperators = `-- name: ListLogisticOperators :many

SELECT logistic_operator_id, name, type FROM logistic_operator ORDER BY name
`

// ── Logistic Operators ────────────────────────────────────────────────────────
func (q *Queries) ListLogisticOperators(ctx context.Context) ([]LogisticOperator, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticOperators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogisticOperator
	for rows.Next() {
		var i LogisticOperator
		if err := rows.Scan(&i.LogisticOperatorID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogisticOrderAttachments = `-- name: ListLogisticOrderAttachments :many
SELECT logistic_order_attachment_id, logistic_order_id, file_name, file_path, file_size, created_at
FROM logistic_order_attachment
WHERE logistic_order_id=? AND deleted_at IS NULL
ORDER BY created_at
`

type ListLogisticOrderAttachmentsRow struct {
	LogisticOrderAttachmentID int32     `json:"logistic_order_attachment_id"`
	LogisticOrderID           int32     `json:"logistic_order_id"`
	FileName                  string    `json:"file_name"`
	FilePath                  string    `json:"file_path"`
	FileSize                  int32     `json:"file_size"`
	CreatedAt                 time.Time `json:"created_at"`
}

func (q *Queries) ListLogisticOrderAttachments(ctx context.Context, logisticOrderID int32) ([]ListLogisticOrderAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticOrderAttachments, logisticOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogisticOrderAttachmentsRow
	for rows.Next() {
		var i ListLogisticOrderAttachmentsRow
		if err := rows.Scan(
			&i.LogisticOrderAttachmentID,
			&i.LogisticOrderID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogisticOrderItems = `-- name: ListLogisticOrderItems :many
SELECT logistic_order_item_id, logistic_order_id, name, item_code, quantity
FROM logistic_order_items
WHERE logistic_order_id=? AND deleted_at IS NULL
`

type ListLogisticOrderItemsRow struct {
	LogisticOrderItemID int32  `json:"logistic_order_item_id"`
	LogisticOrderID     int32  `json:"logistic_order_id"`
	Name                string `json:"name"`
	ItemCode            string `json:"item_code"`
	Quantity            int32  `json:"quantity"`
}

func (q *Queries) ListLogisticOrderItems(ctx context.Context, logisticOrderID int32) ([]ListLogisticOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticOrderItems, logisticOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogisticOrderItemsRow
	for rows.Next() {
		var i ListLogisticOrderItemsRow
		if err := rows.Scan(
			&i.LogisticOrderItemID,
			&i.LogisticOrderID,
			&i.Name,
			&i.ItemCode,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogisticOrderPriorities = `-- name: ListLogisticOrderPriorities :many

SELECT logistic_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM logistic_order_priorities
ORDER BY sort_index
`

// ── Logistic Priority ─────────────────────────────────────────────────────────
func (q *Queries) ListLogisticOrderPriorities(ctx context.Context) ([]LogisticOrderPriority, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticOrderPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogisticOrderPriority
	for rows.Next() {
		var i LogisticOrderPriority
		if err := rows.Scan(
			&i.LogisticOrderPriorityID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogisticOrderReasons = `-- name: ListLogisticOrderReasons :many

SELECT r.logistic_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM logistic_order_reason r
JOIN logistic_order_status s ON s.logistic_order_status_id = r.initial_status_id
WHERE r.deleted_at IS NULL
ORDER BY r.name
`

type ListLogisticOrderReasonsRow struct {
	LogisticOrderReasonID int32  `json:"logistic_order_reason_id"`
	Name                  string `json:"name"`
	InitialStatusID       int32  `json:"initial_status_id"`
	InitialStatusName     string `json:"initial_status_name"`
}

// ── Logistic Reason ───────────────────────────────────────────────────────────
func (q *Queries) ListLogisticOrderReasons(ctx context.Context) ([]ListLogisticOrderReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticOrderReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogisticOrderReasonsRow
	for rows.Next() {
		var i ListLogisticOrderReasonsRow
		if err := rows.Scan(
			&i.LogisticOrderReasonID,
			&i.Name,
			&i.InitialStatusID,
			&i.InitialStatusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogisticOrderStatuses = `-- name: ListLogisticOrderStatuses :many

SELECT logistic_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_pending_approval, is_rh_step
FROM logistic_order_status
ORDER BY sort_index
`

// ── Logistic Status ───────────────────────────────────────────────────────────
func (q *Queries) ListLogisticOrderStatuses(ctx context.Context) ([]LogisticOrderStatus, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticOrderStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogisticOrderStatus
	for rows.Next() {
		var i LogisticOrderStatus
		if err := rows.Scan(
			&i.LogisticOrderStatusID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
			&i.IsClosed,
			&i.IsPendingApproval,
			&i.IsRhStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogisticStatusTransitions = `-- name: ListLogisticStatusTransitions :many

SELECT id, from_status_id, to_status_id, access_level_id
FROM logistic_order_status_transition
`

// ── Logistic Status Transitions ───────────────────────────────────────────────
func (q *Queries) ListLogisticStatusTransitions(ctx context.Context) ([]LogisticOrderStatusTransition, error) {
	rows, err := q.db.QueryContext(ctx, listLogisticStatusTransitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogisticOrderStatusTransition
	for rows.Next() {
		var i LogisticOrderStatusTransition
		if err := rows.Scan(
			&i.ID,
			&i.FromStatusID,
			&i.ToStatusID,
			&i.AccessLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLogisticCheckerSignature = `-- name: SaveLogisticCheckerSignature :exec
UPDATE logistic_order SET checker_name=?, checker_signature=?
WHERE logistic_order_id=? AND deleted_at IS NULL
`

type SaveLogisticCheckerSignatureParams struct {
	CheckerName      sql.NullString `json:"checker_name"`
	CheckerSignature sql.NullString `json:"checker_signature"`
	LogisticOrderID  int32          `json:"logistic_order_id"`
}

func (q *Queries) SaveLogisticCheckerSignature(ctx context.Context, arg SaveLogisticCheckerSignatureParams) error {
	_, err := q.db.ExecContext(ctx, saveLogisticCheckerSignature, arg.CheckerName, arg.CheckerSignature, arg.LogisticOrderID)
	return err
}

const updateLogisticConfigSalaryDiscount = `-- name: UpdateLogisticConfigSalaryDiscount :exec
UPDATE logistic_config SET salary_discount_access_level_id=? WHERE logistic_config_id=?
`

type UpdateLogisticConfigSalaryDiscountParams struct {
	SalaryDiscountAccessLevelID sql.NullInt32 `json:"salary_discount_access_level_id"`
	LogisticConfigID            int32         `json:"logistic_config_id"`
}

func (q *Queries) UpdateLogisticConfigSalaryDiscount(ctx context.Context, arg UpdateLogisticConfigSalaryDiscountParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticConfigSalaryDiscount, arg.SalaryDiscountAccessLevelID, arg.LogisticConfigID)
	return err
}

const updateLogisticOperator = `-- name: UpdateLogisticOperator :exec
UPDATE logistic_operator SET name=?, type=? WHERE logistic_operator_id=?
`

type UpdateLogisticOperatorParams struct {
	Name               string               `json:"name"`
	Type               LogisticOperatorType `json:"type"`
	LogisticOperatorID int32                `json:"logistic_operator_id"`
}

func (q *Queries) UpdateLogisticOperator(ctx context.Context, arg UpdateLogisticOperatorParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticOperator, arg.Name, arg.Type, arg.LogisticOperatorID)
	return err
}

const updateLogisticOrder = `-- name: UpdateLogisticOrder :exec
UPDATE logistic_order
SET assigned_to_id=?, assigned_to_name=?, driver_name=?, checker_name=?,
    salesperson_name=?, client_code=?, client_name=?, client_alias_name=?,
    contact_type=?, contact_name=?, contact_phone=?, contact_mobile=?, contact_email=?,
    address_name=?, address_type=?, type_of_address=?, street=?, street_no=?, block=?,
    city=?, county=?, state=?, country=?, zip_code=?, building_floor_room=?,
    status_id=?, priority_id=?, reason_id=?, schedule_date=?, description=?,
    has_salary_discount=?, salary_discount_reason=?,
    captured_at=?, resolution=?, closed_at=?
WHERE logistic_order_id=? AND deleted_at IS NULL
`

type UpdateLogisticOrderParams struct {
	AssignedToID         sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName       sql.NullString `json:"assigned_to_name"`
	DriverName           sql.NullString `json:"driver_name"`
	CheckerName          sql.NullString `json:"checker_name"`
	SalespersonName      sql.NullString `json:"salesperson_name"`
	ClientCode           string         `json:"client_code"`
	ClientName           string         `json:"client_name"`
	ClientAliasName      string         `json:"client_alias_name"`
	ContactType          sql.NullString `json:"contact_type"`
	ContactName          sql.NullString `json:"contact_name"`
	ContactPhone         sql.NullString `json:"contact_phone"`
	ContactMobile        sql.NullString `json:"contact_mobile"`
	ContactEmail         sql.NullString `json:"contact_email"`
	AddressName          sql.NullString `json:"address_name"`
	AddressType          sql.NullString `json:"address_type"`
	TypeOfAddress        sql.NullString `json:"type_of_address"`
	Street               sql.NullString `json:"street"`
	StreetNo             sql.NullString `json:"street_no"`
	Block                sql.NullString `json:"block"`
	City                 sql.NullString `json:"city"`
	County               sql.NullString `json:"county"`
	State                sql.NullString `json:"state"`
	Country              sql.NullString `json:"country"`
	ZipCode              sql.NullString `json:"zip_code"`
	BuildingFloorRoom    sql.NullString `json:"building_floor_room"`
	StatusID             int32          `json:"status_id"`
	PriorityID           int32          `json:"priority_id"`
	ReasonID             int32          `json:"reason_id"`
	ScheduleDate         sql.NullTime   `json:"schedule_date"`
	Description          string         `json:"description"`
	HasSalaryDiscount    sql.NullBool   `json:"has_salary_discount"`
	SalaryDiscountReason sql.NullString `json:"salary_discount_reason"`
	CapturedAt           sql.NullTime   `json:"captured_at"`
	Resolution           sql.NullString `json:"resolution"`
	ClosedAt             sql.NullTime   `json:"closed_at"`
	LogisticOrderID      int32          `json:"logistic_order_id"`
}

func (q *Queries) UpdateLogisticOrder(ctx context.Context, arg UpdateLogisticOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticOrder,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.DriverName,
		arg.CheckerName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.ContactType,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactMobile,
		arg.ContactEmail,
		arg.AddressName,
		arg.AddressType,
		arg.TypeOfAddress,
		arg.Street,
		arg.StreetNo,
		arg.Block,
		arg.City,
		arg.County,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.BuildingFloorRoom,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.ScheduleDate,
		arg.Description,
		arg.HasSalaryDiscount,
		arg.SalaryDiscountReason,
		arg.CapturedAt,
		arg.Resolution,
		arg.ClosedAt,
		arg.LogisticOrderID,
	)
	return err
}

const updateLogisticOrderPriority = `-- name: UpdateLogisticOrderPriority :exec
UPDATE logistic_order_priorities
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?
WHERE logistic_order_priority_id=?
`

type UpdateLogisticOrderPriorityParams struct {
	Name                    string `json:"name"`
	BackgroundColor         string `json:"background_color"`
	BorderColor             string `json:"border_color"`
	TextColor               string `json:"text_color"`
	SortIndex               int32  `json:"sort_index"`
	LogisticOrderPriorityID int32  `json:"logistic_order_priority_id"`
}

func (q *Queries) UpdateLogisticOrderPriority(ctx context.Context, arg UpdateLogisticOrderPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.LogisticOrderPriorityID,
	)
	return err
}

const updateLogisticOrderReason = `-- name: UpdateLogisticOrderReason :exec
UPDATE logistic_order_reason SET name=?, initial_status_id=?
WHERE logistic_order_reason_id=? AND deleted_at IS NULL
`

type UpdateLogisticOrderReasonParams struct {
	Name                  string `json:"name"`
	InitialStatusID       int32  `json:"initial_status_id"`
	LogisticOrderReasonID int32  `json:"logistic_order_reason_id"`
}

func (q *Queries) UpdateLogisticOrderReason(ctx context.Context, arg UpdateLogisticOrderReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticOrderReason, arg.Name, arg.InitialStatusID, arg.LogisticOrderReasonID)
	return err
}

const updateLogisticOrderStatus = `-- name: UpdateLogisticOrderStatus :exec
UPDATE logistic_order SET status_id=?, captured_at=?, closed_at=?
WHERE logistic_order_id=? AND deleted_at IS NULL
`

type UpdateLogisticOrderStatusParams struct {
	StatusID        int32        `json:"status_id"`
	CapturedAt      sql.NullTime `json:"captured_at"`
	ClosedAt        sql.NullTime `json:"closed_at"`
	LogisticOrderID int32        `json:"logistic_order_id"`
}

func (q *Queries) UpdateLogisticOrderStatus(ctx context.Context, arg UpdateLogisticOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticOrderStatus,
		arg.StatusID,
		arg.CapturedAt,
		arg.ClosedAt,
		arg.LogisticOrderID,
	)
	return err
}

const updateLogisticStatusRecord = `-- name: UpdateLogisticStatusRecord :exec
UPDATE logistic_order_status
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?,
    is_closed=?, is_pending_approval=?, is_rh_step=?
WHERE logistic_order_status_id=?
`

type UpdateLogisticStatusRecordParams struct {
	Name                  string `json:"name"`
	BackgroundColor       string `json:"background_color"`
	BorderColor           string `json:"border_color"`
	TextColor             string `json:"text_color"`
	SortIndex             int32  `json:"sort_index"`
	IsClosed              bool   `json:"is_closed"`
	IsPendingApproval     bool   `json:"is_pending_approval"`
	IsRhStep              bool   `json:"is_rh_step"`
	LogisticOrderStatusID int32  `json:"logistic_order_status_id"`
}

func (q *Queries) UpdateLogisticStatusRecord(ctx context.Context, arg UpdateLogisticStatusRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateLogisticStatusRecord,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsPendingApproval,
		arg.IsRhStep,
		arg.LogisticOrderStatusID,
	)
	return err
}
