// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: maintenance.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addConfigAssignableAccessLevel = `-- name: AddConfigAssignableAccessLevel :exec
INSERT INTO maintenance_order_config_assignable_access_level
  (maintenance_order_config_id, access_level_id) VALUES (?, ?)
`

type AddConfigAssignableAccessLevelParams struct {
	MaintenanceOrderConfigID int32 `json:"maintenance_order_config_id"`
	AccessLevelID            int32 `json:"access_level_id"`
}

func (q *Queries) AddConfigAssignableAccessLevel(ctx context.Context, arg AddConfigAssignableAccessLevelParams) error {
	_, err := q.db.ExecContext(ctx, addConfigAssignableAccessLevel, arg.MaintenanceOrderConfigID, arg.AccessLevelID)
	return err
}

const countTechnicianOnDate = `-- name: CountTechnicianOnDate :one
SELECT COUNT(*) FROM maintenance_order_schedule_date_technician
WHERE maintenance_order_schedule_date_id = ? AND technician_id = ? AND deleted_at IS NULL
`

type CountTechnicianOnDateParams struct {
	MaintenanceOrderScheduleDateID int32 `json:"maintenance_order_schedule_date_id"`
	TechnicianID                   int32 `json:"technician_id"`
}

func (q *Queries) CountTechnicianOnDate(ctx context.Context, arg CountTechnicianOnDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTechnicianOnDate, arg.MaintenanceOrderScheduleDateID, arg.TechnicianID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklistAnswer = `-- name: CreateChecklistAnswer :exec

INSERT INTO maintenance_order_checklist_answer (checklist_id, item_id, value) VALUES (?, ?, ?)
`

type CreateChecklistAnswerParams struct {
	ChecklistID int32          `json:"checklist_id"`
	ItemID      int32          `json:"item_id"`
	Value       sql.NullString `json:"value"`
}

// ── Checklist answers ─────────────────────────────────────────────────────────
func (q *Queries) CreateChecklistAnswer(ctx context.Context, arg CreateChecklistAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createChecklistAnswer, arg.ChecklistID, arg.ItemID, arg.Value)
	return err
}

const createChecklistItem = `-- name: CreateChecklistItem :execresult
INSERT INTO maintenance_order_checklist_item
    (template_id, section, label, type, options, metadata, required, sort_order, parent_item_id, show_when_values)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChecklistItemParams struct {
	TemplateID     int32                             `json:"template_id"`
	Section        sql.NullString                    `json:"section"`
	Label          string                            `json:"label"`
	Type           MaintenanceOrderChecklistItemType `json:"type"`
	Options        sql.NullString                    `json:"options"`
	Metadata       sql.NullString                    `json:"metadata"`
	Required       bool                              `json:"required"`
	SortOrder      int32                             `json:"sort_order"`
	ParentItemID   sql.NullInt32                     `json:"parent_item_id"`
	ShowWhenValues sql.NullString                    `json:"show_when_values"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChecklistItem,
		arg.TemplateID,
		arg.Section,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Metadata,
		arg.Required,
		arg.SortOrder,
		arg.ParentItemID,
		arg.ShowWhenValues,
	)
}

const createChecklistTemplate = `-- name: CreateChecklistTemplate :execresult
INSERT INTO maintenance_order_checklist_template (name, reason_id, active) VALUES (?, ?, ?)
`

type CreateChecklistTemplateParams struct {
	Name     string        `json:"name"`
	ReasonID sql.NullInt32 `json:"reason_id"`
	Active   bool          `json:"active"`
}

func (q *Queries) CreateChecklistTemplate(ctx context.Context, arg CreateChecklistTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChecklistTemplate, arg.Name, arg.ReasonID, arg.Active)
}

const createMaintenanceConfig = `-- name: CreateMaintenanceConfig :execresult
INSERT INTO maintenance_order_config () VALUES ()
`

func (q *Queries) CreateMaintenanceConfig(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceConfig)
}

const createMaintenanceOrder = `-- name: CreateMaintenanceOrder :execresult
INSERT INTO maintenance_order (
    requester_id, requester_name, salesperson_name,
    client_code, client_name, client_alias_name,
    contact_type, contact_name, contact_phone, contact_mobile, contact_email,
    address_name, address_type, type_of_address, street, street_no, block,
    city, county, state, country, zip_code, building_floor_room,
    status_id, priority_id, reason_id, description
) VALUES (
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateMaintenanceOrderParams struct {
	RequesterID       int32          `json:"requester_id"`
	RequesterName     string         `json:"requester_name"`
	SalespersonName   sql.NullString `json:"salesperson_name"`
	ClientCode        string         `json:"client_code"`
	ClientName        string         `json:"client_name"`
	ClientAliasName   string         `json:"client_alias_name"`
	ContactType       sql.NullString `json:"contact_type"`
	ContactName       sql.NullString `json:"contact_name"`
	ContactPhone      sql.NullString `json:"contact_phone"`
	ContactMobile     sql.NullString `json:"contact_mobile"`
	ContactEmail      sql.NullString `json:"contact_email"`
	AddressName       sql.NullString `json:"address_name"`
	AddressType       sql.NullString `json:"address_type"`
	TypeOfAddress     sql.NullString `json:"type_of_address"`
	Street            sql.NullString `json:"street"`
	StreetNo          sql.NullString `json:"street_no"`
	Block             sql.NullString `json:"block"`
	City              sql.NullString `json:"city"`
	County            sql.NullString `json:"county"`
	State             sql.NullString `json:"state"`
	Country           sql.NullString `json:"country"`
	ZipCode           sql.NullString `json:"zip_code"`
	BuildingFloorRoom sql.NullString `json:"building_floor_room"`
	StatusID          int32          `json:"status_id"`
	PriorityID        int32          `json:"priority_id"`
	ReasonID          int32          `json:"reason_id"`
	Description       string         `json:"description"`
}

func (q *Queries) CreateMaintenanceOrder(ctx context.Context, arg CreateMaintenanceOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrder,
		arg.RequesterID,
		arg.RequesterName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.ContactType,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactMobile,
		arg.ContactEmail,
		arg.AddressName,
		arg.AddressType,
		arg.TypeOfAddress,
		arg.Street,
		arg.StreetNo,
		arg.Block,
		arg.City,
		arg.County,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.BuildingFloorRoom,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
	)
}

const createMaintenanceOrderAttachment = `-- name: CreateMaintenanceOrderAttachment :execresult

INSERT INTO maintenance_order_attachment (maintenance_order_id, file_name, file_path, file_size)
VALUES (?, ?, ?, ?)
`

type CreateMaintenanceOrderAttachmentParams struct {
	MaintenanceOrderID int32  `json:"maintenance_order_id"`
	FileName           string `json:"file_name"`
	FilePath           string `json:"file_path"`
	FileSize           int32  `json:"file_size"`
}

// ── Attachments ───────────────────────────────────────────────────────────────
func (q *Queries) CreateMaintenanceOrderAttachment(ctx context.Context, arg CreateMaintenanceOrderAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderAttachment,
		arg.MaintenanceOrderID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
	)
}

const createMaintenanceOrderItem = `-- name: CreateMaintenanceOrderItem :exec

INSERT INTO maintenance_order_items (maintenance_order_id, name, item_code, quantity)
VALUES (?, ?, ?, ?)
`

type CreateMaintenanceOrderItemParams struct {
	MaintenanceOrderID int32  `json:"maintenance_order_id"`
	Name               string `json:"name"`
	ItemCode           string `json:"item_code"`
	Quantity           int32  `json:"quantity"`
}

// ── Order items ───────────────────────────────────────────────────────────────
func (q *Queries) CreateMaintenanceOrderItem(ctx context.Context, arg CreateMaintenanceOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createMaintenanceOrderItem,
		arg.MaintenanceOrderID,
		arg.Name,
		arg.ItemCode,
		arg.Quantity,
	)
	return err
}

const createMaintenanceOrderNoteTemplate = `-- name: CreateMaintenanceOrderNoteTemplate :execresult
INSERT INTO maintenance_order_note_template (name, description) VALUES (?, ?)
`

type CreateMaintenanceOrderNoteTemplateParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateMaintenanceOrderNoteTemplate(ctx context.Context, arg CreateMaintenanceOrderNoteTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderNoteTemplate, arg.Name, arg.Description)
}

const createMaintenanceOrderPriority = `-- name: CreateMaintenanceOrderPriority :execresult
INSERT INTO maintenance_order_priorities (name, background_color, border_color, text_color, sort_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateMaintenanceOrderPriorityParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
}

func (q *Queries) CreateMaintenanceOrderPriority(ctx context.Context, arg CreateMaintenanceOrderPriorityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
	)
}

const createMaintenanceOrderReason = `-- name: CreateMaintenanceOrderReason :execresult
INSERT INTO maintenance_order_reason (name) VALUES (?)
`

func (q *Queries) CreateMaintenanceOrderReason(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderReason, name)
}

const createMaintenanceOrderResolutionItem = `-- name: CreateMaintenanceOrderResolutionItem :exec

INSERT INTO maintenance_order_resolution_items (maintenance_order_id, name, item_code, quantity)
VALUES (?, ?, ?, ?)
`

type CreateMaintenanceOrderResolutionItemParams struct {
	MaintenanceOrderID int32  `json:"maintenance_order_id"`
	Name               string `json:"name"`
	ItemCode           string `json:"item_code"`
	Quantity           int32  `json:"quantity"`
}

// ── Resolution items ──────────────────────────────────────────────────────────
func (q *Queries) CreateMaintenanceOrderResolutionItem(ctx context.Context, arg CreateMaintenanceOrderResolutionItemParams) error {
	_, err := q.db.ExecContext(ctx, createMaintenanceOrderResolutionItem,
		arg.MaintenanceOrderID,
		arg.Name,
		arg.ItemCode,
		arg.Quantity,
	)
	return err
}

const createMaintenanceOrderScheduleDate = `-- name: CreateMaintenanceOrderScheduleDate :execresult

INSERT INTO maintenance_order_schedule_date (maintenance_order_id, date) VALUES (?, ?)
`

type CreateMaintenanceOrderScheduleDateParams struct {
	MaintenanceOrderID int32     `json:"maintenance_order_id"`
	Date               time.Time `json:"date"`
}

// ── Schedule dates ────────────────────────────────────────────────────────────
func (q *Queries) CreateMaintenanceOrderScheduleDate(ctx context.Context, arg CreateMaintenanceOrderScheduleDateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderScheduleDate, arg.MaintenanceOrderID, arg.Date)
}

const createMaintenanceOrderStatus = `-- name: CreateMaintenanceOrderStatus :execresult
INSERT INTO maintenance_order_status (name, background_color, border_color, text_color, sort_index, is_closed, is_default)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMaintenanceOrderStatusParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
	IsClosed        bool   `json:"is_closed"`
	IsDefault       bool   `json:"is_default"`
}

func (q *Queries) CreateMaintenanceOrderStatus(ctx context.Context, arg CreateMaintenanceOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
	)
}

const createMaintenanceOrderTimeEntry = `-- name: CreateMaintenanceOrderTimeEntry :exec

INSERT INTO maintenance_order_time_entry (maintenance_order_id, type_id, started_at, ended_at)
VALUES (?, ?, ?, ?)
`

type CreateMaintenanceOrderTimeEntryParams struct {
	MaintenanceOrderID int32        `json:"maintenance_order_id"`
	TypeID             int32        `json:"type_id"`
	StartedAt          time.Time    `json:"started_at"`
	EndedAt            sql.NullTime `json:"ended_at"`
}

// ── Time entries ──────────────────────────────────────────────────────────────
func (q *Queries) CreateMaintenanceOrderTimeEntry(ctx context.Context, arg CreateMaintenanceOrderTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, createMaintenanceOrderTimeEntry,
		arg.MaintenanceOrderID,
		arg.TypeID,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const createMaintenanceOrderTimeEntryType = `-- name: CreateMaintenanceOrderTimeEntryType :execresult
INSERT INTO maintenance_order_time_entry_type (name, color) VALUES (?, ?)
`

type CreateMaintenanceOrderTimeEntryTypeParams struct {
	Name  string         `json:"name"`
	Color sql.NullString `json:"color"`
}

func (q *Queries) CreateMaintenanceOrderTimeEntryType(ctx context.Context, arg CreateMaintenanceOrderTimeEntryTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaintenanceOrderTimeEntryType, arg.Name, arg.Color)
}

const createOrderChecklist = `-- name: CreateOrderChecklist :execresult
INSERT INTO maintenance_order_checklist (maintenance_order_id, template_id) VALUES (?, ?)
`

type CreateOrderChecklistParams struct {
	MaintenanceOrderID int32 `json:"maintenance_order_id"`
	TemplateID         int32 `json:"template_id"`
}

func (q *Queries) CreateOrderChecklist(ctx context.Context, arg CreateOrderChecklistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderChecklist, arg.MaintenanceOrderID, arg.TemplateID)
}

const createScheduleDateTechnician = `-- name: CreateScheduleDateTechnician :exec

INSERT INTO maintenance_order_schedule_date_technician
    (maintenance_order_schedule_date_id, technician_id, technician_name)
VALUES (?, ?, ?)
`

type CreateScheduleDateTechnicianParams struct {
	MaintenanceOrderScheduleDateID int32  `json:"maintenance_order_schedule_date_id"`
	TechnicianID                   int32  `json:"technician_id"`
	TechnicianName                 string `json:"technician_name"`
}

// ── Schedule date technicians ─────────────────────────────────────────────────
func (q *Queries) CreateScheduleDateTechnician(ctx context.Context, arg CreateScheduleDateTechnicianParams) error {
	_, err := q.db.ExecContext(ctx, createScheduleDateTechnician, arg.MaintenanceOrderScheduleDateID, arg.TechnicianID, arg.TechnicianName)
	return err
}

const deleteConfigAssignableAccessLevels = `-- name: DeleteConfigAssignableAccessLevels :exec
DELETE FROM maintenance_order_config_assignable_access_level
WHERE maintenance_order_config_id = ?
`

func (q *Queries) DeleteConfigAssignableAccessLevels(ctx context.Context, maintenanceOrderConfigID int32) error {
	_, err := q.db.ExecContext(ctx, deleteConfigAssignableAccessLevels, maintenanceOrderConfigID)
	return err
}

const deleteMaintenanceOrderItems = `-- name: DeleteMaintenanceOrderItems :exec
UPDATE maintenance_order_items SET deleted_at = NOW()
WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteMaintenanceOrderItems(ctx context.Context, maintenanceOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderItems, maintenanceOrderID)
	return err
}

const deleteMaintenanceOrderPriority = `-- name: DeleteMaintenanceOrderPriority :exec
DELETE FROM maintenance_order_priorities WHERE maintenance_order_priorities_id = ?
`

func (q *Queries) DeleteMaintenanceOrderPriority(ctx context.Context, maintenanceOrderPrioritiesID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderPriority, maintenanceOrderPrioritiesID)
	return err
}

const deleteMaintenanceOrderResolutionItems = `-- name: DeleteMaintenanceOrderResolutionItems :exec
UPDATE maintenance_order_resolution_items SET deleted_at = NOW()
WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteMaintenanceOrderResolutionItems(ctx context.Context, maintenanceOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderResolutionItems, maintenanceOrderID)
	return err
}

const deleteMaintenanceOrderScheduleDates = `-- name: DeleteMaintenanceOrderScheduleDates :exec
UPDATE maintenance_order_schedule_date SET deleted_at = NOW()
WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteMaintenanceOrderScheduleDates(ctx context.Context, maintenanceOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderScheduleDates, maintenanceOrderID)
	return err
}

const deleteMaintenanceOrderStatus = `-- name: DeleteMaintenanceOrderStatus :exec
DELETE FROM maintenance_order_status WHERE maintenance_order_status_id = ?
`

func (q *Queries) DeleteMaintenanceOrderStatus(ctx context.Context, maintenanceOrderStatusID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderStatus, maintenanceOrderStatusID)
	return err
}

const deleteMaintenanceOrderTimeEntries = `-- name: DeleteMaintenanceOrderTimeEntries :exec
UPDATE maintenance_order_time_entry SET deleted_at = NOW()
WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteMaintenanceOrderTimeEntries(ctx context.Context, maintenanceOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderTimeEntries, maintenanceOrderID)
	return err
}

const deleteMaintenanceOrderTimeEntryType = `-- name: DeleteMaintenanceOrderTimeEntryType :exec
DELETE FROM maintenance_order_time_entry_type WHERE maintenance_order_time_entry_type_id = ?
`

func (q *Queries) DeleteMaintenanceOrderTimeEntryType(ctx context.Context, maintenanceOrderTimeEntryTypeID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceOrderTimeEntryType, maintenanceOrderTimeEntryTypeID)
	return err
}

const deleteScheduleDateTechnicians = `-- name: DeleteScheduleDateTechnicians :exec
UPDATE maintenance_order_schedule_date_technician SET deleted_at = NOW()
WHERE maintenance_order_schedule_date_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteScheduleDateTechnicians(ctx context.Context, maintenanceOrderScheduleDateID int32) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleDateTechnicians, maintenanceOrderScheduleDateID)
	return err
}

const getChecklistItemByID = `-- name: GetChecklistItemByID :one
SELECT maintenance_order_checklist_item_id, template_id, section, label, type, options, metadata, required, sort_order, parent_item_id, show_when_values, created_at, updated_at, deleted_at FROM maintenance_order_checklist_item
WHERE maintenance_order_checklist_item_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetChecklistItemByID(ctx context.Context, maintenanceOrderChecklistItemID int32) (MaintenanceOrderChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, getChecklistItemByID, maintenanceOrderChecklistItemID)
	var i MaintenanceOrderChecklistItem
	err := row.Scan(
		&i.MaintenanceOrderChecklistItemID,
		&i.TemplateID,
		&i.Section,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.Metadata,
		&i.Required,
		&i.SortOrder,
		&i.ParentItemID,
		&i.ShowWhenValues,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChecklistTemplateByID = `-- name: GetChecklistTemplateByID :one
SELECT maintenance_order_checklist_template_id, name, reason_id, active, created_at, updated_at, deleted_at FROM maintenance_order_checklist_template
WHERE maintenance_order_checklist_template_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetChecklistTemplateByID(ctx context.Context, maintenanceOrderChecklistTemplateID int32) (MaintenanceOrderChecklistTemplate, error) {
	row := q.db.QueryRowContext(ctx, getChecklistTemplateByID, maintenanceOrderChecklistTemplateID)
	var i MaintenanceOrderChecklistTemplate
	err := row.Scan(
		&i.MaintenanceOrderChecklistTemplateID,
		&i.Name,
		&i.ReasonID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConfigAssignableAccessLevelIDs = `-- name: GetConfigAssignableAccessLevelIDs :many
SELECT access_level_id
FROM maintenance_order_config_assignable_access_level
WHERE maintenance_order_config_id = ?
`

func (q *Queries) GetConfigAssignableAccessLevelIDs(ctx context.Context, maintenanceOrderConfigID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getConfigAssignableAccessLevelIDs, maintenanceOrderConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var access_level_id int32
		if err := rows.Scan(&access_level_id); err != nil {
			return nil, err
		}
		items = append(items, access_level_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultMaintenanceOrderStatus = `-- name: GetDefaultMaintenanceOrderStatus :one
SELECT maintenance_order_status_id, name, background_color, border_color, text_color, sort_index, is_closed, is_default FROM maintenance_order_status WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultMaintenanceOrderStatus(ctx context.Context) (MaintenanceOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getDefaultMaintenanceOrderStatus)
	var i MaintenanceOrderStatus
	err := row.Scan(
		&i.MaintenanceOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsDefault,
	)
	return i, err
}

const getFirstMaintenanceOrderStatusBySort = `-- name: GetFirstMaintenanceOrderStatusBySort :one
SELECT maintenance_order_status_id, name, background_color, border_color, text_color, sort_index, is_closed, is_default FROM maintenance_order_status ORDER BY sort_index ASC LIMIT 1
`

func (q *Queries) GetFirstMaintenanceOrderStatusBySort(ctx context.Context) (MaintenanceOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getFirstMaintenanceOrderStatusBySort)
	var i MaintenanceOrderStatus
	err := row.Scan(
		&i.MaintenanceOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsDefault,
	)
	return i, err
}

const getMaintenanceConfig = `-- name: GetMaintenanceConfig :one

SELECT maintenance_order_config_id FROM maintenance_order_config LIMIT 1
`

// ── Config ────────────────────────────────────────────────────────────────────
func (q *Queries) GetMaintenanceConfig(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceConfig)
	var maintenance_order_config_id int32
	err := row.Scan(&maintenance_order_config_id)
	return maintenance_order_config_id, err
}

const getMaintenanceOrderAttachmentByID = `-- name: GetMaintenanceOrderAttachmentByID :one
SELECT maintenance_order_attachment_id, maintenance_order_id, file_name, file_path, file_size, created_at, updated_at, deleted_at FROM maintenance_order_attachment
WHERE maintenance_order_attachment_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetMaintenanceOrderAttachmentByID(ctx context.Context, maintenanceOrderAttachmentID int32) (MaintenanceOrderAttachment, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderAttachmentByID, maintenanceOrderAttachmentID)
	var i MaintenanceOrderAttachment
	err := row.Scan(
		&i.MaintenanceOrderAttachmentID,
		&i.MaintenanceOrderID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaintenanceOrderByID = `-- name: GetMaintenanceOrderByID :one

SELECT maintenance_order_id, requester_id, requester_name, salesperson_name, client_code, client_name, client_alias_name, contact_type, contact_name, contact_phone, contact_mobile, contact_email, address_name, address_type, type_of_address, street, street_no, block, city, county, state, country, zip_code, building_floor_room, status_id, priority_id, reason_id, description, captured_at, resolution, motivo_resolution, client_signature, closed_at, created_at, updated_at, deleted_at FROM maintenance_order WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

// ── Main order ────────────────────────────────────────────────────────────────
func (q *Queries) GetMaintenanceOrderByID(ctx context.Context, maintenanceOrderID int32) (MaintenanceOrder, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderByID, maintenanceOrderID)
	var i MaintenanceOrder
	err := row.Scan(
		&i.MaintenanceOrderID,
		&i.RequesterID,
		&i.RequesterName,
		&i.SalespersonName,
		&i.ClientCode,
		&i.ClientName,
		&i.ClientAliasName,
		&i.ContactType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactMobile,
		&i.ContactEmail,
		&i.AddressName,
		&i.AddressType,
		&i.TypeOfAddress,
		&i.Street,
		&i.StreetNo,
		&i.Block,
		&i.City,
		&i.County,
		&i.State,
		&i.Country,
		&i.ZipCode,
		&i.BuildingFloorRoom,
		&i.StatusID,
		&i.PriorityID,
		&i.ReasonID,
		&i.Description,
		&i.CapturedAt,
		&i.Resolution,
		&i.MotivoResolution,
		&i.ClientSignature,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaintenanceOrderNoteTemplateByID = `-- name: GetMaintenanceOrderNoteTemplateByID :one
SELECT maintenance_order_note_template_id, name, description, created_at, updated_at, deleted_at FROM maintenance_order_note_template WHERE maintenance_order_note_template_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetMaintenanceOrderNoteTemplateByID(ctx context.Context, maintenanceOrderNoteTemplateID int32) (MaintenanceOrderNoteTemplate, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderNoteTemplateByID, maintenanceOrderNoteTemplateID)
	var i MaintenanceOrderNoteTemplate
	err := row.Scan(
		&i.MaintenanceOrderNoteTemplateID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaintenanceOrderPriorityByID = `-- name: GetMaintenanceOrderPriorityByID :one
SELECT maintenance_order_priorities_id, name, background_color, border_color, text_color, sort_index FROM maintenance_order_priorities WHERE maintenance_order_priorities_id = ?
`

func (q *Queries) GetMaintenanceOrderPriorityByID(ctx context.Context, maintenanceOrderPrioritiesID int32) (MaintenanceOrderPriority, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderPriorityByID, maintenanceOrderPrioritiesID)
	var i MaintenanceOrderPriority
	err := row.Scan(
		&i.MaintenanceOrderPrioritiesID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
	)
	return i, err
}

const getMaintenanceOrderReasonByID = `-- name: GetMaintenanceOrderReasonByID :one
SELECT maintenance_order_reason_id, name, created_at, updated_at, deleted_at FROM maintenance_order_reason WHERE maintenance_order_reason_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetMaintenanceOrderReasonByID(ctx context.Context, maintenanceOrderReasonID int32) (MaintenanceOrderReason, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderReasonByID, maintenanceOrderReasonID)
	var i MaintenanceOrderReason
	err := row.Scan(
		&i.MaintenanceOrderReasonID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaintenanceOrderStatusByID = `-- name: GetMaintenanceOrderStatusByID :one
SELECT maintenance_order_status_id, name, background_color, border_color, text_color, sort_index, is_closed, is_default FROM maintenance_order_status WHERE maintenance_order_status_id = ?
`

func (q *Queries) GetMaintenanceOrderStatusByID(ctx context.Context, maintenanceOrderStatusID int32) (MaintenanceOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderStatusByID, maintenanceOrderStatusID)
	var i MaintenanceOrderStatus
	err := row.Scan(
		&i.MaintenanceOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsDefault,
	)
	return i, err
}

const getMaintenanceOrderTimeEntryTypeByID = `-- name: GetMaintenanceOrderTimeEntryTypeByID :one
SELECT maintenance_order_time_entry_type_id, name, color FROM maintenance_order_time_entry_type WHERE maintenance_order_time_entry_type_id = ?
`

func (q *Queries) GetMaintenanceOrderTimeEntryTypeByID(ctx context.Context, maintenanceOrderTimeEntryTypeID int32) (MaintenanceOrderTimeEntryType, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceOrderTimeEntryTypeByID, maintenanceOrderTimeEntryTypeID)
	var i MaintenanceOrderTimeEntryType
	err := row.Scan(&i.MaintenanceOrderTimeEntryTypeID, &i.Name, &i.Color)
	return i, err
}

const getOrderChecklistByID = `-- name: GetOrderChecklistByID :one
SELECT maintenance_order_checklist_id, maintenance_order_id, template_id, completed_at, created_at, updated_at, deleted_at FROM maintenance_order_checklist
WHERE maintenance_order_checklist_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetOrderChecklistByID(ctx context.Context, maintenanceOrderChecklistID int32) (MaintenanceOrderChecklist, error) {
	row := q.db.QueryRowContext(ctx, getOrderChecklistByID, maintenanceOrderChecklistID)
	var i MaintenanceOrderChecklist
	err := row.Scan(
		&i.MaintenanceOrderChecklistID,
		&i.MaintenanceOrderID,
		&i.TemplateID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllTechniciansForOrder = `-- name: ListAllTechniciansForOrder :many
SELECT sdt.maintenance_order_schedule_date_technician_id, sdt.maintenance_order_schedule_date_id, sdt.technician_id, sdt.technician_name, sdt.created_at, sdt.updated_at, sdt.deleted_at
FROM maintenance_order_schedule_date_technician sdt
JOIN maintenance_order_schedule_date sd
    ON sd.maintenance_order_schedule_date_id = sdt.maintenance_order_schedule_date_id
WHERE sd.maintenance_order_id = ? AND sd.deleted_at IS NULL AND sdt.deleted_at IS NULL
`

func (q *Queries) ListAllTechniciansForOrder(ctx context.Context, maintenanceOrderID int32) ([]MaintenanceOrderScheduleDateTechnician, error) {
	rows, err := q.db.QueryContext(ctx, listAllTechniciansForOrder, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderScheduleDateTechnician
	for rows.Next() {
		var i MaintenanceOrderScheduleDateTechnician
		if err := rows.Scan(
			&i.MaintenanceOrderScheduleDateTechnicianID,
			&i.MaintenanceOrderScheduleDateID,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistAnswers = `-- name: ListChecklistAnswers :many
SELECT maintenance_order_checklist_answer_id, checklist_id, item_id, value, created_at, updated_at, deleted_at FROM maintenance_order_checklist_answer
WHERE checklist_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListChecklistAnswers(ctx context.Context, checklistID int32) ([]MaintenanceOrderChecklistAnswer, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistAnswers, checklistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderChecklistAnswer
	for rows.Next() {
		var i MaintenanceOrderChecklistAnswer
		if err := rows.Scan(
			&i.MaintenanceOrderChecklistAnswerID,
			&i.ChecklistID,
			&i.ItemID,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistItemsByTemplate = `-- name: ListChecklistItemsByTemplate :many

SELECT maintenance_order_checklist_item_id, template_id, section, label, type, options, metadata, required, sort_order, parent_item_id, show_when_values, created_at, updated_at, deleted_at FROM maintenance_order_checklist_item
WHERE template_id = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

// ── Checklist items ───────────────────────────────────────────────────────────
func (q *Queries) ListChecklistItemsByTemplate(ctx context.Context, templateID int32) ([]MaintenanceOrderChecklistItem, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistItemsByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderChecklistItem
	for rows.Next() {
		var i MaintenanceOrderChecklistItem
		if err := rows.Scan(
			&i.MaintenanceOrderChecklistItemID,
			&i.TemplateID,
			&i.Section,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.Metadata,
			&i.Required,
			&i.SortOrder,
			&i.ParentItemID,
			&i.ShowWhenValues,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistTemplates = `-- name: ListChecklistTemplates :many

SELECT maintenance_order_checklist_template_id, name, reason_id, active, created_at, updated_at, deleted_at FROM maintenance_order_checklist_template WHERE deleted_at IS NULL ORDER BY name ASC
`

// ── Checklist templates ───────────────────────────────────────────────────────
func (q *Queries) ListChecklistTemplates(ctx context.Context) ([]MaintenanceOrderChecklistTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderChecklistTemplate
	for rows.Next() {
		var i MaintenanceOrderChecklistTemplate
		if err := rows.Scan(
			&i.MaintenanceOrderChecklistTemplateID,
			&i.Name,
			&i.ReasonID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistTemplatesByReason = `-- name: ListChecklistTemplatesByReason :many
SELECT maintenance_order_checklist_template_id, name, reason_id, active, created_at, updated_at, deleted_at FROM maintenance_order_checklist_template
WHERE deleted_at IS NULL AND reason_id = ?
ORDER BY name ASC
`

func (q *Queries) ListChecklistTemplatesByReason(ctx context.Context, reasonID sql.NullInt32) ([]MaintenanceOrderChecklistTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistTemplatesByReason, reasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderChecklistTemplate
	for rows.Next() {
		var i MaintenanceOrderChecklistTemplate
		if err := rows.Scan(
			&i.MaintenanceOrderChecklistTemplateID,
			&i.Name,
			&i.ReasonID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderAttachments = `-- name: ListMaintenanceOrderAttachments :many
SELECT maintenance_order_attachment_id, maintenance_order_id, file_name, file_path, file_size, created_at, updated_at, deleted_at FROM maintenance_order_attachment
WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListMaintenanceOrderAttachments(ctx context.Context, maintenanceOrderID int32) ([]MaintenanceOrderAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderAttachments, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderAttachment
	for rows.Next() {
		var i MaintenanceOrderAttachment
		if err := rows.Scan(
			&i.MaintenanceOrderAttachmentID,
			&i.MaintenanceOrderID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderItems = `-- name: ListMaintenanceOrderItems :many
SELECT maintenance_order_item_id, maintenance_order_id, name, item_code, quantity, created_at, updated_at, deleted_at FROM maintenance_order_items WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListMaintenanceOrderItems(ctx context.Context, maintenanceOrderID int32) ([]MaintenanceOrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderItems, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderItem
	for rows.Next() {
		var i MaintenanceOrderItem
		if err := rows.Scan(
			&i.MaintenanceOrderItemID,
			&i.MaintenanceOrderID,
			&i.Name,
			&i.ItemCode,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderNoteTemplates = `-- name: ListMaintenanceOrderNoteTemplates :many

SELECT maintenance_order_note_template_id, name, description, created_at, updated_at, deleted_at FROM maintenance_order_note_template WHERE deleted_at IS NULL ORDER BY name ASC
`

// ── Note templates ────────────────────────────────────────────────────────────
func (q *Queries) ListMaintenanceOrderNoteTemplates(ctx context.Context) ([]MaintenanceOrderNoteTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderNoteTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderNoteTemplate
	for rows.Next() {
		var i MaintenanceOrderNoteTemplate
		if err := rows.Scan(
			&i.MaintenanceOrderNoteTemplateID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderPriorities = `-- name: ListMaintenanceOrderPriorities :many

SELECT maintenance_order_priorities_id, name, background_color, border_color, text_color, sort_index FROM maintenance_order_priorities ORDER BY sort_index ASC
`

// ── Priorities ────────────────────────────────────────────────────────────────
func (q *Queries) ListMaintenanceOrderPriorities(ctx context.Context) ([]MaintenanceOrderPriority, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderPriority
	for rows.Next() {
		var i MaintenanceOrderPriority
		if err := rows.Scan(
			&i.MaintenanceOrderPrioritiesID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderReasons = `-- name: ListMaintenanceOrderReasons :many

SELECT maintenance_order_reason_id, name, created_at, updated_at, deleted_at FROM maintenance_order_reason WHERE deleted_at IS NULL ORDER BY name ASC
`

// ── Reasons ───────────────────────────────────────────────────────────────────
func (q *Queries) ListMaintenanceOrderReasons(ctx context.Context) ([]MaintenanceOrderReason, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderReason
	for rows.Next() {
		var i MaintenanceOrderReason
		if err := rows.Scan(
			&i.MaintenanceOrderReasonID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderResolutionItems = `-- name: ListMaintenanceOrderResolutionItems :many
SELECT maintenance_order_resolution_item_id, maintenance_order_id, name, item_code, quantity, created_at, updated_at, deleted_at FROM maintenance_order_resolution_items WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListMaintenanceOrderResolutionItems(ctx context.Context, maintenanceOrderID int32) ([]MaintenanceOrderResolutionItem, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderResolutionItems, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderResolutionItem
	for rows.Next() {
		var i MaintenanceOrderResolutionItem
		if err := rows.Scan(
			&i.MaintenanceOrderResolutionItemID,
			&i.MaintenanceOrderID,
			&i.Name,
			&i.ItemCode,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderScheduleDates = `-- name: ListMaintenanceOrderScheduleDates :many
SELECT maintenance_order_schedule_date_id, maintenance_order_id, date, created_at, updated_at, deleted_at FROM maintenance_order_schedule_date
WHERE maintenance_order_id = ? AND deleted_at IS NULL
ORDER BY date ASC
`

func (q *Queries) ListMaintenanceOrderScheduleDates(ctx context.Context, maintenanceOrderID int32) ([]MaintenanceOrderScheduleDate, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderScheduleDates, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderScheduleDate
	for rows.Next() {
		var i MaintenanceOrderScheduleDate
		if err := rows.Scan(
			&i.MaintenanceOrderScheduleDateID,
			&i.MaintenanceOrderID,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderStatuses = `-- name: ListMaintenanceOrderStatuses :many

SELECT maintenance_order_status_id, name, background_color, border_color, text_color, sort_index, is_closed, is_default FROM maintenance_order_status ORDER BY sort_index ASC
`

// ── Status ────────────────────────────────────────────────────────────────────
func (q *Queries) ListMaintenanceOrderStatuses(ctx context.Context) ([]MaintenanceOrderStatus, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderStatus
	for rows.Next() {
		var i MaintenanceOrderStatus
		if err := rows.Scan(
			&i.MaintenanceOrderStatusID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
			&i.IsClosed,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderTimeEntries = `-- name: ListMaintenanceOrderTimeEntries :many
SELECT
    te.maintenance_order_time_entry_id,
    te.maintenance_order_id,
    te.type_id,
    te.started_at,
    te.ended_at,
    te.created_at,
    te.updated_at,
    te.deleted_at,
    t.name  AS type_name,
    t.color AS type_color
FROM maintenance_order_time_entry te
JOIN maintenance_order_time_entry_type t ON t.maintenance_order_time_entry_type_id = te.type_id
WHERE te.maintenance_order_id = ? AND te.deleted_at IS NULL
`

type ListMaintenanceOrderTimeEntriesRow struct {
	MaintenanceOrderTimeEntryID int32          `json:"maintenance_order_time_entry_id"`
	MaintenanceOrderID          int32          `json:"maintenance_order_id"`
	TypeID                      int32          `json:"type_id"`
	StartedAt                   time.Time      `json:"started_at"`
	EndedAt                     sql.NullTime   `json:"ended_at"`
	CreatedAt                   time.Time      `json:"created_at"`
	UpdatedAt                   time.Time      `json:"updated_at"`
	DeletedAt                   sql.NullTime   `json:"deleted_at"`
	TypeName                    string         `json:"type_name"`
	TypeColor                   sql.NullString `json:"type_color"`
}

func (q *Queries) ListMaintenanceOrderTimeEntries(ctx context.Context, maintenanceOrderID int32) ([]ListMaintenanceOrderTimeEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderTimeEntries, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceOrderTimeEntriesRow
	for rows.Next() {
		var i ListMaintenanceOrderTimeEntriesRow
		if err := rows.Scan(
			&i.MaintenanceOrderTimeEntryID,
			&i.MaintenanceOrderID,
			&i.TypeID,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TypeName,
			&i.TypeColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceOrderTimeEntryTypes = `-- name: ListMaintenanceOrderTimeEntryTypes :many

SELECT maintenance_order_time_entry_type_id, name, color FROM maintenance_order_time_entry_type ORDER BY name ASC
`

// ── Time entry types ──────────────────────────────────────────────────────────
func (q *Queries) ListMaintenanceOrderTimeEntryTypes(ctx context.Context) ([]MaintenanceOrderTimeEntryType, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceOrderTimeEntryTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderTimeEntryType
	for rows.Next() {
		var i MaintenanceOrderTimeEntryType
		if err := rows.Scan(&i.MaintenanceOrderTimeEntryTypeID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderChecklists = `-- name: ListOrderChecklists :many

SELECT maintenance_order_checklist_id, maintenance_order_id, template_id, completed_at, created_at, updated_at, deleted_at FROM maintenance_order_checklist
WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

// ── Order checklists ──────────────────────────────────────────────────────────
func (q *Queries) ListOrderChecklists(ctx context.Context, maintenanceOrderID int32) ([]MaintenanceOrderChecklist, error) {
	rows, err := q.db.QueryContext(ctx, listOrderChecklists, maintenanceOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderChecklist
	for rows.Next() {
		var i MaintenanceOrderChecklist
		if err := rows.Scan(
			&i.MaintenanceOrderChecklistID,
			&i.MaintenanceOrderID,
			&i.TemplateID,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleDateTechnicians = `-- name: ListScheduleDateTechnicians :many
SELECT maintenance_order_schedule_date_technician_id, maintenance_order_schedule_date_id, technician_id, technician_name, created_at, updated_at, deleted_at FROM maintenance_order_schedule_date_technician
WHERE maintenance_order_schedule_date_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListScheduleDateTechnicians(ctx context.Context, maintenanceOrderScheduleDateID int32) ([]MaintenanceOrderScheduleDateTechnician, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleDateTechnicians, maintenanceOrderScheduleDateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceOrderScheduleDateTechnician
	for rows.Next() {
		var i MaintenanceOrderScheduleDateTechnician
		if err := rows.Scan(
			&i.MaintenanceOrderScheduleDateTechnicianID,
			&i.MaintenanceOrderScheduleDateID,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChecklistItem = `-- name: SoftDeleteChecklistItem :exec
UPDATE maintenance_order_checklist_item SET deleted_at = NOW()
WHERE maintenance_order_checklist_item_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteChecklistItem(ctx context.Context, maintenanceOrderChecklistItemID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteChecklistItem, maintenanceOrderChecklistItemID)
	return err
}

const softDeleteChecklistTemplate = `-- name: SoftDeleteChecklistTemplate :exec
UPDATE maintenance_order_checklist_template SET deleted_at = NOW()
WHERE maintenance_order_checklist_template_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteChecklistTemplate(ctx context.Context, maintenanceOrderChecklistTemplateID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteChecklistTemplate, maintenanceOrderChecklistTemplateID)
	return err
}

const softDeleteMaintenanceOrder = `-- name: SoftDeleteMaintenanceOrder :execrows
UPDATE maintenance_order SET deleted_at = NOW() WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaintenanceOrder(ctx context.Context, maintenanceOrderID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteMaintenanceOrder, maintenanceOrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteMaintenanceOrderAttachment = `-- name: SoftDeleteMaintenanceOrderAttachment :exec
UPDATE maintenance_order_attachment SET deleted_at = NOW()
WHERE maintenance_order_attachment_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaintenanceOrderAttachment(ctx context.Context, maintenanceOrderAttachmentID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteMaintenanceOrderAttachment, maintenanceOrderAttachmentID)
	return err
}

const softDeleteMaintenanceOrderNoteTemplate = `-- name: SoftDeleteMaintenanceOrderNoteTemplate :exec
UPDATE maintenance_order_note_template SET deleted_at = NOW()
WHERE maintenance_order_note_template_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaintenanceOrderNoteTemplate(ctx context.Context, maintenanceOrderNoteTemplateID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteMaintenanceOrderNoteTemplate, maintenanceOrderNoteTemplateID)
	return err
}

const softDeleteMaintenanceOrderReason = `-- name: SoftDeleteMaintenanceOrderReason :exec
UPDATE maintenance_order_reason SET deleted_at = NOW() WHERE maintenance_order_reason_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaintenanceOrderReason(ctx context.Context, maintenanceOrderReasonID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteMaintenanceOrderReason, maintenanceOrderReasonID)
	return err
}

const softDeleteOrderChecklist = `-- name: SoftDeleteOrderChecklist :exec
UPDATE maintenance_order_checklist SET deleted_at = NOW()
WHERE maintenance_order_checklist_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrderChecklist(ctx context.Context, maintenanceOrderChecklistID int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteOrderChecklist, maintenanceOrderChecklistID)
	return err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :exec
UPDATE maintenance_order_checklist_item
SET section = ?, label = ?, type = ?, options = ?, metadata = ?, required = ?, sort_order = ?,
    parent_item_id = ?, show_when_values = ?
WHERE maintenance_order_checklist_item_id = ? AND deleted_at IS NULL
`

type UpdateChecklistItemParams struct {
	Section                         sql.NullString                    `json:"section"`
	Label                           string                            `json:"label"`
	Type                            MaintenanceOrderChecklistItemType `json:"type"`
	Options                         sql.NullString                    `json:"options"`
	Metadata                        sql.NullString                    `json:"metadata"`
	Required                        bool                              `json:"required"`
	SortOrder                       int32                             `json:"sort_order"`
	ParentItemID                    sql.NullInt32                     `json:"parent_item_id"`
	ShowWhenValues                  sql.NullString                    `json:"show_when_values"`
	MaintenanceOrderChecklistItemID int32                             `json:"maintenance_order_checklist_item_id"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklistItem,
		arg.Section,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Metadata,
		arg.Required,
		arg.SortOrder,
		arg.ParentItemID,
		arg.ShowWhenValues,
		arg.MaintenanceOrderChecklistItemID,
	)
	return err
}

const updateChecklistTemplate = `-- name: UpdateChecklistTemplate :exec
UPDATE maintenance_order_checklist_template
SET name = ?, reason_id = ?, active = ?
WHERE maintenance_order_checklist_template_id = ? AND deleted_at IS NULL
`

type UpdateChecklistTemplateParams struct {
	Name                                string        `json:"name"`
	ReasonID                            sql.NullInt32 `json:"reason_id"`
	Active                              bool          `json:"active"`
	MaintenanceOrderChecklistTemplateID int32         `json:"maintenance_order_checklist_template_id"`
}

func (q *Queries) UpdateChecklistTemplate(ctx context.Context, arg UpdateChecklistTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklistTemplate,
		arg.Name,
		arg.ReasonID,
		arg.Active,
		arg.MaintenanceOrderChecklistTemplateID,
	)
	return err
}

const updateMaintenanceOrderCapturedAt = `-- name: UpdateMaintenanceOrderCapturedAt :exec
UPDATE maintenance_order SET captured_at = ? WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

type UpdateMaintenanceOrderCapturedAtParams struct {
	CapturedAt         sql.NullTime `json:"captured_at"`
	MaintenanceOrderID int32        `json:"maintenance_order_id"`
}

func (q *Queries) UpdateMaintenanceOrderCapturedAt(ctx context.Context, arg UpdateMaintenanceOrderCapturedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderCapturedAt, arg.CapturedAt, arg.MaintenanceOrderID)
	return err
}

const updateMaintenanceOrderNoteTemplate = `-- name: UpdateMaintenanceOrderNoteTemplate :exec
UPDATE maintenance_order_note_template
SET name = ?, description = ?
WHERE maintenance_order_note_template_id = ? AND deleted_at IS NULL
`

type UpdateMaintenanceOrderNoteTemplateParams struct {
	Name                           string `json:"name"`
	Description                    string `json:"description"`
	MaintenanceOrderNoteTemplateID int32  `json:"maintenance_order_note_template_id"`
}

func (q *Queries) UpdateMaintenanceOrderNoteTemplate(ctx context.Context, arg UpdateMaintenanceOrderNoteTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderNoteTemplate, arg.Name, arg.Description, arg.MaintenanceOrderNoteTemplateID)
	return err
}

const updateMaintenanceOrderPriority = `-- name: UpdateMaintenanceOrderPriority :exec
UPDATE maintenance_order_priorities
SET name = ?, background_color = ?, border_color = ?, text_color = ?, sort_index = ?
WHERE maintenance_order_priorities_id = ?
`

type UpdateMaintenanceOrderPriorityParams struct {
	Name                         string `json:"name"`
	BackgroundColor              string `json:"background_color"`
	BorderColor                  string `json:"border_color"`
	TextColor                    string `json:"text_color"`
	SortIndex                    int32  `json:"sort_index"`
	MaintenanceOrderPrioritiesID int32  `json:"maintenance_order_priorities_id"`
}

func (q *Queries) UpdateMaintenanceOrderPriority(ctx context.Context, arg UpdateMaintenanceOrderPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.MaintenanceOrderPrioritiesID,
	)
	return err
}

const updateMaintenanceOrderReason = `-- name: UpdateMaintenanceOrderReason :exec
UPDATE maintenance_order_reason SET name = ? WHERE maintenance_order_reason_id = ? AND deleted_at IS NULL
`

type UpdateMaintenanceOrderReasonParams struct {
	Name                     string `json:"name"`
	MaintenanceOrderReasonID int32  `json:"maintenance_order_reason_id"`
}

func (q *Queries) UpdateMaintenanceOrderReason(ctx context.Context, arg UpdateMaintenanceOrderReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderReason, arg.Name, arg.MaintenanceOrderReasonID)
	return err
}

const updateMaintenanceOrderSignature = `-- name: UpdateMaintenanceOrderSignature :exec
UPDATE maintenance_order SET client_signature = ? WHERE maintenance_order_id = ? AND deleted_at IS NULL
`

type UpdateMaintenanceOrderSignatureParams struct {
	ClientSignature    sql.NullString `json:"client_signature"`
	MaintenanceOrderID int32          `json:"maintenance_order_id"`
}

func (q *Queries) UpdateMaintenanceOrderSignature(ctx context.Context, arg UpdateMaintenanceOrderSignatureParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderSignature, arg.ClientSignature, arg.MaintenanceOrderID)
	return err
}

const updateMaintenanceOrderStatus = `-- name: UpdateMaintenanceOrderStatus :exec
UPDATE maintenance_order_status
SET name = ?, background_color = ?, border_color = ?, text_color = ?, sort_index = ?, is_closed = ?, is_default = ?
WHERE maintenance_order_status_id = ?
`

type UpdateMaintenanceOrderStatusParams struct {
	Name                     string `json:"name"`
	BackgroundColor          string `json:"background_color"`
	BorderColor              string `json:"border_color"`
	TextColor                string `json:"text_color"`
	SortIndex                int32  `json:"sort_index"`
	IsClosed                 bool   `json:"is_closed"`
	IsDefault                bool   `json:"is_default"`
	MaintenanceOrderStatusID int32  `json:"maintenance_order_status_id"`
}

func (q *Queries) UpdateMaintenanceOrderStatus(ctx context.Context, arg UpdateMaintenanceOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.MaintenanceOrderStatusID,
	)
	return err
}

const updateMaintenanceOrderTimeEntryType = `-- name: UpdateMaintenanceOrderTimeEntryType :exec
UPDATE maintenance_order_time_entry_type SET name = ?, color = ?
WHERE maintenance_order_time_entry_type_id = ?
`

type UpdateMaintenanceOrderTimeEntryTypeParams struct {
	Name                            string         `json:"name"`
	Color                           sql.NullString `json:"color"`
	MaintenanceOrderTimeEntryTypeID int32          `json:"maintenance_order_time_entry_type_id"`
}

func (q *Queries) UpdateMaintenanceOrderTimeEntryType(ctx context.Context, arg UpdateMaintenanceOrderTimeEntryTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceOrderTimeEntryType, arg.Name, arg.Color, arg.MaintenanceOrderTimeEntryTypeID)
	return err
}

const updateOrderChecklistCompletedAt = `-- name: UpdateOrderChecklistCompletedAt :exec
UPDATE maintenance_order_checklist SET completed_at = ?
WHERE maintenance_order_checklist_id = ? AND deleted_at IS NULL
`

type UpdateOrderChecklistCompletedAtParams struct {
	CompletedAt                 sql.NullTime `json:"completed_at"`
	MaintenanceOrderChecklistID int32        `json:"maintenance_order_checklist_id"`
}

func (q *Queries) UpdateOrderChecklistCompletedAt(ctx context.Context, arg UpdateOrderChecklistCompletedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderChecklistCompletedAt, arg.CompletedAt, arg.MaintenanceOrderChecklistID)
	return err
}
