// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AccessLevelsModulesDataScope string

const (
	AccessLevelsModulesDataScopeOWN         AccessLevelsModulesDataScope = "OWN"
	AccessLevelsModulesDataScopeRESPONSIBLE AccessLevelsModulesDataScope = "RESPONSIBLE"
	AccessLevelsModulesDataScopeGROUP       AccessLevelsModulesDataScope = "GROUP"
	AccessLevelsModulesDataScopeALL         AccessLevelsModulesDataScope = "ALL"
)

func (e *AccessLevelsModulesDataScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessLevelsModulesDataScope(s)
	case string:
		*e = AccessLevelsModulesDataScope(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessLevelsModulesDataScope: %T", src)
	}
	return nil
}

type NullAccessLevelsModulesDataScope struct {
	AccessLevelsModulesDataScope AccessLevelsModulesDataScope `json:"access_levels_modules_data_scope"`
	Valid                        bool                         `json:"valid"` // Valid is true if AccessLevelsModulesDataScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessLevelsModulesDataScope) Scan(value interface{}) error {
	if value == nil {
		ns.AccessLevelsModulesDataScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessLevelsModulesDataScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessLevelsModulesDataScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessLevelsModulesDataScope), nil
}

type MaintenanceOrderChecklistItemType string

const (
	MaintenanceOrderChecklistItemTypeSingleChoice MaintenanceOrderChecklistItemType = "single_choice"
	MaintenanceOrderChecklistItemTypeMultiChoice  MaintenanceOrderChecklistItemType = "multi_choice"
	MaintenanceOrderChecklistItemTypeText         MaintenanceOrderChecklistItemType = "text"
	MaintenanceOrderChecklistItemTypeTableRow     MaintenanceOrderChecklistItemType = "table_row"
	MaintenanceOrderChecklistItemTypeSapItem      MaintenanceOrderChecklistItemType = "sap_item"
)

func (e *MaintenanceOrderChecklistItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceOrderChecklistItemType(s)
	case string:
		*e = MaintenanceOrderChecklistItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceOrderChecklistItemType: %T", src)
	}
	return nil
}

type NullMaintenanceOrderChecklistItemType struct {
	MaintenanceOrderChecklistItemType MaintenanceOrderChecklistItemType `json:"maintenance_order_checklist_item_type"`
	Valid                             bool                              `json:"valid"` // Valid is true if MaintenanceOrderChecklistItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceOrderChecklistItemType) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceOrderChecklistItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceOrderChecklistItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceOrderChecklistItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceOrderChecklistItemType), nil
}

type MenuRequiredScope string

const (
	MenuRequiredScopeOWN         MenuRequiredScope = "OWN"
	MenuRequiredScopeRESPONSIBLE MenuRequiredScope = "RESPONSIBLE"
	MenuRequiredScopeGROUP       MenuRequiredScope = "GROUP"
	MenuRequiredScopeALL         MenuRequiredScope = "ALL"
)

func (e *MenuRequiredScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MenuRequiredScope(s)
	case string:
		*e = MenuRequiredScope(s)
	default:
		return fmt.Errorf("unsupported scan type for MenuRequiredScope: %T", src)
	}
	return nil
}

type NullMenuRequiredScope struct {
	MenuRequiredScope MenuRequiredScope `json:"menu_required_scope"`
	Valid             bool              `json:"valid"` // Valid is true if MenuRequiredScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMenuRequiredScope) Scan(value interface{}) error {
	if value == nil {
		ns.MenuRequiredScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MenuRequiredScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMenuRequiredScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MenuRequiredScope), nil
}

type AccessLevel struct {
	AccessLevelID int32  `json:"access_level_id"`
	Name          string `json:"name"`
}

type AccessLevelsModule struct {
	AccessLevelModuleID int32        `json:"access_level_module_id"`
	AccessLevelID       int32        `json:"access_level_id"`
	ModuleID            int32        `json:"module_id"`
	DataScope           string       `json:"data_scope"`
	Permission          int32        `json:"permission"`
	CanBeAssigned       bool         `json:"can_be_assigned"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
	DeletedAt           sql.NullTime `json:"deleted_at"`
}

type Group struct {
	GroupID   int32         `json:"group_id"`
	Name      string        `json:"name"`
	ParentID  sql.NullInt32 `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

type GroupsAccessLevel struct {
	GroupAccessLevelID int32 `json:"group_access_level_id"`
	GroupID            int32 `json:"group_id"`
	AccessLevelID      int32 `json:"access_level_id"`
}

type MaintenanceOrder struct {
	MaintenanceOrderID int32          `json:"maintenance_order_id"`
	RequesterID        int32          `json:"requester_id"`
	RequesterName      string         `json:"requester_name"`
	SalespersonName    sql.NullString `json:"salesperson_name"`
	ClientCode         string         `json:"client_code"`
	ClientName         string         `json:"client_name"`
	ClientAliasName    string         `json:"client_alias_name"`
	ContactType        sql.NullString `json:"contact_type"`
	ContactName        sql.NullString `json:"contact_name"`
	ContactPhone       sql.NullString `json:"contact_phone"`
	ContactMobile      sql.NullString `json:"contact_mobile"`
	ContactEmail       sql.NullString `json:"contact_email"`
	AddressName        sql.NullString `json:"address_name"`
	AddressType        sql.NullString `json:"address_type"`
	TypeOfAddress      sql.NullString `json:"type_of_address"`
	Street             sql.NullString `json:"street"`
	StreetNo           sql.NullString `json:"street_no"`
	Block              sql.NullString `json:"block"`
	City               sql.NullString `json:"city"`
	County             sql.NullString `json:"county"`
	State              sql.NullString `json:"state"`
	Country            sql.NullString `json:"country"`
	ZipCode            sql.NullString `json:"zip_code"`
	BuildingFloorRoom  sql.NullString `json:"building_floor_room"`
	StatusID           int32          `json:"status_id"`
	PriorityID         int32          `json:"priority_id"`
	ReasonID           int32          `json:"reason_id"`
	Description        string         `json:"description"`
	CapturedAt         sql.NullTime   `json:"captured_at"`
	Resolution         sql.NullString `json:"resolution"`
	MotivoResolution   sql.NullString `json:"motivo_resolution"`
	ClientSignature    sql.NullString `json:"client_signature"`
	ClosedAt           sql.NullTime   `json:"closed_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type MaintenanceOrderAttachment struct {
	MaintenanceOrderAttachmentID int32        `json:"maintenance_order_attachment_id"`
	MaintenanceOrderID           int32        `json:"maintenance_order_id"`
	FileName                     string       `json:"file_name"`
	FilePath                     string       `json:"file_path"`
	FileSize                     int32        `json:"file_size"`
	CreatedAt                    time.Time    `json:"created_at"`
	UpdatedAt                    time.Time    `json:"updated_at"`
	DeletedAt                    sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderChecklist struct {
	MaintenanceOrderChecklistID int32        `json:"maintenance_order_checklist_id"`
	MaintenanceOrderID          int32        `json:"maintenance_order_id"`
	TemplateID                  int32        `json:"template_id"`
	CompletedAt                 sql.NullTime `json:"completed_at"`
	CreatedAt                   time.Time    `json:"created_at"`
	UpdatedAt                   time.Time    `json:"updated_at"`
	DeletedAt                   sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderChecklistAnswer struct {
	MaintenanceOrderChecklistAnswerID int32          `json:"maintenance_order_checklist_answer_id"`
	ChecklistID                       int32          `json:"checklist_id"`
	ItemID                            int32          `json:"item_id"`
	Value                             sql.NullString `json:"value"`
	CreatedAt                         time.Time      `json:"created_at"`
	UpdatedAt                         time.Time      `json:"updated_at"`
	DeletedAt                         sql.NullTime   `json:"deleted_at"`
}

type MaintenanceOrderChecklistItem struct {
	MaintenanceOrderChecklistItemID int32                             `json:"maintenance_order_checklist_item_id"`
	TemplateID                      int32                             `json:"template_id"`
	Section                         sql.NullString                    `json:"section"`
	Label                           string                            `json:"label"`
	Type                            MaintenanceOrderChecklistItemType `json:"type"`
	Options                         sql.NullString                    `json:"options"`
	Metadata                        sql.NullString                    `json:"metadata"`
	Required                        bool                              `json:"required"`
	SortOrder                       int32                             `json:"sort_order"`
	ParentItemID                    sql.NullInt32                     `json:"parent_item_id"`
	ShowWhenValues                  sql.NullString                    `json:"show_when_values"`
	CreatedAt                       time.Time                         `json:"created_at"`
	UpdatedAt                       time.Time                         `json:"updated_at"`
	DeletedAt                       sql.NullTime                      `json:"deleted_at"`
}

type MaintenanceOrderChecklistTemplate struct {
	MaintenanceOrderChecklistTemplateID int32         `json:"maintenance_order_checklist_template_id"`
	Name                                string        `json:"name"`
	ReasonID                            sql.NullInt32 `json:"reason_id"`
	Active                              bool          `json:"active"`
	CreatedAt                           time.Time     `json:"created_at"`
	UpdatedAt                           time.Time     `json:"updated_at"`
	DeletedAt                           sql.NullTime  `json:"deleted_at"`
}

type MaintenanceOrderConfig struct {
	MaintenanceOrderConfigID int32 `json:"maintenance_order_config_id"`
}

type MaintenanceOrderConfigAssignableAccessLevel struct {
	MaintenanceOrderConfigID int32 `json:"maintenance_order_config_id"`
	AccessLevelID            int32 `json:"access_level_id"`
}

type MaintenanceOrderItem struct {
	MaintenanceOrderItemID int32        `json:"maintenance_order_item_id"`
	MaintenanceOrderID     int32        `json:"maintenance_order_id"`
	Name                   string       `json:"name"`
	ItemCode               string       `json:"item_code"`
	Quantity               int32        `json:"quantity"`
	CreatedAt              time.Time    `json:"created_at"`
	UpdatedAt              time.Time    `json:"updated_at"`
	DeletedAt              sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderNoteTemplate struct {
	MaintenanceOrderNoteTemplateID int32        `json:"maintenance_order_note_template_id"`
	Name                           string       `json:"name"`
	Description                    string       `json:"description"`
	CreatedAt                      time.Time    `json:"created_at"`
	UpdatedAt                      time.Time    `json:"updated_at"`
	DeletedAt                      sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderPriority struct {
	MaintenanceOrderPrioritiesID int32  `json:"maintenance_order_priorities_id"`
	Name                         string `json:"name"`
	BackgroundColor              string `json:"background_color"`
	BorderColor                  string `json:"border_color"`
	TextColor                    string `json:"text_color"`
	SortIndex                    int32  `json:"sort_index"`
}

type MaintenanceOrderReason struct {
	MaintenanceOrderReasonID int32        `json:"maintenance_order_reason_id"`
	Name                     string       `json:"name"`
	CreatedAt                time.Time    `json:"created_at"`
	UpdatedAt                time.Time    `json:"updated_at"`
	DeletedAt                sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderResolutionItem struct {
	MaintenanceOrderResolutionItemID int32        `json:"maintenance_order_resolution_item_id"`
	MaintenanceOrderID               int32        `json:"maintenance_order_id"`
	Name                             string       `json:"name"`
	ItemCode                         string       `json:"item_code"`
	Quantity                         int32        `json:"quantity"`
	CreatedAt                        time.Time    `json:"created_at"`
	UpdatedAt                        time.Time    `json:"updated_at"`
	DeletedAt                        sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderScheduleDate struct {
	MaintenanceOrderScheduleDateID int32        `json:"maintenance_order_schedule_date_id"`
	MaintenanceOrderID             int32        `json:"maintenance_order_id"`
	Date                           time.Time    `json:"date"`
	CreatedAt                      time.Time    `json:"created_at"`
	UpdatedAt                      time.Time    `json:"updated_at"`
	DeletedAt                      sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderScheduleDateTechnician struct {
	MaintenanceOrderScheduleDateTechnicianID int32        `json:"maintenance_order_schedule_date_technician_id"`
	MaintenanceOrderScheduleDateID           int32        `json:"maintenance_order_schedule_date_id"`
	TechnicianID                             int32        `json:"technician_id"`
	TechnicianName                           string       `json:"technician_name"`
	CreatedAt                                time.Time    `json:"created_at"`
	UpdatedAt                                time.Time    `json:"updated_at"`
	DeletedAt                                sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderStatus struct {
	MaintenanceOrderStatusID int32  `json:"maintenance_order_status_id"`
	Name                     string `json:"name"`
	BackgroundColor          string `json:"background_color"`
	BorderColor              string `json:"border_color"`
	TextColor                string `json:"text_color"`
	SortIndex                int32  `json:"sort_index"`
	IsClosed                 bool   `json:"is_closed"`
	IsDefault                bool   `json:"is_default"`
}

type MaintenanceOrderTimeEntry struct {
	MaintenanceOrderTimeEntryID int32        `json:"maintenance_order_time_entry_id"`
	MaintenanceOrderID          int32        `json:"maintenance_order_id"`
	TypeID                      int32        `json:"type_id"`
	StartedAt                   time.Time    `json:"started_at"`
	EndedAt                     sql.NullTime `json:"ended_at"`
	CreatedAt                   time.Time    `json:"created_at"`
	UpdatedAt                   time.Time    `json:"updated_at"`
	DeletedAt                   sql.NullTime `json:"deleted_at"`
}

type MaintenanceOrderTimeEntryType struct {
	MaintenanceOrderTimeEntryTypeID int32          `json:"maintenance_order_time_entry_type_id"`
	Name                            string         `json:"name"`
	Color                           sql.NullString `json:"color"`
}

type Menu struct {
	MenuID        int32          `json:"menu_id"`
	Name          string         `json:"name"`
	SortIndex     int32          `json:"sort_index"`
	Paths         string         `json:"paths"`
	ModuleID      int32          `json:"module_id"`
	ParentID      sql.NullInt32  `json:"parent_id"`
	RequiredScope sql.NullString `json:"required_scope"`
}

type Module struct {
	ModuleID int32  `json:"module_id"`
	Name     string `json:"name"`
}

type User struct {
	UserID    int32          `json:"user_id"`
	Name      string         `json:"name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type UsersAccessLevel struct {
	UserAccessLevelID int32 `json:"user_access_level_id"`
	UserID            int32 `json:"user_id"`
	AccessLevelID     int32 `json:"access_level_id"`
}

type UsersGroup struct {
	UserGroupID int32 `json:"user_group_id"`
	UserID      int32 `json:"user_id"`
	GroupID     int32 `json:"group_id"`
}
