// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: purchasing.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignPurchasingOrder = `-- name: AssignPurchasingOrder :exec
UPDATE purchasing_order SET assigned_to_id=?, assigned_to_name=?
WHERE purchasing_order_id=? AND deleted_at IS NULL
`

type AssignPurchasingOrderParams struct {
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	PurchasingOrderID int32          `json:"purchasing_order_id"`
}

func (q *Queries) AssignPurchasingOrder(ctx context.Context, arg AssignPurchasingOrderParams) error {
	_, err := q.db.ExecContext(ctx, assignPurchasingOrder, arg.AssignedToID, arg.AssignedToName, arg.PurchasingOrderID)
	return err
}

const createPurchasingOrder = `-- name: CreatePurchasingOrder :execresult

INSERT INTO purchasing_order (requester_id, requester_name, assigned_to_id, assigned_to_name,
    salesperson_name, client_code, client_name, client_alias_name,
    status_id, priority_id, reason_id, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePurchasingOrderParams struct {
	RequesterID     int32          `json:"requester_id"`
	RequesterName   string         `json:"requester_name"`
	AssignedToID    sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName  sql.NullString `json:"assigned_to_name"`
	SalespersonName sql.NullString `json:"salesperson_name"`
	ClientCode      string         `json:"client_code"`
	ClientName      string         `json:"client_name"`
	ClientAliasName string         `json:"client_alias_name"`
	StatusID        int32          `json:"status_id"`
	PriorityID      int32          `json:"priority_id"`
	ReasonID        int32          `json:"reason_id"`
	Description     string         `json:"description"`
}

// ── Purchasing Orders ─────────────────────────────────────────────────────────
func (q *Queries) CreatePurchasingOrder(ctx context.Context, arg CreatePurchasingOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPurchasingOrder,
		arg.RequesterID,
		arg.RequesterName,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
	)
}

const createPurchasingOrderAttachment = `-- name: CreatePurchasingOrderAttachment :execresult

INSERT INTO purchasing_order_attachment (purchasing_order_id, file_name, file_path, file_size)
VALUES (?, ?, ?, ?)
`

type CreatePurchasingOrderAttachmentParams struct {
	PurchasingOrderID int32  `json:"purchasing_order_id"`
	FileName          string `json:"file_name"`
	FilePath          string `json:"file_path"`
	FileSize          int32  `json:"file_size"`
}

// ── Purchasing Attachments ────────────────────────────────────────────────────
func (q *Queries) CreatePurchasingOrderAttachment(ctx context.Context, arg CreatePurchasingOrderAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPurchasingOrderAttachment,
		arg.PurchasingOrderID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
	)
}

const createPurchasingOrderPriority = `-- name: CreatePurchasingOrderPriority :execresult
INSERT INTO purchasing_order_priorities (name, background_color, border_color, text_color, sort_index)
VALUES (?, ?, ?, ?, ?)
`

type CreatePurchasingOrderPriorityParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
}

func (q *Queries) CreatePurchasingOrderPriority(ctx context.Context, arg CreatePurchasingOrderPriorityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPurchasingOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
	)
}

const createPurchasingOrderReason = `-- name: CreatePurchasingOrderReason :execresult
INSERT INTO purchasing_order_reason (name, initial_status_id) VALUES (?, ?)
`

type CreatePurchasingOrderReasonParams struct {
	Name            string `json:"name"`
	InitialStatusID int32  `json:"initial_status_id"`
}

func (q *Queries) CreatePurchasingOrderReason(ctx context.Context, arg CreatePurchasingOrderReasonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPurchasingOrderReason, arg.Name, arg.InitialStatusID)
}

const createPurchasingOrderStatus = `-- name: CreatePurchasingOrderStatus :execresult
INSERT INTO purchasing_order_status (name, background_color, border_color, text_color, sort_index,
    is_closed, is_default, is_pending_approval)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePurchasingOrderStatusParams struct {
	Name              string `json:"name"`
	BackgroundColor   string `json:"background_color"`
	BorderColor       string `json:"border_color"`
	TextColor         string `json:"text_color"`
	SortIndex         int32  `json:"sort_index"`
	IsClosed          bool   `json:"is_closed"`
	IsDefault         bool   `json:"is_default"`
	IsPendingApproval bool   `json:"is_pending_approval"`
}

func (q *Queries) CreatePurchasingOrderStatus(ctx context.Context, arg CreatePurchasingOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPurchasingOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.IsPendingApproval,
	)
}

const createPurchasingStatusTransition = `-- name: CreatePurchasingStatusTransition :execresult
INSERT INTO purchasing_order_status_transition (from_status_id, to_status_id, access_level_id)
VALUES (?, ?, ?)
`

type CreatePurchasingStatusTransitionParams struct {
	FromStatusID  sql.NullInt32 `json:"from_status_id"`
	ToStatusID    int32         `json:"to_status_id"`
	AccessLevelID int32         `json:"access_level_id"`
}

func (q *Queries) CreatePurchasingStatusTransition(ctx context.Context, arg CreatePurchasingStatusTransitionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPurchasingStatusTransition, arg.FromStatusID, arg.ToStatusID, arg.AccessLevelID)
}

const deletePurchasingOrder = `-- name: DeletePurchasingOrder :exec
UPDATE purchasing_order SET deleted_at=NOW()
WHERE purchasing_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeletePurchasingOrder(ctx context.Context, purchasingOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deletePurchasingOrder, purchasingOrderID)
	return err
}

const deletePurchasingOrderAttachment = `-- name: DeletePurchasingOrderAttachment :exec
UPDATE purchasing_order_attachment SET deleted_at=NOW()
WHERE purchasing_order_attachment_id=? AND deleted_at IS NULL
`

func (q *Queries) DeletePurchasingOrderAttachment(ctx context.Context, purchasingOrderAttachmentID int32) error {
	_, err := q.db.ExecContext(ctx, deletePurchasingOrderAttachment, purchasingOrderAttachmentID)
	return err
}

const deletePurchasingOrderPriority = `-- name: DeletePurchasingOrderPriority :exec
DELETE FROM purchasing_order_priorities WHERE purchasing_order_priority_id=?
`

func (q *Queries) DeletePurchasingOrderPriority(ctx context.Context, purchasingOrderPriorityID int32) error {
	_, err := q.db.ExecContext(ctx, deletePurchasingOrderPriority, purchasingOrderPriorityID)
	return err
}

const deletePurchasingOrderReason = `-- name: DeletePurchasingOrderReason :exec
UPDATE purchasing_order_reason SET deleted_at=NOW()
WHERE purchasing_order_reason_id=? AND deleted_at IS NULL
`

func (q *Queries) DeletePurchasingOrderReason(ctx context.Context, purchasingOrderReasonID int32) error {
	_, err := q.db.ExecContext(ctx, deletePurchasingOrderReason, purchasingOrderReasonID)
	return err
}

const deletePurchasingOrderStatus = `-- name: DeletePurchasingOrderStatus :exec
DELETE FROM purchasing_order_status WHERE purchasing_order_status_id=?
`

func (q *Queries) DeletePurchasingOrderStatus(ctx context.Context, purchasingOrderStatusID int32) error {
	_, err := q.db.ExecContext(ctx, deletePurchasingOrderStatus, purchasingOrderStatusID)
	return err
}

const deletePurchasingStatusTransition = `-- name: DeletePurchasingStatusTransition :exec
DELETE FROM purchasing_order_status_transition WHERE id=?
`

func (q *Queries) DeletePurchasingStatusTransition(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePurchasingStatusTransition, id)
	return err
}

const getPurchasingOrderAttachmentByID = `-- name: GetPurchasingOrderAttachmentByID :one
SELECT purchasing_order_attachment_id, purchasing_order_id, file_name, file_path, file_size, created_at
FROM purchasing_order_attachment
WHERE purchasing_order_attachment_id=? AND deleted_at IS NULL
`

type GetPurchasingOrderAttachmentByIDRow struct {
	PurchasingOrderAttachmentID int32     `json:"purchasing_order_attachment_id"`
	PurchasingOrderID           int32     `json:"purchasing_order_id"`
	FileName                    string    `json:"file_name"`
	FilePath                    string    `json:"file_path"`
	FileSize                    int32     `json:"file_size"`
	CreatedAt                   time.Time `json:"created_at"`
}

func (q *Queries) GetPurchasingOrderAttachmentByID(ctx context.Context, purchasingOrderAttachmentID int32) (GetPurchasingOrderAttachmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPurchasingOrderAttachmentByID, purchasingOrderAttachmentID)
	var i GetPurchasingOrderAttachmentByIDRow
	err := row.Scan(
		&i.PurchasingOrderAttachmentID,
		&i.PurchasingOrderID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchasingOrderByID = `-- name: GetPurchasingOrderByID :one
SELECT o.purchasing_order_id, o.requester_id, o.requester_name, o.assigned_to_id, o.assigned_to_name,
       o.salesperson_name, o.client_code, o.client_name, o.client_alias_name,
       o.status_id, o.priority_id, o.reason_id, o.description,
       o.captured_at, o.resolution, o.closed_at, o.created_at, o.updated_at,
       s.name AS status_name, s.background_color AS status_bg, s.border_color AS status_border,
       s.text_color AS status_text, s.is_closed AS status_is_closed,
       p.name AS priority_name, p.background_color AS priority_bg,
       r.name AS reason_name
FROM purchasing_order o
JOIN purchasing_order_status s     ON s.purchasing_order_status_id   = o.status_id
JOIN purchasing_order_priorities p ON p.purchasing_order_priority_id = o.priority_id
JOIN purchasing_order_reason r     ON r.purchasing_order_reason_id   = o.reason_id
WHERE o.purchasing_order_id=? AND o.deleted_at IS NULL
`

type GetPurchasingOrderByIDRow struct {
	PurchasingOrderID int32          `json:"purchasing_order_id"`
	RequesterID       int32          `json:"requester_id"`
	RequesterName     string         `json:"requester_name"`
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	SalespersonName   sql.NullString `json:"salesperson_name"`
	ClientCode        string         `json:"client_code"`
	ClientName        string         `json:"client_name"`
	ClientAliasName   string         `json:"client_alias_name"`
	StatusID          int32          `json:"status_id"`
	PriorityID        int32          `json:"priority_id"`
	ReasonID          int32          `json:"reason_id"`
	Description       string         `json:"description"`
	CapturedAt        sql.NullTime   `json:"captured_at"`
	Resolution        sql.NullString `json:"resolution"`
	ClosedAt          sql.NullTime   `json:"closed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	StatusName        string         `json:"status_name"`
	StatusBg          string         `json:"status_bg"`
	StatusBorder      string         `json:"status_border"`
	StatusText        string         `json:"status_text"`
	StatusIsClosed    bool           `json:"status_is_closed"`
	PriorityName      string         `json:"priority_name"`
	PriorityBg        string         `json:"priority_bg"`
	ReasonName        string         `json:"reason_name"`
}

func (q *Queries) GetPurchasingOrderByID(ctx context.Context, purchasingOrderID int32) (GetPurchasingOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPurchasingOrderByID, purchasingOrderID)
	var i GetPurchasingOrderByIDRow
	err := row.Scan(
		&i.PurchasingOrderID,
		&i.RequesterID,
		&i.RequesterName,
		&i.AssignedToID,
		&i.AssignedToName,
		&i.SalespersonName,
		&i.ClientCode,
		&i.ClientName,
		&i.ClientAliasName,
		&i.StatusID,
		&i.PriorityID,
		&i.ReasonID,
		&i.Description,
		&i.CapturedAt,
		&i.Resolution,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusName,
		&i.StatusBg,
		&i.StatusBorder,
		&i.StatusText,
		&i.StatusIsClosed,
		&i.PriorityName,
		&i.PriorityBg,
		&i.ReasonName,
	)
	return i, err
}

const getPurchasingOrderPriorityByID = `-- name: GetPurchasingOrderPriorityByID :one
SELECT purchasing_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM purchasing_order_priorities
WHERE purchasing_order_priority_id=?
`

func (q *Queries) GetPurchasingOrderPriorityByID(ctx context.Context, purchasingOrderPriorityID int32) (PurchasingOrderPriority, error) {
	row := q.db.QueryRowContext(ctx, getPurchasingOrderPriorityByID, purchasingOrderPriorityID)
	var i PurchasingOrderPriority
	err := row.Scan(
		&i.PurchasingOrderPriorityID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
	)
	return i, err
}

const getPurchasingOrderReasonByID = `-- name: GetPurchasingOrderReasonByID :one
SELECT r.purchasing_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM purchasing_order_reason r
JOIN purchasing_order_status s ON s.purchasing_order_status_id = r.initial_status_id
WHERE r.purchasing_order_reason_id=? AND r.deleted_at IS NULL
`

type GetPurchasingOrderReasonByIDRow struct {
	PurchasingOrderReasonID int32  `json:"purchasing_order_reason_id"`
	Name                    string `json:"name"`
	InitialStatusID         int32  `json:"initial_status_id"`
	InitialStatusName       string `json:"initial_status_name"`
}

func (q *Queries) GetPurchasingOrderReasonByID(ctx context.Context, purchasingOrderReasonID int32) (GetPurchasingOrderReasonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPurchasingOrderReasonByID, purchasingOrderReasonID)
	var i GetPurchasingOrderReasonByIDRow
	err := row.Scan(
		&i.PurchasingOrderReasonID,
		&i.Name,
		&i.InitialStatusID,
		&i.InitialStatusName,
	)
	return i, err
}

const getPurchasingOrderStatusByID = `-- name: GetPurchasingOrderStatusByID :one
SELECT purchasing_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_default, is_pending_approval
FROM purchasing_order_status
WHERE purchasing_order_status_id=?
`

func (q *Queries) GetPurchasingOrderStatusByID(ctx context.Context, purchasingOrderStatusID int32) (PurchasingOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getPurchasingOrderStatusByID, purchasingOrderStatusID)
	var i PurchasingOrderStatus
	err := row.Scan(
		&i.PurchasingOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsDefault,
		&i.IsPendingApproval,
	)
	return i, err
}

const listPurchasingOrderAttachments = `-- name: ListPurchasingOrderAttachments :many
SELECT purchasing_order_attachment_id, purchasing_order_id, file_name, file_path, file_size, created_at
FROM purchasing_order_attachment
WHERE purchasing_order_id=? AND deleted_at IS NULL
ORDER BY created_at
`

type ListPurchasingOrderAttachmentsRow struct {
	PurchasingOrderAttachmentID int32     `json:"purchasing_order_attachment_id"`
	PurchasingOrderID           int32     `json:"purchasing_order_id"`
	FileName                    string    `json:"file_name"`
	FilePath                    string    `json:"file_path"`
	FileSize                    int32     `json:"file_size"`
	CreatedAt                   time.Time `json:"created_at"`
}

func (q *Queries) ListPurchasingOrderAttachments(ctx context.Context, purchasingOrderID int32) ([]ListPurchasingOrderAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasingOrderAttachments, purchasingOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasingOrderAttachmentsRow
	for rows.Next() {
		var i ListPurchasingOrderAttachmentsRow
		if err := rows.Scan(
			&i.PurchasingOrderAttachmentID,
			&i.PurchasingOrderID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasingOrderPriorities = `-- name: ListPurchasingOrderPriorities :many

SELECT purchasing_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM purchasing_order_priorities
ORDER BY sort_index
`

// ── Purchasing Priority ───────────────────────────────────────────────────────
func (q *Queries) ListPurchasingOrderPriorities(ctx context.Context) ([]PurchasingOrderPriority, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasingOrderPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchasingOrderPriority
	for rows.Next() {
		var i PurchasingOrderPriority
		if err := rows.Scan(
			&i.PurchasingOrderPriorityID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasingOrderReasons = `-- name: ListPurchasingOrderReasons :many

SELECT r.purchasing_order_reason_id, r.name, r.initial_status_id,
       s.name AS initial_status_name
FROM purchasing_order_reason r
JOIN purchasing_order_status s ON s.purchasing_order_status_id = r.initial_status_id
WHERE r.deleted_at IS NULL
ORDER BY r.name
`

type ListPurchasingOrderReasonsRow struct {
	PurchasingOrderReasonID int32  `json:"purchasing_order_reason_id"`
	Name                    string `json:"name"`
	InitialStatusID         int32  `json:"initial_status_id"`
	InitialStatusName       string `json:"initial_status_name"`
}

// ── Purchasing Reason ─────────────────────────────────────────────────────────
func (q *Queries) ListPurchasingOrderReasons(ctx context.Context) ([]ListPurchasingOrderReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasingOrderReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasingOrderReasonsRow
	for rows.Next() {
		var i ListPurchasingOrderReasonsRow
		if err := rows.Scan(
			&i.PurchasingOrderReasonID,
			&i.Name,
			&i.InitialStatusID,
			&i.InitialStatusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasingOrderStatuses = `-- name: ListPurchasingOrderStatuses :many

SELECT purchasing_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_default, is_pending_approval
FROM purchasing_order_status
ORDER BY sort_index
`

// ── Purchasing Status ─────────────────────────────────────────────────────────
func (q *Queries) ListPurchasingOrderStatuses(ctx context.Context) ([]PurchasingOrderStatus, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasingOrderStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchasingOrderStatus
	for rows.Next() {
		var i PurchasingOrderStatus
		if err := rows.Scan(
			&i.PurchasingOrderStatusID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
			&i.IsClosed,
			&i.IsDefault,
			&i.IsPendingApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasingStatusTransitions = `-- name: ListPurchasingStatusTransitions :many

SELECT id, from_status_id, to_status_id, access_level_id
FROM purchasing_order_status_transition
`

// ── Purchasing Status Transitions ─────────────────────────────────────────────
func (q *Queries) ListPurchasingStatusTransitions(ctx context.Context) ([]PurchasingOrderStatusTransition, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasingStatusTransitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchasingOrderStatusTransition
	for rows.Next() {
		var i PurchasingOrderStatusTransition
		if err := rows.Scan(
			&i.ID,
			&i.FromStatusID,
			&i.ToStatusID,
			&i.AccessLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchasingOrder = `-- name: UpdatePurchasingOrder :exec
UPDATE purchasing_order
SET assigned_to_id=?, assigned_to_name=?, salesperson_name=?,
    client_code=?, client_name=?, client_alias_name=?,
    status_id=?, priority_id=?, reason_id=?, description=?,
    captured_at=?, resolution=?, closed_at=?
WHERE purchasing_order_id=? AND deleted_at IS NULL
`

type UpdatePurchasingOrderParams struct {
	AssignedToID      sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName    sql.NullString `json:"assigned_to_name"`
	SalespersonName   sql.NullString `json:"salesperson_name"`
	ClientCode        string         `json:"client_code"`
	ClientName        string         `json:"client_name"`
	ClientAliasName   string         `json:"client_alias_name"`
	StatusID          int32          `json:"status_id"`
	PriorityID        int32          `json:"priority_id"`
	ReasonID          int32          `json:"reason_id"`
	Description       string         `json:"description"`
	CapturedAt        sql.NullTime   `json:"captured_at"`
	Resolution        sql.NullString `json:"resolution"`
	ClosedAt          sql.NullTime   `json:"closed_at"`
	PurchasingOrderID int32          `json:"purchasing_order_id"`
}

func (q *Queries) UpdatePurchasingOrder(ctx context.Context, arg UpdatePurchasingOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchasingOrder,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.Description,
		arg.CapturedAt,
		arg.Resolution,
		arg.ClosedAt,
		arg.PurchasingOrderID,
	)
	return err
}

const updatePurchasingOrderPriority = `-- name: UpdatePurchasingOrderPriority :exec
UPDATE purchasing_order_priorities
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?
WHERE purchasing_order_priority_id=?
`

type UpdatePurchasingOrderPriorityParams struct {
	Name                      string `json:"name"`
	BackgroundColor           string `json:"background_color"`
	BorderColor               string `json:"border_color"`
	TextColor                 string `json:"text_color"`
	SortIndex                 int32  `json:"sort_index"`
	PurchasingOrderPriorityID int32  `json:"purchasing_order_priority_id"`
}

func (q *Queries) UpdatePurchasingOrderPriority(ctx context.Context, arg UpdatePurchasingOrderPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchasingOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.PurchasingOrderPriorityID,
	)
	return err
}

const updatePurchasingOrderReason = `-- name: UpdatePurchasingOrderReason :exec
UPDATE purchasing_order_reason SET name=?, initial_status_id=?
WHERE purchasing_order_reason_id=? AND deleted_at IS NULL
`

type UpdatePurchasingOrderReasonParams struct {
	Name                    string `json:"name"`
	InitialStatusID         int32  `json:"initial_status_id"`
	PurchasingOrderReasonID int32  `json:"purchasing_order_reason_id"`
}

func (q *Queries) UpdatePurchasingOrderReason(ctx context.Context, arg UpdatePurchasingOrderReasonParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchasingOrderReason, arg.Name, arg.InitialStatusID, arg.PurchasingOrderReasonID)
	return err
}

const updatePurchasingOrderStatus = `-- name: UpdatePurchasingOrderStatus :exec
UPDATE purchasing_order SET status_id=?, captured_at=?, closed_at=?
WHERE purchasing_order_id=? AND deleted_at IS NULL
`

type UpdatePurchasingOrderStatusParams struct {
	StatusID          int32        `json:"status_id"`
	CapturedAt        sql.NullTime `json:"captured_at"`
	ClosedAt          sql.NullTime `json:"closed_at"`
	PurchasingOrderID int32        `json:"purchasing_order_id"`
}

func (q *Queries) UpdatePurchasingOrderStatus(ctx context.Context, arg UpdatePurchasingOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchasingOrderStatus,
		arg.StatusID,
		arg.CapturedAt,
		arg.ClosedAt,
		arg.PurchasingOrderID,
	)
	return err
}

const updatePurchasingStatusRecord = `-- name: UpdatePurchasingStatusRecord :exec
UPDATE purchasing_order_status
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?,
    is_closed=?, is_default=?, is_pending_approval=?
WHERE purchasing_order_status_id=?
`

type UpdatePurchasingStatusRecordParams struct {
	Name                    string `json:"name"`
	BackgroundColor         string `json:"background_color"`
	BorderColor             string `json:"border_color"`
	TextColor               string `json:"text_color"`
	SortIndex               int32  `json:"sort_index"`
	IsClosed                bool   `json:"is_closed"`
	IsDefault               bool   `json:"is_default"`
	IsPendingApproval       bool   `json:"is_pending_approval"`
	PurchasingOrderStatusID int32  `json:"purchasing_order_status_id"`
}

func (q *Queries) UpdatePurchasingStatusRecord(ctx context.Context, arg UpdatePurchasingStatusRecordParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchasingStatusRecord,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.IsPendingApproval,
		arg.PurchasingOrderStatusID,
	)
	return err
}
