// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: return.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignReturnOrder = `-- name: AssignReturnOrder :exec
UPDATE return_order SET assigned_to_id=?, assigned_to_name=?
WHERE return_order_id=? AND deleted_at IS NULL
`

type AssignReturnOrderParams struct {
	AssignedToID   sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName sql.NullString `json:"assigned_to_name"`
	ReturnOrderID  int32          `json:"return_order_id"`
}

func (q *Queries) AssignReturnOrder(ctx context.Context, arg AssignReturnOrderParams) error {
	_, err := q.db.ExecContext(ctx, assignReturnOrder, arg.AssignedToID, arg.AssignedToName, arg.ReturnOrderID)
	return err
}

const createReturnOrder = `-- name: CreateReturnOrder :execresult

INSERT INTO return_order (requester_id, requester_name, assigned_to_id, assigned_to_name,
    salesperson_name, client_code, client_name, client_alias_name,
    contact_type, contact_name, contact_phone, contact_mobile, contact_email,
    address_name, address_type, type_of_address, street, street_no, block,
    city, county, state, country, zip_code, building_floor_room,
    status_id, priority_id, reason_id, credit_form_id,
    pix_key_type, pix_key_owner, pix_key,
    transfer_bank, transfer_agency, transfer_account,
    nfe, client_sent_return_note, internal_return, partial_return,
    schedule_date, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReturnOrderParams struct {
	RequesterID          int32          `json:"requester_id"`
	RequesterName        string         `json:"requester_name"`
	AssignedToID         sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName       sql.NullString `json:"assigned_to_name"`
	SalespersonName      sql.NullString `json:"salesperson_name"`
	ClientCode           string         `json:"client_code"`
	ClientName           string         `json:"client_name"`
	ClientAliasName      string         `json:"client_alias_name"`
	ContactType          sql.NullString `json:"contact_type"`
	ContactName          sql.NullString `json:"contact_name"`
	ContactPhone         sql.NullString `json:"contact_phone"`
	ContactMobile        sql.NullString `json:"contact_mobile"`
	ContactEmail         sql.NullString `json:"contact_email"`
	AddressName          sql.NullString `json:"address_name"`
	AddressType          sql.NullString `json:"address_type"`
	TypeOfAddress        sql.NullString `json:"type_of_address"`
	Street               sql.NullString `json:"street"`
	StreetNo             sql.NullString `json:"street_no"`
	Block                sql.NullString `json:"block"`
	City                 sql.NullString `json:"city"`
	County               sql.NullString `json:"county"`
	State                sql.NullString `json:"state"`
	Country              sql.NullString `json:"country"`
	ZipCode              sql.NullString `json:"zip_code"`
	BuildingFloorRoom    sql.NullString `json:"building_floor_room"`
	StatusID             int32          `json:"status_id"`
	PriorityID           int32          `json:"priority_id"`
	ReasonID             int32          `json:"reason_id"`
	CreditFormID         sql.NullInt32  `json:"credit_form_id"`
	PixKeyType           sql.NullString `json:"pix_key_type"`
	PixKeyOwner          sql.NullString `json:"pix_key_owner"`
	PixKey               sql.NullString `json:"pix_key"`
	TransferBank         sql.NullString `json:"transfer_bank"`
	TransferAgency       sql.NullString `json:"transfer_agency"`
	TransferAccount      sql.NullString `json:"transfer_account"`
	Nfe                  sql.NullString `json:"nfe"`
	ClientSentReturnNote bool           `json:"client_sent_return_note"`
	InternalReturn       bool           `json:"internal_return"`
	PartialReturn        bool           `json:"partial_return"`
	ScheduleDate         sql.NullTime   `json:"schedule_date"`
	Description          string         `json:"description"`
}

// ── Return Orders ─────────────────────────────────────────────────────────────
func (q *Queries) CreateReturnOrder(ctx context.Context, arg CreateReturnOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrder,
		arg.RequesterID,
		arg.RequesterName,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.ContactType,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactMobile,
		arg.ContactEmail,
		arg.AddressName,
		arg.AddressType,
		arg.TypeOfAddress,
		arg.Street,
		arg.StreetNo,
		arg.Block,
		arg.City,
		arg.County,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.BuildingFloorRoom,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.CreditFormID,
		arg.PixKeyType,
		arg.PixKeyOwner,
		arg.PixKey,
		arg.TransferBank,
		arg.TransferAgency,
		arg.TransferAccount,
		arg.Nfe,
		arg.ClientSentReturnNote,
		arg.InternalReturn,
		arg.PartialReturn,
		arg.ScheduleDate,
		arg.Description,
	)
}

const createReturnOrderAttachment = `-- name: CreateReturnOrderAttachment :execresult

INSERT INTO return_order_attachment (return_order_id, file_name, file_path, file_size)
VALUES (?, ?, ?, ?)
`

type CreateReturnOrderAttachmentParams struct {
	ReturnOrderID int32  `json:"return_order_id"`
	FileName      string `json:"file_name"`
	FilePath      string `json:"file_path"`
	FileSize      int32  `json:"file_size"`
}

// ── Return Attachments ────────────────────────────────────────────────────────
func (q *Queries) CreateReturnOrderAttachment(ctx context.Context, arg CreateReturnOrderAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrderAttachment,
		arg.ReturnOrderID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
	)
}

const createReturnOrderCreditForm = `-- name: CreateReturnOrderCreditForm :execresult
INSERT INTO return_order_credit_form (name) VALUES (?)
`

func (q *Queries) CreateReturnOrderCreditForm(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrderCreditForm, name)
}

const createReturnOrderItem = `-- name: CreateReturnOrderItem :execresult

INSERT INTO return_order_items (return_order_id, name, item_code, quantity)
VALUES (?, ?, ?, ?)
`

type CreateReturnOrderItemParams struct {
	ReturnOrderID int32  `json:"return_order_id"`
	Name          string `json:"name"`
	ItemCode      string `json:"item_code"`
	Quantity      int32  `json:"quantity"`
}

// ── Return Items ──────────────────────────────────────────────────────────────
func (q *Queries) CreateReturnOrderItem(ctx context.Context, arg CreateReturnOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrderItem,
		arg.ReturnOrderID,
		arg.Name,
		arg.ItemCode,
		arg.Quantity,
	)
}

const createReturnOrderPriority = `-- name: CreateReturnOrderPriority :execresult
INSERT INTO return_order_priorities (name, background_color, border_color, text_color, sort_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateReturnOrderPriorityParams struct {
	Name            string `json:"name"`
	BackgroundColor string `json:"background_color"`
	BorderColor     string `json:"border_color"`
	TextColor       string `json:"text_color"`
	SortIndex       int32  `json:"sort_index"`
}

func (q *Queries) CreateReturnOrderPriority(ctx context.Context, arg CreateReturnOrderPriorityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
	)
}

const createReturnOrderReason = `-- name: CreateReturnOrderReason :execresult
INSERT INTO return_order_reason (name, description, initial_status_id) VALUES (?, ?, ?)
`

type CreateReturnOrderReasonParams struct {
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	InitialStatusID int32          `json:"initial_status_id"`
}

func (q *Queries) CreateReturnOrderReason(ctx context.Context, arg CreateReturnOrderReasonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrderReason, arg.Name, arg.Description, arg.InitialStatusID)
}

const createReturnOrderStatus = `-- name: CreateReturnOrderStatus :execresult
INSERT INTO return_order_status (name, background_color, border_color, text_color,
    sort_index, is_closed, is_default, is_pending_approval)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReturnOrderStatusParams struct {
	Name              string `json:"name"`
	BackgroundColor   string `json:"background_color"`
	BorderColor       string `json:"border_color"`
	TextColor         string `json:"text_color"`
	SortIndex         int32  `json:"sort_index"`
	IsClosed          bool   `json:"is_closed"`
	IsDefault         bool   `json:"is_default"`
	IsPendingApproval bool   `json:"is_pending_approval"`
}

func (q *Queries) CreateReturnOrderStatus(ctx context.Context, arg CreateReturnOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnOrderStatus,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.IsPendingApproval,
	)
}

const createReturnStatusTransition = `-- name: CreateReturnStatusTransition :execresult
INSERT INTO return_order_status_transition (from_status_id, to_status_id, access_level_id)
VALUES (?, ?, ?)
`

type CreateReturnStatusTransitionParams struct {
	FromStatusID  sql.NullInt32 `json:"from_status_id"`
	ToStatusID    int32         `json:"to_status_id"`
	AccessLevelID int32         `json:"access_level_id"`
}

func (q *Queries) CreateReturnStatusTransition(ctx context.Context, arg CreateReturnStatusTransitionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReturnStatusTransition, arg.FromStatusID, arg.ToStatusID, arg.AccessLevelID)
}

const deleteReturnConfigAssignableAccessLevels = `-- name: DeleteReturnConfigAssignableAccessLevels :exec
DELETE FROM return_config_assignable_access_level WHERE return_config_id=?
`

func (q *Queries) DeleteReturnConfigAssignableAccessLevels(ctx context.Context, returnConfigID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnConfigAssignableAccessLevels, returnConfigID)
	return err
}

const deleteReturnOrder = `-- name: DeleteReturnOrder :exec
UPDATE return_order SET deleted_at=NOW()
WHERE return_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteReturnOrder(ctx context.Context, returnOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrder, returnOrderID)
	return err
}

const deleteReturnOrderAttachment = `-- name: DeleteReturnOrderAttachment :exec
UPDATE return_order_attachment SET deleted_at=NOW()
WHERE return_order_attachment_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteReturnOrderAttachment(ctx context.Context, returnOrderAttachmentID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrderAttachment, returnOrderAttachmentID)
	return err
}

const deleteReturnOrderCreditForm = `-- name: DeleteReturnOrderCreditForm :exec
UPDATE return_order_credit_form SET deleted_at=NOW()
WHERE return_order_credit_form_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteReturnOrderCreditForm(ctx context.Context, returnOrderCreditFormID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrderCreditForm, returnOrderCreditFormID)
	return err
}

const deleteReturnOrderItems = `-- name: DeleteReturnOrderItems :exec
UPDATE return_order_items SET deleted_at=NOW()
WHERE return_order_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteReturnOrderItems(ctx context.Context, returnOrderID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrderItems, returnOrderID)
	return err
}

const deleteReturnOrderPriority = `-- name: DeleteReturnOrderPriority :exec
DELETE FROM return_order_priorities WHERE return_order_priority_id=?
`

func (q *Queries) DeleteReturnOrderPriority(ctx context.Context, returnOrderPriorityID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrderPriority, returnOrderPriorityID)
	return err
}

const deleteReturnOrderReason = `-- name: DeleteReturnOrderReason :exec
UPDATE return_order_reason SET deleted_at=NOW()
WHERE return_order_reason_id=? AND deleted_at IS NULL
`

func (q *Queries) DeleteReturnOrderReason(ctx context.Context, returnOrderReasonID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrderReason, returnOrderReasonID)
	return err
}

const deleteReturnOrderStatus = `-- name: DeleteReturnOrderStatus :exec
DELETE FROM return_order_status WHERE return_order_status_id=?
`

func (q *Queries) DeleteReturnOrderStatus(ctx context.Context, returnOrderStatusID int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnOrderStatus, returnOrderStatusID)
	return err
}

const deleteReturnStatusTransition = `-- name: DeleteReturnStatusTransition :exec
DELETE FROM return_order_status_transition WHERE id=?
`

func (q *Queries) DeleteReturnStatusTransition(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteReturnStatusTransition, id)
	return err
}

const getOrCreateReturnConfig = `-- name: GetOrCreateReturnConfig :one

SELECT return_config_id FROM return_config LIMIT 1
`

// ── Return Config ─────────────────────────────────────────────────────────────
func (q *Queries) GetOrCreateReturnConfig(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateReturnConfig)
	var return_config_id int32
	err := row.Scan(&return_config_id)
	return return_config_id, err
}

const getReturnConfigAssignableAccessLevels = `-- name: GetReturnConfigAssignableAccessLevels :many
SELECT a.access_level_id, a.name
FROM return_config_assignable_access_level ca
JOIN access_level a ON a.access_level_id = ca.access_level_id
WHERE ca.return_config_id=?
`

func (q *Queries) GetReturnConfigAssignableAccessLevels(ctx context.Context, returnConfigID int32) ([]AccessLevel, error) {
	rows, err := q.db.QueryContext(ctx, getReturnConfigAssignableAccessLevels, returnConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(&i.AccessLevelID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReturnOrderAttachmentByID = `-- name: GetReturnOrderAttachmentByID :one
SELECT return_order_attachment_id, return_order_id, file_name, file_path, file_size, created_at
FROM return_order_attachment
WHERE return_order_attachment_id=? AND deleted_at IS NULL
`

type GetReturnOrderAttachmentByIDRow struct {
	ReturnOrderAttachmentID int32     `json:"return_order_attachment_id"`
	ReturnOrderID           int32     `json:"return_order_id"`
	FileName                string    `json:"file_name"`
	FilePath                string    `json:"file_path"`
	FileSize                int32     `json:"file_size"`
	CreatedAt               time.Time `json:"created_at"`
}

func (q *Queries) GetReturnOrderAttachmentByID(ctx context.Context, returnOrderAttachmentID int32) (GetReturnOrderAttachmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReturnOrderAttachmentByID, returnOrderAttachmentID)
	var i GetReturnOrderAttachmentByIDRow
	err := row.Scan(
		&i.ReturnOrderAttachmentID,
		&i.ReturnOrderID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getReturnOrderByID = `-- name: GetReturnOrderByID :one
SELECT o.return_order_id, o.requester_id, o.requester_name, o.assigned_to_id, o.assigned_to_name,
       o.salesperson_name, o.client_code, o.client_name, o.client_alias_name,
       o.contact_type, o.contact_name, o.contact_phone, o.contact_mobile, o.contact_email,
       o.address_name, o.address_type, o.type_of_address, o.street, o.street_no, o.block,
       o.city, o.county, o.state, o.country, o.zip_code, o.building_floor_room,
       o.status_id, o.priority_id, o.reason_id, o.credit_form_id,
       o.pix_key_type, o.pix_key_owner, o.pix_key,
       o.transfer_bank, o.transfer_agency, o.transfer_account,
       o.nfe, o.client_sent_return_note, o.internal_return, o.partial_return,
       o.schedule_date, o.description, o.captured_at, o.resolution, o.closed_at,
       o.created_at, o.updated_at,
       s.name AS status_name, s.background_color AS status_bg, s.border_color AS status_border,
       s.text_color AS status_text, s.is_closed AS status_is_closed,
       p.name AS priority_name, p.background_color AS priority_bg,
       r.name AS reason_name,
       cf.name AS credit_form_name
FROM return_order o
JOIN return_order_status s     ON s.return_order_status_id   = o.status_id
JOIN return_order_priorities p ON p.return_order_priority_id = o.priority_id
JOIN return_order_reason r     ON r.return_order_reason_id   = o.reason_id
LEFT JOIN return_order_credit_form cf ON cf.return_order_credit_form_id = o.credit_form_id
WHERE o.return_order_id=? AND o.deleted_at IS NULL
`

type GetReturnOrderByIDRow struct {
	ReturnOrderID        int32          `json:"return_order_id"`
	RequesterID          int32          `json:"requester_id"`
	RequesterName        string         `json:"requester_name"`
	AssignedToID         sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName       sql.NullString `json:"assigned_to_name"`
	SalespersonName      sql.NullString `json:"salesperson_name"`
	ClientCode           string         `json:"client_code"`
	ClientName           string         `json:"client_name"`
	ClientAliasName      string         `json:"client_alias_name"`
	ContactType          sql.NullString `json:"contact_type"`
	ContactName          sql.NullString `json:"contact_name"`
	ContactPhone         sql.NullString `json:"contact_phone"`
	ContactMobile        sql.NullString `json:"contact_mobile"`
	ContactEmail         sql.NullString `json:"contact_email"`
	AddressName          sql.NullString `json:"address_name"`
	AddressType          sql.NullString `json:"address_type"`
	TypeOfAddress        sql.NullString `json:"type_of_address"`
	Street               sql.NullString `json:"street"`
	StreetNo             sql.NullString `json:"street_no"`
	Block                sql.NullString `json:"block"`
	City                 sql.NullString `json:"city"`
	County               sql.NullString `json:"county"`
	State                sql.NullString `json:"state"`
	Country              sql.NullString `json:"country"`
	ZipCode              sql.NullString `json:"zip_code"`
	BuildingFloorRoom    sql.NullString `json:"building_floor_room"`
	StatusID             int32          `json:"status_id"`
	PriorityID           int32          `json:"priority_id"`
	ReasonID             int32          `json:"reason_id"`
	CreditFormID         sql.NullInt32  `json:"credit_form_id"`
	PixKeyType           sql.NullString `json:"pix_key_type"`
	PixKeyOwner          sql.NullString `json:"pix_key_owner"`
	PixKey               sql.NullString `json:"pix_key"`
	TransferBank         sql.NullString `json:"transfer_bank"`
	TransferAgency       sql.NullString `json:"transfer_agency"`
	TransferAccount      sql.NullString `json:"transfer_account"`
	Nfe                  sql.NullString `json:"nfe"`
	ClientSentReturnNote bool           `json:"client_sent_return_note"`
	InternalReturn       bool           `json:"internal_return"`
	PartialReturn        bool           `json:"partial_return"`
	ScheduleDate         sql.NullTime   `json:"schedule_date"`
	Description          string         `json:"description"`
	CapturedAt           sql.NullTime   `json:"captured_at"`
	Resolution           sql.NullString `json:"resolution"`
	ClosedAt             sql.NullTime   `json:"closed_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	StatusName           string         `json:"status_name"`
	StatusBg             string         `json:"status_bg"`
	StatusBorder         string         `json:"status_border"`
	StatusText           string         `json:"status_text"`
	StatusIsClosed       bool           `json:"status_is_closed"`
	PriorityName         string         `json:"priority_name"`
	PriorityBg           string         `json:"priority_bg"`
	ReasonName           string         `json:"reason_name"`
	CreditFormName       sql.NullString `json:"credit_form_name"`
}

func (q *Queries) GetReturnOrderByID(ctx context.Context, returnOrderID int32) (GetReturnOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReturnOrderByID, returnOrderID)
	var i GetReturnOrderByIDRow
	err := row.Scan(
		&i.ReturnOrderID,
		&i.RequesterID,
		&i.RequesterName,
		&i.AssignedToID,
		&i.AssignedToName,
		&i.SalespersonName,
		&i.ClientCode,
		&i.ClientName,
		&i.ClientAliasName,
		&i.ContactType,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactMobile,
		&i.ContactEmail,
		&i.AddressName,
		&i.AddressType,
		&i.TypeOfAddress,
		&i.Street,
		&i.StreetNo,
		&i.Block,
		&i.City,
		&i.County,
		&i.State,
		&i.Country,
		&i.ZipCode,
		&i.BuildingFloorRoom,
		&i.StatusID,
		&i.PriorityID,
		&i.ReasonID,
		&i.CreditFormID,
		&i.PixKeyType,
		&i.PixKeyOwner,
		&i.PixKey,
		&i.TransferBank,
		&i.TransferAgency,
		&i.TransferAccount,
		&i.Nfe,
		&i.ClientSentReturnNote,
		&i.InternalReturn,
		&i.PartialReturn,
		&i.ScheduleDate,
		&i.Description,
		&i.CapturedAt,
		&i.Resolution,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusName,
		&i.StatusBg,
		&i.StatusBorder,
		&i.StatusText,
		&i.StatusIsClosed,
		&i.PriorityName,
		&i.PriorityBg,
		&i.ReasonName,
		&i.CreditFormName,
	)
	return i, err
}

const getReturnOrderCreditFormByID = `-- name: GetReturnOrderCreditFormByID :one
SELECT return_order_credit_form_id, name
FROM return_order_credit_form
WHERE return_order_credit_form_id=? AND deleted_at IS NULL
`

type GetReturnOrderCreditFormByIDRow struct {
	ReturnOrderCreditFormID int32  `json:"return_order_credit_form_id"`
	Name                    string `json:"name"`
}

func (q *Queries) GetReturnOrderCreditFormByID(ctx context.Context, returnOrderCreditFormID int32) (GetReturnOrderCreditFormByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReturnOrderCreditFormByID, returnOrderCreditFormID)
	var i GetReturnOrderCreditFormByIDRow
	err := row.Scan(&i.ReturnOrderCreditFormID, &i.Name)
	return i, err
}

const getReturnOrderPriorityByID = `-- name: GetReturnOrderPriorityByID :one
SELECT return_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM return_order_priorities
WHERE return_order_priority_id=?
`

func (q *Queries) GetReturnOrderPriorityByID(ctx context.Context, returnOrderPriorityID int32) (ReturnOrderPriority, error) {
	row := q.db.QueryRowContext(ctx, getReturnOrderPriorityByID, returnOrderPriorityID)
	var i ReturnOrderPriority
	err := row.Scan(
		&i.ReturnOrderPriorityID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
	)
	return i, err
}

const getReturnOrderReasonByID = `-- name: GetReturnOrderReasonByID :one
SELECT r.return_order_reason_id, r.name, r.description, r.initial_status_id,
       s.name AS initial_status_name
FROM return_order_reason r
JOIN return_order_status s ON s.return_order_status_id = r.initial_status_id
WHERE r.return_order_reason_id=? AND r.deleted_at IS NULL
`

type GetReturnOrderReasonByIDRow struct {
	ReturnOrderReasonID int32          `json:"return_order_reason_id"`
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	InitialStatusID     int32          `json:"initial_status_id"`
	InitialStatusName   string         `json:"initial_status_name"`
}

func (q *Queries) GetReturnOrderReasonByID(ctx context.Context, returnOrderReasonID int32) (GetReturnOrderReasonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReturnOrderReasonByID, returnOrderReasonID)
	var i GetReturnOrderReasonByIDRow
	err := row.Scan(
		&i.ReturnOrderReasonID,
		&i.Name,
		&i.Description,
		&i.InitialStatusID,
		&i.InitialStatusName,
	)
	return i, err
}

const getReturnOrderStatusByID = `-- name: GetReturnOrderStatusByID :one
SELECT return_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_default, is_pending_approval
FROM return_order_status
WHERE return_order_status_id=?
`

func (q *Queries) GetReturnOrderStatusByID(ctx context.Context, returnOrderStatusID int32) (ReturnOrderStatus, error) {
	row := q.db.QueryRowContext(ctx, getReturnOrderStatusByID, returnOrderStatusID)
	var i ReturnOrderStatus
	err := row.Scan(
		&i.ReturnOrderStatusID,
		&i.Name,
		&i.BackgroundColor,
		&i.BorderColor,
		&i.TextColor,
		&i.SortIndex,
		&i.IsClosed,
		&i.IsDefault,
		&i.IsPendingApproval,
	)
	return i, err
}

const insertReturnConfig = `-- name: InsertReturnConfig :execresult
INSERT INTO return_config () VALUES ()
`

func (q *Queries) InsertReturnConfig(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReturnConfig)
}

const insertReturnConfigAssignableAccessLevel = `-- name: InsertReturnConfigAssignableAccessLevel :exec
INSERT INTO return_config_assignable_access_level (return_config_id, access_level_id)
VALUES (?, ?)
`

type InsertReturnConfigAssignableAccessLevelParams struct {
	ReturnConfigID int32 `json:"return_config_id"`
	AccessLevelID  int32 `json:"access_level_id"`
}

func (q *Queries) InsertReturnConfigAssignableAccessLevel(ctx context.Context, arg InsertReturnConfigAssignableAccessLevelParams) error {
	_, err := q.db.ExecContext(ctx, insertReturnConfigAssignableAccessLevel, arg.ReturnConfigID, arg.AccessLevelID)
	return err
}

const listReturnOrderAttachments = `-- name: ListReturnOrderAttachments :many
SELECT return_order_attachment_id, return_order_id, file_name, file_path, file_size, created_at
FROM return_order_attachment
WHERE return_order_id=? AND deleted_at IS NULL
ORDER BY created_at
`

type ListReturnOrderAttachmentsRow struct {
	ReturnOrderAttachmentID int32     `json:"return_order_attachment_id"`
	ReturnOrderID           int32     `json:"return_order_id"`
	FileName                string    `json:"file_name"`
	FilePath                string    `json:"file_path"`
	FileSize                int32     `json:"file_size"`
	CreatedAt               time.Time `json:"created_at"`
}

func (q *Queries) ListReturnOrderAttachments(ctx context.Context, returnOrderID int32) ([]ListReturnOrderAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReturnOrderAttachments, returnOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturnOrderAttachmentsRow
	for rows.Next() {
		var i ListReturnOrderAttachmentsRow
		if err := rows.Scan(
			&i.ReturnOrderAttachmentID,
			&i.ReturnOrderID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnOrderCreditForms = `-- name: ListReturnOrderCreditForms :many

SELECT return_order_credit_form_id, name
FROM return_order_credit_form
WHERE deleted_at IS NULL
ORDER BY name
`

type ListReturnOrderCreditFormsRow struct {
	ReturnOrderCreditFormID int32  `json:"return_order_credit_form_id"`
	Name                    string `json:"name"`
}

// ── Return Credit Form ────────────────────────────────────────────────────────
func (q *Queries) ListReturnOrderCreditForms(ctx context.Context) ([]ListReturnOrderCreditFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReturnOrderCreditForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturnOrderCreditFormsRow
	for rows.Next() {
		var i ListReturnOrderCreditFormsRow
		if err := rows.Scan(&i.ReturnOrderCreditFormID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnOrderItems = `-- name: ListReturnOrderItems :many
SELECT return_order_item_id, return_order_id, name, item_code, quantity
FROM return_order_items
WHERE return_order_id=? AND deleted_at IS NULL
`

type ListReturnOrderItemsRow struct {
	ReturnOrderItemID int32  `json:"return_order_item_id"`
	ReturnOrderID     int32  `json:"return_order_id"`
	Name              string `json:"name"`
	ItemCode          string `json:"item_code"`
	Quantity          int32  `json:"quantity"`
}

func (q *Queries) ListReturnOrderItems(ctx context.Context, returnOrderID int32) ([]ListReturnOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReturnOrderItems, returnOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturnOrderItemsRow
	for rows.Next() {
		var i ListReturnOrderItemsRow
		if err := rows.Scan(
			&i.ReturnOrderItemID,
			&i.ReturnOrderID,
			&i.Name,
			&i.ItemCode,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnOrderPriorities = `-- name: ListReturnOrderPriorities :many

SELECT return_order_priority_id, name, background_color, border_color, text_color, sort_index
FROM return_order_priorities
ORDER BY sort_index
`

// ── Return Priority ───────────────────────────────────────────────────────────
func (q *Queries) ListReturnOrderPriorities(ctx context.Context) ([]ReturnOrderPriority, error) {
	rows, err := q.db.QueryContext(ctx, listReturnOrderPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnOrderPriority
	for rows.Next() {
		var i ReturnOrderPriority
		if err := rows.Scan(
			&i.ReturnOrderPriorityID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnOrderReasons = `-- name: ListReturnOrderReasons :many

SELECT r.return_order_reason_id, r.name, r.description, r.initial_status_id,
       s.name AS initial_status_name
FROM return_order_reason r
JOIN return_order_status s ON s.return_order_status_id = r.initial_status_id
WHERE r.deleted_at IS NULL
ORDER BY r.name
`

type ListReturnOrderReasonsRow struct {
	ReturnOrderReasonID int32          `json:"return_order_reason_id"`
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	InitialStatusID     int32          `json:"initial_status_id"`
	InitialStatusName   string         `json:"initial_status_name"`
}

// ── Return Reason ─────────────────────────────────────────────────────────────
func (q *Queries) ListReturnOrderReasons(ctx context.Context) ([]ListReturnOrderReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReturnOrderReasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturnOrderReasonsRow
	for rows.Next() {
		var i ListReturnOrderReasonsRow
		if err := rows.Scan(
			&i.ReturnOrderReasonID,
			&i.Name,
			&i.Description,
			&i.InitialStatusID,
			&i.InitialStatusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnOrderStatuses = `-- name: ListReturnOrderStatuses :many

SELECT return_order_status_id, name, background_color, border_color, text_color,
       sort_index, is_closed, is_default, is_pending_approval
FROM return_order_status
ORDER BY sort_index
`

// ── Return Status ─────────────────────────────────────────────────────────────
func (q *Queries) ListReturnOrderStatuses(ctx context.Context) ([]ReturnOrderStatus, error) {
	rows, err := q.db.QueryContext(ctx, listReturnOrderStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnOrderStatus
	for rows.Next() {
		var i ReturnOrderStatus
		if err := rows.Scan(
			&i.ReturnOrderStatusID,
			&i.Name,
			&i.BackgroundColor,
			&i.BorderColor,
			&i.TextColor,
			&i.SortIndex,
			&i.IsClosed,
			&i.IsDefault,
			&i.IsPendingApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnStatusTransitions = `-- name: ListReturnStatusTransitions :many

SELECT id, from_status_id, to_status_id, access_level_id
FROM return_order_status_transition
`

// ── Return Status Transitions ─────────────────────────────────────────────────
func (q *Queries) ListReturnStatusTransitions(ctx context.Context) ([]ReturnOrderStatusTransition, error) {
	rows, err := q.db.QueryContext(ctx, listReturnStatusTransitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnOrderStatusTransition
	for rows.Next() {
		var i ReturnOrderStatusTransition
		if err := rows.Scan(
			&i.ID,
			&i.FromStatusID,
			&i.ToStatusID,
			&i.AccessLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReturnOrder = `-- name: UpdateReturnOrder :exec
UPDATE return_order
SET assigned_to_id=?, assigned_to_name=?, salesperson_name=?,
    client_code=?, client_name=?, client_alias_name=?,
    contact_type=?, contact_name=?, contact_phone=?, contact_mobile=?, contact_email=?,
    address_name=?, address_type=?, type_of_address=?, street=?, street_no=?, block=?,
    city=?, county=?, state=?, country=?, zip_code=?, building_floor_room=?,
    status_id=?, priority_id=?, reason_id=?, credit_form_id=?,
    pix_key_type=?, pix_key_owner=?, pix_key=?,
    transfer_bank=?, transfer_agency=?, transfer_account=?,
    nfe=?, client_sent_return_note=?, internal_return=?, partial_return=?,
    schedule_date=?, description=?, captured_at=?, resolution=?, closed_at=?
WHERE return_order_id=? AND deleted_at IS NULL
`

type UpdateReturnOrderParams struct {
	AssignedToID         sql.NullInt32  `json:"assigned_to_id"`
	AssignedToName       sql.NullString `json:"assigned_to_name"`
	SalespersonName      sql.NullString `json:"salesperson_name"`
	ClientCode           string         `json:"client_code"`
	ClientName           string         `json:"client_name"`
	ClientAliasName      string         `json:"client_alias_name"`
	ContactType          sql.NullString `json:"contact_type"`
	ContactName          sql.NullString `json:"contact_name"`
	ContactPhone         sql.NullString `json:"contact_phone"`
	ContactMobile        sql.NullString `json:"contact_mobile"`
	ContactEmail         sql.NullString `json:"contact_email"`
	AddressName          sql.NullString `json:"address_name"`
	AddressType          sql.NullString `json:"address_type"`
	TypeOfAddress        sql.NullString `json:"type_of_address"`
	Street               sql.NullString `json:"street"`
	StreetNo             sql.NullString `json:"street_no"`
	Block                sql.NullString `json:"block"`
	City                 sql.NullString `json:"city"`
	County               sql.NullString `json:"county"`
	State                sql.NullString `json:"state"`
	Country              sql.NullString `json:"country"`
	ZipCode              sql.NullString `json:"zip_code"`
	BuildingFloorRoom    sql.NullString `json:"building_floor_room"`
	StatusID             int32          `json:"status_id"`
	PriorityID           int32          `json:"priority_id"`
	ReasonID             int32          `json:"reason_id"`
	CreditFormID         sql.NullInt32  `json:"credit_form_id"`
	PixKeyType           sql.NullString `json:"pix_key_type"`
	PixKeyOwner          sql.NullString `json:"pix_key_owner"`
	PixKey               sql.NullString `json:"pix_key"`
	TransferBank         sql.NullString `json:"transfer_bank"`
	TransferAgency       sql.NullString `json:"transfer_agency"`
	TransferAccount      sql.NullString `json:"transfer_account"`
	Nfe                  sql.NullString `json:"nfe"`
	ClientSentReturnNote bool           `json:"client_sent_return_note"`
	InternalReturn       bool           `json:"internal_return"`
	PartialReturn        bool           `json:"partial_return"`
	ScheduleDate         sql.NullTime   `json:"schedule_date"`
	Description          string         `json:"description"`
	CapturedAt           sql.NullTime   `json:"captured_at"`
	Resolution           sql.NullString `json:"resolution"`
	ClosedAt             sql.NullTime   `json:"closed_at"`
	ReturnOrderID        int32          `json:"return_order_id"`
}

func (q *Queries) UpdateReturnOrder(ctx context.Context, arg UpdateReturnOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateReturnOrder,
		arg.AssignedToID,
		arg.AssignedToName,
		arg.SalespersonName,
		arg.ClientCode,
		arg.ClientName,
		arg.ClientAliasName,
		arg.ContactType,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactMobile,
		arg.ContactEmail,
		arg.AddressName,
		arg.AddressType,
		arg.TypeOfAddress,
		arg.Street,
		arg.StreetNo,
		arg.Block,
		arg.City,
		arg.County,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.BuildingFloorRoom,
		arg.StatusID,
		arg.PriorityID,
		arg.ReasonID,
		arg.CreditFormID,
		arg.PixKeyType,
		arg.PixKeyOwner,
		arg.PixKey,
		arg.TransferBank,
		arg.TransferAgency,
		arg.TransferAccount,
		arg.Nfe,
		arg.ClientSentReturnNote,
		arg.InternalReturn,
		arg.PartialReturn,
		arg.ScheduleDate,
		arg.Description,
		arg.CapturedAt,
		arg.Resolution,
		arg.ClosedAt,
		arg.ReturnOrderID,
	)
	return err
}

const updateReturnOrderCreditForm = `-- name: UpdateReturnOrderCreditForm :exec
UPDATE return_order_credit_form SET name=?
WHERE return_order_credit_form_id=? AND deleted_at IS NULL
`

type UpdateReturnOrderCreditFormParams struct {
	Name                    string `json:"name"`
	ReturnOrderCreditFormID int32  `json:"return_order_credit_form_id"`
}

func (q *Queries) UpdateReturnOrderCreditForm(ctx context.Context, arg UpdateReturnOrderCreditFormParams) error {
	_, err := q.db.ExecContext(ctx, updateReturnOrderCreditForm, arg.Name, arg.ReturnOrderCreditFormID)
	return err
}

const updateReturnOrderPriority = `-- name: UpdateReturnOrderPriority :exec
UPDATE return_order_priorities
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?
WHERE return_order_priority_id=?
`

type UpdateReturnOrderPriorityParams struct {
	Name                  string `json:"name"`
	BackgroundColor       string `json:"background_color"`
	BorderColor           string `json:"border_color"`
	TextColor             string `json:"text_color"`
	SortIndex             int32  `json:"sort_index"`
	ReturnOrderPriorityID int32  `json:"return_order_priority_id"`
}

func (q *Queries) UpdateReturnOrderPriority(ctx context.Context, arg UpdateReturnOrderPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateReturnOrderPriority,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.ReturnOrderPriorityID,
	)
	return err
}

const updateReturnOrderReason = `-- name: UpdateReturnOrderReason :exec
UPDATE return_order_reason SET name=?, description=?, initial_status_id=?
WHERE return_order_reason_id=? AND deleted_at IS NULL
`

type UpdateReturnOrderReasonParams struct {
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	InitialStatusID     int32          `json:"initial_status_id"`
	ReturnOrderReasonID int32          `json:"return_order_reason_id"`
}

func (q *Queries) UpdateReturnOrderReason(ctx context.Context, arg UpdateReturnOrderReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateReturnOrderReason,
		arg.Name,
		arg.Description,
		arg.InitialStatusID,
		arg.ReturnOrderReasonID,
	)
	return err
}

const updateReturnOrderStatus = `-- name: UpdateReturnOrderStatus :exec
UPDATE return_order SET status_id=?, captured_at=?, closed_at=?
WHERE return_order_id=? AND deleted_at IS NULL
`

type UpdateReturnOrderStatusParams struct {
	StatusID      int32        `json:"status_id"`
	CapturedAt    sql.NullTime `json:"captured_at"`
	ClosedAt      sql.NullTime `json:"closed_at"`
	ReturnOrderID int32        `json:"return_order_id"`
}

func (q *Queries) UpdateReturnOrderStatus(ctx context.Context, arg UpdateReturnOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReturnOrderStatus,
		arg.StatusID,
		arg.CapturedAt,
		arg.ClosedAt,
		arg.ReturnOrderID,
	)
	return err
}

const updateReturnStatusRecord = `-- name: UpdateReturnStatusRecord :exec
UPDATE return_order_status
SET name=?, background_color=?, border_color=?, text_color=?, sort_index=?,
    is_closed=?, is_default=?, is_pending_approval=?
WHERE return_order_status_id=?
`

type UpdateReturnStatusRecordParams struct {
	Name                string `json:"name"`
	BackgroundColor     string `json:"background_color"`
	BorderColor         string `json:"border_color"`
	TextColor           string `json:"text_color"`
	SortIndex           int32  `json:"sort_index"`
	IsClosed            bool   `json:"is_closed"`
	IsDefault           bool   `json:"is_default"`
	IsPendingApproval   bool   `json:"is_pending_approval"`
	ReturnOrderStatusID int32  `json:"return_order_status_id"`
}

func (q *Queries) UpdateReturnStatusRecord(ctx context.Context, arg UpdateReturnStatusRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateReturnStatusRecord,
		arg.Name,
		arg.BackgroundColor,
		arg.BorderColor,
		arg.TextColor,
		arg.SortIndex,
		arg.IsClosed,
		arg.IsDefault,
		arg.IsPendingApproval,
		arg.ReturnOrderStatusID,
	)
	return err
}
