// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sap.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteSapClientAddresses = `-- name: DeleteSapClientAddresses :exec
UPDATE sap_client_address SET deleted_at = CURRENT_TIMESTAMP
WHERE sap_client_code = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteSapClientAddresses(ctx context.Context, sapClientCode string) error {
	_, err := q.db.ExecContext(ctx, deleteSapClientAddresses, sapClientCode)
	return err
}

const deleteSapClientContacts = `-- name: DeleteSapClientContacts :exec
UPDATE sap_client_contact SET deleted_at = CURRENT_TIMESTAMP
WHERE sap_client_code = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteSapClientContacts(ctx context.Context, sapClientCode string) error {
	_, err := q.db.ExecContext(ctx, deleteSapClientContacts, sapClientCode)
	return err
}

const deleteSapClientsNotIn = `-- name: DeleteSapClientsNotIn :exec
UPDATE sap_client SET deleted_at = CURRENT_TIMESTAMP
WHERE deleted_at IS NULL AND sap_client_code NOT IN (/*SLICE:codes*/?)
`

func (q *Queries) DeleteSapClientsNotIn(ctx context.Context, codes []string) error {
	query := deleteSapClientsNotIn
	var queryParams []interface{}
	if len(codes) > 0 {
		for _, v := range codes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:codes*/?", strings.Repeat(",?", len(codes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:codes*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteSapItemsNotIn = `-- name: DeleteSapItemsNotIn :exec
UPDATE sap_item SET deleted_at = CURRENT_TIMESTAMP
WHERE deleted_at IS NULL AND sap_item_code NOT IN (/*SLICE:codes*/?)
`

func (q *Queries) DeleteSapItemsNotIn(ctx context.Context, codes []string) error {
	query := deleteSapItemsNotIn
	var queryParams []interface{}
	if len(codes) > 0 {
		for _, v := range codes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:codes*/?", strings.Repeat(",?", len(codes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:codes*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getSapClientAddresses = `-- name: GetSapClientAddresses :many
SELECT sap_client_address_id, sap_client_code, address_name, address_type, type_of_address,
       street, street_no, block, city, county, state, country, zip_code, building_floor_room
FROM sap_client_address
WHERE sap_client_code = ? AND deleted_at IS NULL
ORDER BY address_name
`

type GetSapClientAddressesRow struct {
	SapClientAddressID int32          `json:"sap_client_address_id"`
	SapClientCode      string         `json:"sap_client_code"`
	AddressName        string         `json:"address_name"`
	AddressType        sql.NullString `json:"address_type"`
	TypeOfAddress      sql.NullString `json:"type_of_address"`
	Street             sql.NullString `json:"street"`
	StreetNo           sql.NullString `json:"street_no"`
	Block              sql.NullString `json:"block"`
	City               sql.NullString `json:"city"`
	County             sql.NullString `json:"county"`
	State              sql.NullString `json:"state"`
	Country            sql.NullString `json:"country"`
	ZipCode            sql.NullString `json:"zip_code"`
	BuildingFloorRoom  sql.NullString `json:"building_floor_room"`
}

func (q *Queries) GetSapClientAddresses(ctx context.Context, sapClientCode string) ([]GetSapClientAddressesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSapClientAddresses, sapClientCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSapClientAddressesRow
	for rows.Next() {
		var i GetSapClientAddressesRow
		if err := rows.Scan(
			&i.SapClientAddressID,
			&i.SapClientCode,
			&i.AddressName,
			&i.AddressType,
			&i.TypeOfAddress,
			&i.Street,
			&i.StreetNo,
			&i.Block,
			&i.City,
			&i.County,
			&i.State,
			&i.Country,
			&i.ZipCode,
			&i.BuildingFloorRoom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSapClientByCode = `-- name: GetSapClientByCode :one
SELECT sap_client_code, name, alias_name, sap_updated_at
FROM sap_client
WHERE sap_client_code = ? AND deleted_at IS NULL
`

type GetSapClientByCodeRow struct {
	SapClientCode string         `json:"sap_client_code"`
	Name          string         `json:"name"`
	AliasName     sql.NullString `json:"alias_name"`
	SapUpdatedAt  sql.NullTime   `json:"sap_updated_at"`
}

func (q *Queries) GetSapClientByCode(ctx context.Context, sapClientCode string) (GetSapClientByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getSapClientByCode, sapClientCode)
	var i GetSapClientByCodeRow
	err := row.Scan(
		&i.SapClientCode,
		&i.Name,
		&i.AliasName,
		&i.SapUpdatedAt,
	)
	return i, err
}

const getSapClientContacts = `-- name: GetSapClientContacts :many
SELECT sap_client_contact_id, sap_client_code, name, contact_name, phone, mobile, email
FROM sap_client_contact
WHERE sap_client_code = ? AND deleted_at IS NULL
ORDER BY name
`

type GetSapClientContactsRow struct {
	SapClientContactID int32          `json:"sap_client_contact_id"`
	SapClientCode      string         `json:"sap_client_code"`
	Name               string         `json:"name"`
	ContactName        sql.NullString `json:"contact_name"`
	Phone              sql.NullString `json:"phone"`
	Mobile             sql.NullString `json:"mobile"`
	Email              sql.NullString `json:"email"`
}

func (q *Queries) GetSapClientContacts(ctx context.Context, sapClientCode string) ([]GetSapClientContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSapClientContacts, sapClientCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSapClientContactsRow
	for rows.Next() {
		var i GetSapClientContactsRow
		if err := rows.Scan(
			&i.SapClientContactID,
			&i.SapClientCode,
			&i.Name,
			&i.ContactName,
			&i.Phone,
			&i.Mobile,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSapItemByCode = `-- name: GetSapItemByCode :one
SELECT sap_item_code, name, sap_updated_at
FROM sap_item
WHERE sap_item_code = ? AND deleted_at IS NULL
`

type GetSapItemByCodeRow struct {
	SapItemCode  string       `json:"sap_item_code"`
	Name         string       `json:"name"`
	SapUpdatedAt sql.NullTime `json:"sap_updated_at"`
}

func (q *Queries) GetSapItemByCode(ctx context.Context, sapItemCode string) (GetSapItemByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getSapItemByCode, sapItemCode)
	var i GetSapItemByCodeRow
	err := row.Scan(&i.SapItemCode, &i.Name, &i.SapUpdatedAt)
	return i, err
}

const searchSapClients = `-- name: SearchSapClients :many

SELECT sap_client_code, name, alias_name
FROM sap_client
WHERE deleted_at IS NULL
  AND (name LIKE CONCAT('%', ?, '%')
    OR alias_name LIKE CONCAT('%', ?, '%')
    OR sap_client_code LIKE CONCAT('%', ?, '%'))
ORDER BY name
LIMIT 20
`

type SearchSapClientsParams struct {
	CONCAT   interface{} `json:"CONCAT"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
	CONCAT_3 interface{} `json:"CONCAT_3"`
}

type SearchSapClientsRow struct {
	SapClientCode string         `json:"sap_client_code"`
	Name          string         `json:"name"`
	AliasName     sql.NullString `json:"alias_name"`
}

// ── SAP Clients ───────────────────────────────────────────────────────────────
func (q *Queries) SearchSapClients(ctx context.Context, arg SearchSapClientsParams) ([]SearchSapClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSapClients, arg.CONCAT, arg.CONCAT_2, arg.CONCAT_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSapClientsRow
	for rows.Next() {
		var i SearchSapClientsRow
		if err := rows.Scan(&i.SapClientCode, &i.Name, &i.AliasName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSapItems = `-- name: SearchSapItems :many

SELECT sap_item_code, name
FROM sap_item
WHERE deleted_at IS NULL
  AND (name LIKE CONCAT('%', ?, '%')
    OR sap_item_code LIKE CONCAT('%', ?, '%'))
ORDER BY name
LIMIT 20
`

type SearchSapItemsParams struct {
	CONCAT   interface{} `json:"CONCAT"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
}

type SearchSapItemsRow struct {
	SapItemCode string `json:"sap_item_code"`
	Name        string `json:"name"`
}

// ── SAP Items ─────────────────────────────────────────────────────────────────
func (q *Queries) SearchSapItems(ctx context.Context, arg SearchSapItemsParams) ([]SearchSapItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSapItems, arg.CONCAT, arg.CONCAT_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSapItemsRow
	for rows.Next() {
		var i SearchSapItemsRow
		if err := rows.Scan(&i.SapItemCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSapClient = `-- name: UpsertSapClient :exec
INSERT INTO sap_client (sap_client_code, name, alias_name, sap_updated_at)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  alias_name = VALUES(alias_name),
  sap_updated_at = VALUES(sap_updated_at),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSapClientParams struct {
	SapClientCode string         `json:"sap_client_code"`
	Name          string         `json:"name"`
	AliasName     sql.NullString `json:"alias_name"`
	SapUpdatedAt  sql.NullTime   `json:"sap_updated_at"`
}

func (q *Queries) UpsertSapClient(ctx context.Context, arg UpsertSapClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertSapClient,
		arg.SapClientCode,
		arg.Name,
		arg.AliasName,
		arg.SapUpdatedAt,
	)
	return err
}

const upsertSapClientAddress = `-- name: UpsertSapClientAddress :exec
INSERT INTO sap_client_address (sap_client_code, address_name, address_type, type_of_address,
    street, street_no, block, city, county, state, country, zip_code, building_floor_room)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  type_of_address = VALUES(type_of_address),
  street = VALUES(street),
  street_no = VALUES(street_no),
  block = VALUES(block),
  city = VALUES(city),
  county = VALUES(county),
  state = VALUES(state),
  country = VALUES(country),
  zip_code = VALUES(zip_code),
  building_floor_room = VALUES(building_floor_room),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSapClientAddressParams struct {
	SapClientCode     string         `json:"sap_client_code"`
	AddressName       string         `json:"address_name"`
	AddressType       sql.NullString `json:"address_type"`
	TypeOfAddress     sql.NullString `json:"type_of_address"`
	Street            sql.NullString `json:"street"`
	StreetNo          sql.NullString `json:"street_no"`
	Block             sql.NullString `json:"block"`
	City              sql.NullString `json:"city"`
	County            sql.NullString `json:"county"`
	State             sql.NullString `json:"state"`
	Country           sql.NullString `json:"country"`
	ZipCode           sql.NullString `json:"zip_code"`
	BuildingFloorRoom sql.NullString `json:"building_floor_room"`
}

func (q *Queries) UpsertSapClientAddress(ctx context.Context, arg UpsertSapClientAddressParams) error {
	_, err := q.db.ExecContext(ctx, upsertSapClientAddress,
		arg.SapClientCode,
		arg.AddressName,
		arg.AddressType,
		arg.TypeOfAddress,
		arg.Street,
		arg.StreetNo,
		arg.Block,
		arg.City,
		arg.County,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.BuildingFloorRoom,
	)
	return err
}

const upsertSapClientContact = `-- name: UpsertSapClientContact :exec
INSERT INTO sap_client_contact (sap_client_code, name, contact_name, phone, mobile, email)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  contact_name = VALUES(contact_name),
  phone = VALUES(phone),
  mobile = VALUES(mobile),
  email = VALUES(email),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSapClientContactParams struct {
	SapClientCode string         `json:"sap_client_code"`
	Name          string         `json:"name"`
	ContactName   sql.NullString `json:"contact_name"`
	Phone         sql.NullString `json:"phone"`
	Mobile        sql.NullString `json:"mobile"`
	Email         sql.NullString `json:"email"`
}

func (q *Queries) UpsertSapClientContact(ctx context.Context, arg UpsertSapClientContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertSapClientContact,
		arg.SapClientCode,
		arg.Name,
		arg.ContactName,
		arg.Phone,
		arg.Mobile,
		arg.Email,
	)
	return err
}

const upsertSapItem = `-- name: UpsertSapItem :exec
INSERT INTO sap_item (sap_item_code, name, sap_updated_at)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  sap_updated_at = VALUES(sap_updated_at),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSapItemParams struct {
	SapItemCode  string       `json:"sap_item_code"`
	Name         string       `json:"name"`
	SapUpdatedAt sql.NullTime `json:"sap_updated_at"`
}

func (q *Queries) UpsertSapItem(ctx context.Context, arg UpsertSapItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertSapItem, arg.SapItemCode, arg.Name, arg.SapUpdatedAt)
	return err
}
